// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package recovery is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	CheckPointMessage
*/
package recovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckPointMessage struct {
	// From the message source
	CurrentNumber  uint64 `protobuf:"varint,1,opt,name=currentNumber" json:"currentNumber,omitempty"`
	RequiredNumber uint64 `protobuf:"varint,2,opt,name=requiredNumber" json:"requiredNumber,omitempty"`
	PeerId         uint64 `protobuf:"varint,3,opt,name=peerId" json:"peerId,omitempty"`
}

func (m *CheckPointMessage) Reset()                    { *m = CheckPointMessage{} }
func (m *CheckPointMessage) String() string            { return proto.CompactTextString(m) }
func (*CheckPointMessage) ProtoMessage()               {}
func (*CheckPointMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CheckPointMessage) GetCurrentNumber() uint64 {
	if m != nil {
		return m.CurrentNumber
	}
	return 0
}

func (m *CheckPointMessage) GetRequiredNumber() uint64 {
	if m != nil {
		return m.RequiredNumber
	}
	return 0
}

func (m *CheckPointMessage) GetPeerId() uint64 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckPointMessage)(nil), "recovery.CheckPointMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4a, 0x4d, 0xce, 0x2f,
	0x4b, 0x2d, 0xaa, 0x54, 0xaa, 0xe4, 0x12, 0x74, 0xce, 0x48, 0x4d, 0xce, 0x0e, 0xc8, 0xcf, 0xcc,
	0x2b, 0xf1, 0x85, 0x28, 0x12, 0x52, 0xe1, 0xe2, 0x4d, 0x2e, 0x2d, 0x2a, 0x4a, 0xcd, 0x2b, 0xf1,
	0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x42, 0x15, 0x14, 0x52,
	0xe3, 0xe2, 0x2b, 0x4a, 0x2d, 0x2c, 0xcd, 0x2c, 0x4a, 0x4d, 0x81, 0x2a, 0x63, 0x02, 0x2b, 0x43,
	0x13, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x48, 0x4d, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x06, 0xcb, 0x43,
	0x79, 0x49, 0x6c, 0x60, 0xb7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xd5, 0xb2, 0x00,
	0x9c, 0x00, 0x00, 0x00,
}
