stages:
  - build
  - test

build-my-project:
  stage: build
  script:
    - mkdir -p /builds/chenquan/goenv/
    - pwd
    - export GOPATH=/builds/chenquan/goenv/
    - go get -u github.com/Masterminds/glide
    - glide install
    - go env
    - go test
  only:
    - test
  tags:
    - golang

test-my-project:
  stage: test
  script:
    - go get -u github.com/Masterminds/glide
    - glide install
    - go test -v ./...
  only:
    - test
  tags:
    - golang

