before_script:
  - ORG_DIR="$GOPATH/src/github.com/hyperchain"
  - HYPERCHAIN_DIR="$ORG_DIR/$CI_PROJECT_NAME"
  - echo $ORG_DIR
  - echo $HYPERCHAIN_DIR
  - mkdir -p $ORG_DIR
  - ln -sfv "$(pwd -P)" "$HYPERCHAIN_DIR"
  - cd "$HYPERCHAIN_DIR"

stages:
  - build
  - test

project-build:
  stage: build
  script:
    - pwd
    - go env
    - go build -ldflags -s
  only:
    -  /^release1.4.*$/ # ignore all release1.2* branches
    - opensource


unit-test:
  stage: test
  script:
    - pwd
    - go env
    - go test ./...
  only:
    -  /^release1.4.*$/ # ignore all release1.2* branches
    - opensource
