stages:
  - test
  - build

test-my-project:
  stage: test
  script:
    - go env
    - go get -d
    - go test
  only: 
    - develop
  tags:
    - golang
build-my-project:
  stage: build
  script:
    - go env
    - go get -d
  only:
    - develop
  tags:
    - golang

