before_script:
  - GO_NAMESPACE="$GOPATH/src/git.hyperchain.cn/$CI_PROJECT_NAMESPACE"
  - GO_DIR="$GO_NAMESPACE/$CI_PROJECT_NAME"
  - echo $GO_NAMESPACE
  - echo $GO_DIR
  - mkdir -p $GO_NAMESPACE
  - ln -sfv "$(pwd -P)" "$GO_DIR"
  - cd "$GO_DIR"

stages:
  - build
  - test
  - deploy

job-00:
  stage: build
  script:
    - go get
    - go build
    - ./example
  only:
    - master
  tags:
    - golang