stages:
  - test
  - build

test-my-project:
  stage: test
  script:
    - mkdir -p /builds/hyperchain/goenv/
    - export GOPATH=/builds/hyperchain/goenv/
    - go env
    - go get -u github.com/kardianos/govendor
    - govender sync
    - govender test +local
  only: 
    - develop
  tags:
    - golang
build-my-project:
  stage: build
  script:
    - mkdir -p /builds/hyperchain/goenv/
    - export GOPATH=/builds/hyperchain/goenv/
    - go env
    - go get -u github.com/kardianos/govendor
    - govender sync
    - govender test +local
  only:
    - develop
  tags:
    - golang

