stages:
  - test
  - build

test-my-project:
  stage: test
  script:
    - go env
    - go get -u github.com/kardianos/govendor
    - govendor sync
    - govendor test +local
  only: 
    - develop
  tags:
    - golang
build-my-project:
  stage: build
  script:
    - go env
    - go get -u github.com/kardianos/govendor
    - govendor sync
    - govendor test +local
  only:
    - develop
  tags:
    - golang

