before_script:
  - GO_NAMESPACE="$GOPATH/src"
  - GO_DIR="$GO_NAMESPACE/$CI_PROJECT_NAME"
  - echo $GO_NAMESPACE
  - echo $GO_DIR
  - mkdir -p $GO_NAMESPACE
  - ln -sfv "$(pwd -P)" "$GO_DIR"
  - cd "$GO_DIR"

stages:
  - build
  - test

project-build:
  stage: build
  script:
    - pwd
    - go env
    - go get -u github.com/kardianos/govendor
    - govendor build
  except:
    -  /^release1.2-.*$/ # ignore all release1.2* branches
    -  release1.1


unit-test:
  stage: test
  script:
    - pwd
    - go env
    - go get -u github.com/kardianos/govendor
    - govendor sync
    - govendor test +local
  except:
    -  /^release1.2-.*$/ # ignore all release1.2* branches
    -  release1.1
