before_script:
  - GO_NAMESPACE="$GOPATH/src"
  - GO_DIR="$GO_NAMESPACE/$CI_PROJECT_NAME"
  - echo $GO_NAMESPACE
  - echo $GO_DIR
  - mkdir -p $GO_NAMESPACE
  - ln -sfv "$(pwd -P)" "$GO_DIR"
  - cd "$GO_DIR"

stages:
  - test
  - build
  - deploy

job-test:
  stage: test
  script:
    - pwd
    - go env
    - go get -u github.com/kardianos/govendor
    - govendor sync
    - govendor test +local
  only:
    - develop
  tags:
    - golang