// Code generated by protoc-gen-go.
// source: transaction.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	transaction.proto

It has these top-level messages:
	TransactionV1_2
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionV1_2 struct {
	Version         []byte `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	From            []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To              []byte `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value           []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp       int64  `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Signature       []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Id              uint64 `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	TransactionHash []byte `protobuf:"bytes,8,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Nonce           int64  `protobuf:"varint,9,opt,name=nonce" json:"nonce,omitempty"`
}

func (m *TransactionV1_2) Reset()                    { *m = TransactionV1_2{} }
func (m *TransactionV1_2) String() string            { return proto.CompactTextString(m) }
func (*TransactionV1_2) ProtoMessage()               {}
func (*TransactionV1_2) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *TransactionV1_2) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *TransactionV1_2) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionV1_2) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionV1_2) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionV1_2) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionV1_2) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TransactionV1_2) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransactionV1_2) GetTransactionHash() []byte {
	if m != nil {
		return m.TransactionHash
	}
	return nil
}

func (m *TransactionV1_2) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*TransactionV1_2)(nil), "types.TransactionV1_2")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x40,
	0x0c, 0x85, 0x99, 0xd9, 0x76, 0xd7, 0x0d, 0xe2, 0x62, 0xf0, 0x90, 0x83, 0x87, 0xe2, 0x69, 0x4e,
	0x82, 0xfa, 0x27, 0x3c, 0x17, 0xf1, 0x2a, 0x63, 0x3b, 0xea, 0x80, 0x9d, 0x94, 0x99, 0xb4, 0xe0,
	0xcf, 0xf6, 0x1f, 0x48, 0x53, 0xa4, 0xe2, 0x2d, 0xef, 0x7b, 0x3c, 0x5e, 0x12, 0xb8, 0x94, 0xec,
	0x53, 0xf1, 0x9d, 0x44, 0x4e, 0xb7, 0x63, 0x66, 0x61, 0xac, 0xe5, 0x6b, 0x0c, 0xe5, 0xe6, 0xdb,
	0xc0, 0xe9, 0x69, 0x33, 0x9f, 0xef, 0x5e, 0xee, 0x91, 0xe0, 0x30, 0x87, 0x5c, 0x22, 0x27, 0x32,
	0x8d, 0x71, 0xe7, 0xed, 0xaf, 0x44, 0x84, 0xea, 0x2d, 0xf3, 0x40, 0x56, 0xb1, 0xce, 0x78, 0x01,
	0x56, 0x98, 0x76, 0x4a, 0xac, 0x30, 0x5e, 0x41, 0x3d, 0xfb, 0xcf, 0x29, 0x50, 0xa5, 0x68, 0x15,
	0x78, 0x0d, 0x47, 0x89, 0x43, 0x28, 0xe2, 0x87, 0x91, 0xea, 0xc6, 0xb8, 0x5d, 0xbb, 0x81, 0xc5,
	0x2d, 0xf1, 0x3d, 0x79, 0x99, 0x72, 0xa0, 0xbd, 0xe6, 0x36, 0xb0, 0x34, 0xc4, 0x9e, 0x0e, 0x8d,
	0x71, 0x55, 0x6b, 0x63, 0x8f, 0x0e, 0x4e, 0x7f, 0xee, 0x79, 0xf4, 0xe5, 0x83, 0xce, 0x34, 0xf3,
	0x1f, 0x2f, 0xbb, 0x24, 0x4e, 0x5d, 0xa0, 0xa3, 0x36, 0xae, 0xe2, 0x75, 0xaf, 0x1f, 0x78, 0xf8,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x23, 0xaf, 0xf7, 0x16, 0x01, 0x00, 0x00,
}
