// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package rbft is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ConsensusMessage
	TransactionBatch
	HashBatch
	ReturnRequestBatch
	FetchMissingTransaction
	ReturnMissingTransaction
	PrePrepare
	Prepare
	Commit
	BlockInfo
	Checkpoint
	Vc_C
	Vc_PQ
	VcBasis
	ViewChange
	NewView
	FinishVcReset
	FetchRequestBatch
	NegotiateView
	NegotiateViewResponse
	RecoveryInit
	RecoveryResponse
	RecoveryFetchPQC
	RecoveryReturnPQC
	Pset
	Cset
	AddNode
	DelNode
	ReadyForN
	AgreeUpdateN
	UpdateN
	FinishUpdate
*/
package rbft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/hyperchain/hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsensusMessage_Type int32

const (
	ConsensusMessage_TRANSACTION                ConsensusMessage_Type = 0
	ConsensusMessage_PRE_PREPARE                ConsensusMessage_Type = 1
	ConsensusMessage_PREPARE                    ConsensusMessage_Type = 2
	ConsensusMessage_COMMIT                     ConsensusMessage_Type = 3
	ConsensusMessage_CHECKPOINT                 ConsensusMessage_Type = 4
	ConsensusMessage_VIEW_CHANGE                ConsensusMessage_Type = 5
	ConsensusMessage_NEW_VIEW                   ConsensusMessage_Type = 6
	ConsensusMessage_FINISH_VCRESET             ConsensusMessage_Type = 7
	ConsensusMessage_FRTCH_REQUEST_BATCH        ConsensusMessage_Type = 8
	ConsensusMessage_RETURN_REQUEST_BATCH       ConsensusMessage_Type = 9
	ConsensusMessage_NEGOTIATE_VIEW             ConsensusMessage_Type = 10
	ConsensusMessage_NEGOTIATE_VIEW_RESPONSE    ConsensusMessage_Type = 11
	ConsensusMessage_RECOVERY_INIT              ConsensusMessage_Type = 12
	ConsensusMessage_RECOVERY_RESPONSE          ConsensusMessage_Type = 13
	ConsensusMessage_RECOVERY_FETCH_QPC         ConsensusMessage_Type = 14
	ConsensusMessage_RECOVERY_RETURN_QPC        ConsensusMessage_Type = 15
	ConsensusMessage_ADD_NODE                   ConsensusMessage_Type = 16
	ConsensusMessage_DEL_NODE                   ConsensusMessage_Type = 17
	ConsensusMessage_READY_FOR_N                ConsensusMessage_Type = 18
	ConsensusMessage_AGREE_UPDATE_N             ConsensusMessage_Type = 19
	ConsensusMessage_UPDATE_N                   ConsensusMessage_Type = 20
	ConsensusMessage_FINISH_UPDATE              ConsensusMessage_Type = 21
	ConsensusMessage_FETCH_MISSING_TRANSACTION  ConsensusMessage_Type = 22
	ConsensusMessage_RETURN_MISSING_TRANSACTION ConsensusMessage_Type = 23
)

var ConsensusMessage_Type_name = map[int32]string{
	0:  "TRANSACTION",
	1:  "PRE_PREPARE",
	2:  "PREPARE",
	3:  "COMMIT",
	4:  "CHECKPOINT",
	5:  "VIEW_CHANGE",
	6:  "NEW_VIEW",
	7:  "FINISH_VCRESET",
	8:  "FRTCH_REQUEST_BATCH",
	9:  "RETURN_REQUEST_BATCH",
	10: "NEGOTIATE_VIEW",
	11: "NEGOTIATE_VIEW_RESPONSE",
	12: "RECOVERY_INIT",
	13: "RECOVERY_RESPONSE",
	14: "RECOVERY_FETCH_QPC",
	15: "RECOVERY_RETURN_QPC",
	16: "ADD_NODE",
	17: "DEL_NODE",
	18: "READY_FOR_N",
	19: "AGREE_UPDATE_N",
	20: "UPDATE_N",
	21: "FINISH_UPDATE",
	22: "FETCH_MISSING_TRANSACTION",
	23: "RETURN_MISSING_TRANSACTION",
}
var ConsensusMessage_Type_value = map[string]int32{
	"TRANSACTION":                0,
	"PRE_PREPARE":                1,
	"PREPARE":                    2,
	"COMMIT":                     3,
	"CHECKPOINT":                 4,
	"VIEW_CHANGE":                5,
	"NEW_VIEW":                   6,
	"FINISH_VCRESET":             7,
	"FRTCH_REQUEST_BATCH":        8,
	"RETURN_REQUEST_BATCH":       9,
	"NEGOTIATE_VIEW":             10,
	"NEGOTIATE_VIEW_RESPONSE":    11,
	"RECOVERY_INIT":              12,
	"RECOVERY_RESPONSE":          13,
	"RECOVERY_FETCH_QPC":         14,
	"RECOVERY_RETURN_QPC":        15,
	"ADD_NODE":                   16,
	"DEL_NODE":                   17,
	"READY_FOR_N":                18,
	"AGREE_UPDATE_N":             19,
	"UPDATE_N":                   20,
	"FINISH_UPDATE":              21,
	"FETCH_MISSING_TRANSACTION":  22,
	"RETURN_MISSING_TRANSACTION": 23,
}

func (x ConsensusMessage_Type) String() string {
	return proto.EnumName(ConsensusMessage_Type_name, int32(x))
}
func (ConsensusMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ConsensusMessage struct {
	Type    ConsensusMessage_Type `protobuf:"varint,1,opt,name=type,enum=rbft.ConsensusMessage_Type" json:"type,omitempty"`
	Payload []byte                `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ConsensusMessage) Reset()                    { *m = ConsensusMessage{} }
func (m *ConsensusMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusMessage) ProtoMessage()               {}
func (*ConsensusMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConsensusMessage) GetType() ConsensusMessage_Type {
	if m != nil {
		return m.Type
	}
	return ConsensusMessage_TRANSACTION
}

func (m *ConsensusMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TransactionBatch struct {
	TxList     []*types.Transaction `protobuf:"bytes,1,rep,name=tx_list,json=txList" json:"tx_list,omitempty"`
	HashList   []string             `protobuf:"bytes,2,rep,name=hash_list,json=hashList" json:"hash_list,omitempty"`
	Timestamp  int64                `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	SeqNo      uint64               `protobuf:"varint,4,opt,name=seq_no,json=seqNo" json:"seq_no,omitempty"`
	ResultHash string               `protobuf:"bytes,5,opt,name=resultHash" json:"resultHash,omitempty"`
}

func (m *TransactionBatch) Reset()                    { *m = TransactionBatch{} }
func (m *TransactionBatch) String() string            { return proto.CompactTextString(m) }
func (*TransactionBatch) ProtoMessage()               {}
func (*TransactionBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionBatch) GetTxList() []*types.Transaction {
	if m != nil {
		return m.TxList
	}
	return nil
}

func (m *TransactionBatch) GetHashList() []string {
	if m != nil {
		return m.HashList
	}
	return nil
}

func (m *TransactionBatch) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionBatch) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *TransactionBatch) GetResultHash() string {
	if m != nil {
		return m.ResultHash
	}
	return ""
}

type HashBatch struct {
	List      []string `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Timestamp int64    `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *HashBatch) Reset()                    { *m = HashBatch{} }
func (m *HashBatch) String() string            { return proto.CompactTextString(m) }
func (*HashBatch) ProtoMessage()               {}
func (*HashBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HashBatch) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *HashBatch) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ReturnRequestBatch struct {
	Batch       *TransactionBatch `protobuf:"bytes,1,opt,name=batch" json:"batch,omitempty"`
	BatchDigest string            `protobuf:"bytes,2,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId   uint64            `protobuf:"varint,3,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *ReturnRequestBatch) Reset()                    { *m = ReturnRequestBatch{} }
func (m *ReturnRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*ReturnRequestBatch) ProtoMessage()               {}
func (*ReturnRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReturnRequestBatch) GetBatch() *TransactionBatch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *ReturnRequestBatch) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *ReturnRequestBatch) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type FetchMissingTransaction struct {
	View           uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64            `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string            `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	HashList       map[uint64]string `protobuf:"bytes,4,rep,name=hash_list,json=hashList" json:"hash_list,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReplicaId      uint64            `protobuf:"varint,5,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *FetchMissingTransaction) Reset()                    { *m = FetchMissingTransaction{} }
func (m *FetchMissingTransaction) String() string            { return proto.CompactTextString(m) }
func (*FetchMissingTransaction) ProtoMessage()               {}
func (*FetchMissingTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FetchMissingTransaction) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *FetchMissingTransaction) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *FetchMissingTransaction) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *FetchMissingTransaction) GetHashList() map[uint64]string {
	if m != nil {
		return m.HashList
	}
	return nil
}

func (m *FetchMissingTransaction) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type ReturnMissingTransaction struct {
	View           uint64                        `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64                        `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string                        `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	HashList       map[uint64]string             `protobuf:"bytes,4,rep,name=hash_list,json=hashList" json:"hash_list,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TxList         map[uint64]*types.Transaction `protobuf:"bytes,5,rep,name=tx_list,json=txList" json:"tx_list,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReplicaId      uint64                        `protobuf:"varint,6,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *ReturnMissingTransaction) Reset()                    { *m = ReturnMissingTransaction{} }
func (m *ReturnMissingTransaction) String() string            { return proto.CompactTextString(m) }
func (*ReturnMissingTransaction) ProtoMessage()               {}
func (*ReturnMissingTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReturnMissingTransaction) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ReturnMissingTransaction) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ReturnMissingTransaction) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *ReturnMissingTransaction) GetHashList() map[uint64]string {
	if m != nil {
		return m.HashList
	}
	return nil
}

func (m *ReturnMissingTransaction) GetTxList() map[uint64]*types.Transaction {
	if m != nil {
		return m.TxList
	}
	return nil
}

func (m *ReturnMissingTransaction) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type PrePrepare struct {
	View           uint64     `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64     `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string     `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ResultHash     string     `protobuf:"bytes,4,opt,name=result_hash,json=resultHash" json:"result_hash,omitempty"`
	HashBatch      *HashBatch `protobuf:"bytes,5,opt,name=hash_batch,json=hashBatch" json:"hash_batch,omitempty"`
	ReplicaId      uint64     `protobuf:"varint,6,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *PrePrepare) Reset()                    { *m = PrePrepare{} }
func (m *PrePrepare) String() string            { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()               {}
func (*PrePrepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *PrePrepare) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *PrePrepare) GetResultHash() string {
	if m != nil {
		return m.ResultHash
	}
	return ""
}

func (m *PrePrepare) GetHashBatch() *HashBatch {
	if m != nil {
		return m.HashBatch
	}
	return nil
}

func (m *PrePrepare) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type Prepare struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ResultHash     string `protobuf:"bytes,4,opt,name=result_hash,json=resultHash" json:"result_hash,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,5,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Prepare) Reset()                    { *m = Prepare{} }
func (m *Prepare) String() string            { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()               {}
func (*Prepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Prepare) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *Prepare) GetResultHash() string {
	if m != nil {
		return m.ResultHash
	}
	return ""
}

func (m *Prepare) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type Commit struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ResultHash     string `protobuf:"bytes,4,opt,name=result_hash,json=resultHash" json:"result_hash,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,5,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Commit) Reset()                    { *m = Commit{} }
func (m *Commit) String() string            { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()               {}
func (*Commit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Commit) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *Commit) GetResultHash() string {
	if m != nil {
		return m.ResultHash
	}
	return ""
}

func (m *Commit) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type BlockInfo struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number,omitempty"`
	BlockHash   []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (m *BlockInfo) Reset()                    { *m = BlockInfo{} }
func (m *BlockInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()               {}
func (*BlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BlockInfo) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockInfo) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type Checkpoint struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Genesis        uint64 `protobuf:"varint,4,opt,name=genesis" json:"genesis,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Checkpoint) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Checkpoint) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Checkpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Checkpoint) GetGenesis() uint64 {
	if m != nil {
		return m.Genesis
	}
	return 0
}

// This message should go away and become a checkpoint once replica_id is removed
type Vc_C struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	Id             string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *Vc_C) Reset()                    { *m = Vc_C{} }
func (m *Vc_C) String() string            { return proto.CompactTextString(m) }
func (*Vc_C) ProtoMessage()               {}
func (*Vc_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Vc_C) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Vc_C) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Vc_PQ struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,2,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	View           uint64 `protobuf:"varint,3,opt,name=view" json:"view,omitempty"`
}

func (m *Vc_PQ) Reset()                    { *m = Vc_PQ{} }
func (m *Vc_PQ) String() string            { return proto.CompactTextString(m) }
func (*Vc_PQ) ProtoMessage()               {}
func (*Vc_PQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Vc_PQ) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Vc_PQ) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *Vc_PQ) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

type VcBasis struct {
	View      uint64   `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	H         uint64   `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Cset      []*Vc_C  `protobuf:"bytes,3,rep,name=cset" json:"cset,omitempty"`
	Pset      []*Vc_PQ `protobuf:"bytes,4,rep,name=pset" json:"pset,omitempty"`
	Qset      []*Vc_PQ `protobuf:"bytes,5,rep,name=qset" json:"qset,omitempty"`
	ReplicaId uint64   `protobuf:"varint,6,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Genesis   uint64   `protobuf:"varint,7,opt,name=genesis" json:"genesis,omitempty"`
}

func (m *VcBasis) Reset()                    { *m = VcBasis{} }
func (m *VcBasis) String() string            { return proto.CompactTextString(m) }
func (*VcBasis) ProtoMessage()               {}
func (*VcBasis) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *VcBasis) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *VcBasis) GetH() uint64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *VcBasis) GetCset() []*Vc_C {
	if m != nil {
		return m.Cset
	}
	return nil
}

func (m *VcBasis) GetPset() []*Vc_PQ {
	if m != nil {
		return m.Pset
	}
	return nil
}

func (m *VcBasis) GetQset() []*Vc_PQ {
	if m != nil {
		return m.Qset
	}
	return nil
}

func (m *VcBasis) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *VcBasis) GetGenesis() uint64 {
	if m != nil {
		return m.Genesis
	}
	return 0
}

type ViewChange struct {
	Basis     *VcBasis `protobuf:"bytes,1,opt,name=basis" json:"basis,omitempty"`
	Signature []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp int64    `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ViewChange) Reset()                    { *m = ViewChange{} }
func (m *ViewChange) String() string            { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()               {}
func (*ViewChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ViewChange) GetBasis() *VcBasis {
	if m != nil {
		return m.Basis
	}
	return nil
}

func (m *ViewChange) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ViewChange) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type NewView struct {
	View      uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	Xset      map[uint64]string `protobuf:"bytes,2,rep,name=xset" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReplicaId uint64            `protobuf:"varint,3,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NewView) Reset()                    { *m = NewView{} }
func (m *NewView) String() string            { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()               {}
func (*NewView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *NewView) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NewView) GetXset() map[uint64]string {
	if m != nil {
		return m.Xset
	}
	return nil
}

func (m *NewView) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type FinishVcReset struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
	LowH      uint64 `protobuf:"varint,3,opt,name=low_h,json=lowH" json:"low_h,omitempty"`
}

func (m *FinishVcReset) Reset()                    { *m = FinishVcReset{} }
func (m *FinishVcReset) String() string            { return proto.CompactTextString(m) }
func (*FinishVcReset) ProtoMessage()               {}
func (*FinishVcReset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *FinishVcReset) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *FinishVcReset) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *FinishVcReset) GetLowH() uint64 {
	if m != nil {
		return m.LowH
	}
	return 0
}

type FetchRequestBatch struct {
	BatchDigest string `protobuf:"bytes,1,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId   uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *FetchRequestBatch) Reset()                    { *m = FetchRequestBatch{} }
func (m *FetchRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*FetchRequestBatch) ProtoMessage()               {}
func (*FetchRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *FetchRequestBatch) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *FetchRequestBatch) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type NegotiateView struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NegotiateView) Reset()                    { *m = NegotiateView{} }
func (m *NegotiateView) String() string            { return proto.CompactTextString(m) }
func (*NegotiateView) ProtoMessage()               {}
func (*NegotiateView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *NegotiateView) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type NegotiateViewResponse struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
	N         uint64 `protobuf:"varint,3,opt,name=n" json:"n,omitempty"`
	Routers   []byte `protobuf:"bytes,4,opt,name=routers,proto3" json:"routers,omitempty"`
}

func (m *NegotiateViewResponse) Reset()                    { *m = NegotiateViewResponse{} }
func (m *NegotiateViewResponse) String() string            { return proto.CompactTextString(m) }
func (*NegotiateViewResponse) ProtoMessage()               {}
func (*NegotiateViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *NegotiateViewResponse) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *NegotiateViewResponse) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NegotiateViewResponse) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *NegotiateViewResponse) GetRouters() []byte {
	if m != nil {
		return m.Routers
	}
	return nil
}

type RecoveryInit struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *RecoveryInit) Reset()                    { *m = RecoveryInit{} }
func (m *RecoveryInit) String() string            { return proto.CompactTextString(m) }
func (*RecoveryInit) ProtoMessage()               {}
func (*RecoveryInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RecoveryInit) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type RecoveryResponse struct {
	ReplicaId     uint64            `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Chkpts        map[uint64]string `protobuf:"bytes,2,rep,name=chkpts" json:"chkpts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BlockHeight   uint64            `protobuf:"varint,3,opt,name=blockHeight" json:"blockHeight,omitempty"`
	LastBlockHash string            `protobuf:"bytes,4,opt,name=lastBlockHash" json:"lastBlockHash,omitempty"`
	Genesis       uint64            `protobuf:"varint,5,opt,name=genesis" json:"genesis,omitempty"`
}

func (m *RecoveryResponse) Reset()                    { *m = RecoveryResponse{} }
func (m *RecoveryResponse) String() string            { return proto.CompactTextString(m) }
func (*RecoveryResponse) ProtoMessage()               {}
func (*RecoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RecoveryResponse) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *RecoveryResponse) GetChkpts() map[uint64]string {
	if m != nil {
		return m.Chkpts
	}
	return nil
}

func (m *RecoveryResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *RecoveryResponse) GetLastBlockHash() string {
	if m != nil {
		return m.LastBlockHash
	}
	return ""
}

func (m *RecoveryResponse) GetGenesis() uint64 {
	if m != nil {
		return m.Genesis
	}
	return 0
}

type RecoveryFetchPQC struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	H         uint64 `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
}

func (m *RecoveryFetchPQC) Reset()                    { *m = RecoveryFetchPQC{} }
func (m *RecoveryFetchPQC) String() string            { return proto.CompactTextString(m) }
func (*RecoveryFetchPQC) ProtoMessage()               {}
func (*RecoveryFetchPQC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RecoveryFetchPQC) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *RecoveryFetchPQC) GetH() uint64 {
	if m != nil {
		return m.H
	}
	return 0
}

type RecoveryReturnPQC struct {
	ReplicaId uint64        `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	PrepreSet []*PrePrepare `protobuf:"bytes,2,rep,name=prepre_set,json=prepreSet" json:"prepre_set,omitempty"`
	PreSet    []*Prepare    `protobuf:"bytes,3,rep,name=pre_set,json=preSet" json:"pre_set,omitempty"`
	CmtSet    []*Commit     `protobuf:"bytes,4,rep,name=cmt_set,json=cmtSet" json:"cmt_set,omitempty"`
}

func (m *RecoveryReturnPQC) Reset()                    { *m = RecoveryReturnPQC{} }
func (m *RecoveryReturnPQC) String() string            { return proto.CompactTextString(m) }
func (*RecoveryReturnPQC) ProtoMessage()               {}
func (*RecoveryReturnPQC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RecoveryReturnPQC) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *RecoveryReturnPQC) GetPrepreSet() []*PrePrepare {
	if m != nil {
		return m.PrepreSet
	}
	return nil
}

func (m *RecoveryReturnPQC) GetPreSet() []*Prepare {
	if m != nil {
		return m.PreSet
	}
	return nil
}

func (m *RecoveryReturnPQC) GetCmtSet() []*Commit {
	if m != nil {
		return m.CmtSet
	}
	return nil
}

type Pset struct {
	Set []*Prepare `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (m *Pset) Reset()                    { *m = Pset{} }
func (m *Pset) String() string            { return proto.CompactTextString(m) }
func (*Pset) ProtoMessage()               {}
func (*Pset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Pset) GetSet() []*Prepare {
	if m != nil {
		return m.Set
	}
	return nil
}

type Cset struct {
	Set []*Commit `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (m *Cset) Reset()                    { *m = Cset{} }
func (m *Cset) String() string            { return proto.CompactTextString(m) }
func (*Cset) ProtoMessage()               {}
func (*Cset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *Cset) GetSet() []*Commit {
	if m != nil {
		return m.Set
	}
	return nil
}

type AddNode struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *AddNode) Reset()                    { *m = AddNode{} }
func (m *AddNode) String() string            { return proto.CompactTextString(m) }
func (*AddNode) ProtoMessage()               {}
func (*AddNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *AddNode) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *AddNode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelNode struct {
	ReplicaId  uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key        string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	RouterHash string `protobuf:"bytes,3,opt,name=router_hash,json=routerHash" json:"router_hash,omitempty"`
}

func (m *DelNode) Reset()                    { *m = DelNode{} }
func (m *DelNode) String() string            { return proto.CompactTextString(m) }
func (*DelNode) ProtoMessage()               {}
func (*DelNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *DelNode) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *DelNode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DelNode) GetRouterHash() string {
	if m != nil {
		return m.RouterHash
	}
	return ""
}

type ReadyForN struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *ReadyForN) Reset()                    { *m = ReadyForN{} }
func (m *ReadyForN) String() string            { return proto.CompactTextString(m) }
func (*ReadyForN) ProtoMessage()               {}
func (*ReadyForN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ReadyForN) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *ReadyForN) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AgreeUpdateN struct {
	Basis      *VcBasis `protobuf:"bytes,1,opt,name=basis" json:"basis,omitempty"`
	Flag       bool     `protobuf:"varint,2,opt,name=flag" json:"flag,omitempty"`
	Key        string   `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	RouterHash string   `protobuf:"bytes,4,opt,name=routerHash" json:"routerHash,omitempty"`
	N          int64    `protobuf:"varint,5,opt,name=n" json:"n,omitempty"`
}

func (m *AgreeUpdateN) Reset()                    { *m = AgreeUpdateN{} }
func (m *AgreeUpdateN) String() string            { return proto.CompactTextString(m) }
func (*AgreeUpdateN) ProtoMessage()               {}
func (*AgreeUpdateN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *AgreeUpdateN) GetBasis() *VcBasis {
	if m != nil {
		return m.Basis
	}
	return nil
}

func (m *AgreeUpdateN) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *AgreeUpdateN) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AgreeUpdateN) GetRouterHash() string {
	if m != nil {
		return m.RouterHash
	}
	return ""
}

func (m *AgreeUpdateN) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

type UpdateN struct {
	Flag      bool              `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
	ReplicaId uint64            `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key       string            `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	N         int64             `protobuf:"varint,4,opt,name=n" json:"n,omitempty"`
	View      uint64            `protobuf:"varint,5,opt,name=view" json:"view,omitempty"`
	Xset      map[uint64]string `protobuf:"bytes,6,rep,name=xset" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *UpdateN) Reset()                    { *m = UpdateN{} }
func (m *UpdateN) String() string            { return proto.CompactTextString(m) }
func (*UpdateN) ProtoMessage()               {}
func (*UpdateN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *UpdateN) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *UpdateN) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *UpdateN) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateN) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *UpdateN) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *UpdateN) GetXset() map[uint64]string {
	if m != nil {
		return m.Xset
	}
	return nil
}

type FinishUpdate struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
	LowH      uint64 `protobuf:"varint,3,opt,name=low_h,json=lowH" json:"low_h,omitempty"`
}

func (m *FinishUpdate) Reset()                    { *m = FinishUpdate{} }
func (m *FinishUpdate) String() string            { return proto.CompactTextString(m) }
func (*FinishUpdate) ProtoMessage()               {}
func (*FinishUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *FinishUpdate) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *FinishUpdate) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *FinishUpdate) GetLowH() uint64 {
	if m != nil {
		return m.LowH
	}
	return 0
}

func init() {
	proto.RegisterType((*ConsensusMessage)(nil), "rbft.consensus_message")
	proto.RegisterType((*TransactionBatch)(nil), "rbft.transaction_batch")
	proto.RegisterType((*HashBatch)(nil), "rbft.hash_batch")
	proto.RegisterType((*ReturnRequestBatch)(nil), "rbft.return_request_batch")
	proto.RegisterType((*FetchMissingTransaction)(nil), "rbft.fetch_missing_transaction")
	proto.RegisterType((*ReturnMissingTransaction)(nil), "rbft.return_missing_transaction")
	proto.RegisterType((*PrePrepare)(nil), "rbft.pre_prepare")
	proto.RegisterType((*Prepare)(nil), "rbft.prepare")
	proto.RegisterType((*Commit)(nil), "rbft.commit")
	proto.RegisterType((*BlockInfo)(nil), "rbft.block_info")
	proto.RegisterType((*Checkpoint)(nil), "rbft.checkpoint")
	proto.RegisterType((*Vc_C)(nil), "rbft.vc_C")
	proto.RegisterType((*Vc_PQ)(nil), "rbft.vc_PQ")
	proto.RegisterType((*VcBasis)(nil), "rbft.vc_basis")
	proto.RegisterType((*ViewChange)(nil), "rbft.view_change")
	proto.RegisterType((*NewView)(nil), "rbft.new_view")
	proto.RegisterType((*FinishVcReset)(nil), "rbft.finish_vcReset")
	proto.RegisterType((*FetchRequestBatch)(nil), "rbft.fetch_request_batch")
	proto.RegisterType((*NegotiateView)(nil), "rbft.negotiate_view")
	proto.RegisterType((*NegotiateViewResponse)(nil), "rbft.negotiate_view_response")
	proto.RegisterType((*RecoveryInit)(nil), "rbft.recovery_init")
	proto.RegisterType((*RecoveryResponse)(nil), "rbft.recovery_response")
	proto.RegisterType((*RecoveryFetchPQC)(nil), "rbft.recovery_fetchPQC")
	proto.RegisterType((*RecoveryReturnPQC)(nil), "rbft.recovery_returnPQC")
	proto.RegisterType((*Pset)(nil), "rbft.Pset")
	proto.RegisterType((*Cset)(nil), "rbft.Cset")
	proto.RegisterType((*AddNode)(nil), "rbft.add_node")
	proto.RegisterType((*DelNode)(nil), "rbft.del_node")
	proto.RegisterType((*ReadyForN)(nil), "rbft.ready_for_n")
	proto.RegisterType((*AgreeUpdateN)(nil), "rbft.agree_update_n")
	proto.RegisterType((*UpdateN)(nil), "rbft.update_n")
	proto.RegisterType((*FinishUpdate)(nil), "rbft.finish_update")
	proto.RegisterEnum("rbft.ConsensusMessage_Type", ConsensusMessage_Type_name, ConsensusMessage_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x58, 0xcf, 0x73, 0xda, 0xce,
	0x15, 0xaf, 0x40, 0x60, 0x78, 0x60, 0x22, 0xaf, 0x9d, 0x98, 0x38, 0x89, 0x43, 0xd5, 0x34, 0x61,
	0xa6, 0x09, 0xce, 0xb8, 0x87, 0xfe, 0xc8, 0x4c, 0x5b, 0x82, 0x65, 0x43, 0x13, 0x0b, 0xbc, 0x90,
	0x38, 0x99, 0xe9, 0xcc, 0x8e, 0x2c, 0xd6, 0xa0, 0x31, 0x48, 0x58, 0x12, 0xb6, 0xb9, 0xf4, 0xda,
	0x99, 0x4e, 0xff, 0x8b, 0xf6, 0xd0, 0x5e, 0x3b, 0xbd, 0xf5, 0xde, 0xfe, 0x0b, 0x3d, 0xf5, 0xd4,
	0x3f, 0xa4, 0xb3, 0xbb, 0x92, 0x10, 0x98, 0x18, 0x27, 0x93, 0xef, 0x7c, 0x73, 0xd3, 0xbe, 0x7d,
	0x3f, 0x3e, 0xef, 0xed, 0xfb, 0x05, 0x50, 0x18, 0x52, 0xcf, 0x33, 0x7a, 0xd4, 0xab, 0x8c, 0x5c,
	0xc7, 0x77, 0x90, 0xec, 0x9e, 0x9c, 0xfa, 0x5b, 0xcf, 0xfa, 0x93, 0x11, 0x75, 0xcd, 0xbe, 0x61,
	0xd9, 0x3b, 0xa6, 0xe3, 0xd2, 0x1d, 0x7f, 0x32, 0xa2, 0xde, 0x8e, 0xef, 0x1a, 0xb6, 0x67, 0x98,
	0xbe, 0xe5, 0xd8, 0x82, 0x5d, 0xfd, 0x97, 0x0c, 0x6b, 0xa6, 0x63, 0x7b, 0xd4, 0xf6, 0xc6, 0x1e,
	0x09, 0x74, 0xa1, 0x97, 0x20, 0x33, 0x81, 0xa2, 0x54, 0x92, 0xca, 0x85, 0xdd, 0x87, 0x15, 0xa6,
	0xb3, 0x72, 0x8d, 0xad, 0xd2, 0x99, 0x8c, 0x28, 0xe6, 0x9c, 0xa8, 0x08, 0x2b, 0x23, 0x63, 0x32,
	0x70, 0x8c, 0x6e, 0x31, 0x51, 0x92, 0xca, 0x79, 0x1c, 0x1e, 0xd5, 0xff, 0x25, 0x41, 0x66, 0x8c,
	0xe8, 0x0e, 0xe4, 0x3a, 0xb8, 0xaa, 0xb7, 0xab, 0xb5, 0x4e, 0xa3, 0xa9, 0x2b, 0x3f, 0x60, 0x84,
	0x16, 0xd6, 0x48, 0x0b, 0x6b, 0xad, 0x2a, 0xd6, 0x14, 0x09, 0xe5, 0x60, 0x25, 0x3c, 0x24, 0x10,
	0x40, 0xba, 0xd6, 0x3c, 0x3c, 0x6c, 0x74, 0x94, 0x24, 0x2a, 0x00, 0xd4, 0xea, 0x5a, 0xed, 0x4d,
	0xab, 0xd9, 0xd0, 0x3b, 0x8a, 0xcc, 0x24, 0xdf, 0x37, 0xb4, 0x63, 0x52, 0xab, 0x57, 0xf5, 0x03,
	0x4d, 0x49, 0xa1, 0x3c, 0x64, 0x74, 0xed, 0x98, 0x30, 0xa2, 0x92, 0x46, 0x08, 0x0a, 0xfb, 0x0d,
	0xbd, 0xd1, 0xae, 0x93, 0xf7, 0x35, 0xac, 0xb5, 0xb5, 0x8e, 0xb2, 0x82, 0x36, 0x61, 0x7d, 0x1f,
	0x77, 0x6a, 0x75, 0x82, 0xb5, 0xa3, 0x77, 0x5a, 0xbb, 0x43, 0x5e, 0x57, 0x3b, 0xb5, 0xba, 0x92,
	0x41, 0x45, 0xd8, 0xc0, 0x5a, 0xe7, 0x1d, 0xd6, 0xe7, 0x6e, 0xb2, 0x4c, 0x8d, 0xae, 0x1d, 0x34,
	0x3b, 0x8d, 0x6a, 0x47, 0x13, 0xaa, 0x01, 0x3d, 0x80, 0xcd, 0x59, 0x1a, 0xc1, 0x5a, 0xbb, 0xd5,
	0xd4, 0xdb, 0x9a, 0x92, 0x43, 0x6b, 0xb0, 0x8a, 0xb5, 0x5a, 0xf3, 0xbd, 0x86, 0x3f, 0x92, 0x86,
	0xde, 0xe8, 0x28, 0x79, 0x74, 0x17, 0xd6, 0x22, 0x52, 0xc4, 0xb9, 0x8a, 0xee, 0x01, 0x8a, 0xc8,
	0xfb, 0x1a, 0x83, 0x75, 0xd4, 0xaa, 0x29, 0x05, 0x86, 0x32, 0xc6, 0xce, 0x51, 0xb1, 0x8b, 0x3b,
	0xcc, 0xc1, 0xea, 0xde, 0x1e, 0xd1, 0x9b, 0x7b, 0x9a, 0xa2, 0xb0, 0xd3, 0x9e, 0xf6, 0x56, 0x9c,
	0xd6, 0x58, 0x34, 0xb0, 0x56, 0xdd, 0xfb, 0x48, 0xf6, 0x9b, 0x98, 0xe8, 0x0a, 0x62, 0xc0, 0xab,
	0x07, 0x58, 0xd3, 0xc8, 0xbb, 0xd6, 0x1e, 0xc3, 0xa9, 0x2b, 0xeb, 0x4c, 0x24, 0x3a, 0x6d, 0x30,
	0xa4, 0x41, 0x84, 0x04, 0x51, 0xb9, 0x8b, 0x1e, 0xc1, 0x7d, 0x81, 0xe4, 0xb0, 0xd1, 0x6e, 0x37,
	0xf4, 0x03, 0x12, 0x7f, 0xac, 0x7b, 0x68, 0x1b, 0xb6, 0x02, 0x40, 0x8b, 0xee, 0x37, 0xd5, 0xbf,
	0x4b, 0xb0, 0x16, 0x4b, 0x2f, 0x72, 0x62, 0xf8, 0x66, 0x1f, 0xfd, 0x04, 0x56, 0xfc, 0x2b, 0x32,
	0xb0, 0x3c, 0xbf, 0x28, 0x95, 0x92, 0xe5, 0xdc, 0x2e, 0xaa, 0xf0, 0x4c, 0xac, 0x74, 0xa6, 0xac,
	0x38, 0xed, 0x5f, 0xbd, 0xb5, 0x3c, 0x1f, 0x3d, 0x80, 0x6c, 0xdf, 0xf0, 0xfa, 0x82, 0x3d, 0x51,
	0x4a, 0x96, 0xb3, 0x38, 0xc3, 0x08, 0xfc, 0xf2, 0x21, 0x64, 0x7d, 0x6b, 0x48, 0x3d, 0xdf, 0x18,
	0x8e, 0x8a, 0xc9, 0x92, 0x54, 0x4e, 0xe2, 0x29, 0x01, 0xdd, 0x85, 0xb4, 0x47, 0xcf, 0x89, 0xed,
	0x14, 0xe5, 0x92, 0x54, 0x96, 0x71, 0xca, 0xa3, 0xe7, 0xba, 0x83, 0xb6, 0x01, 0x5c, 0xea, 0x8d,
	0x07, 0x7e, 0xdd, 0xf0, 0xfa, 0xc5, 0x54, 0x49, 0x2a, 0x67, 0x71, 0x8c, 0xa2, 0xfe, 0x0a, 0x80,
	0x5b, 0x14, 0x60, 0x11, 0xc8, 0x11, 0xd2, 0x2c, 0xe6, 0xdf, 0xb3, 0x66, 0x13, 0x73, 0x66, 0xd5,
	0x3f, 0x48, 0xb0, 0xe1, 0x52, 0x7f, 0xec, 0xda, 0xc4, 0xa5, 0xe7, 0x63, 0xea, 0xf9, 0x81, 0xaa,
	0x17, 0x90, 0xe2, 0x1f, 0xbc, 0x82, 0x72, 0xbb, 0x9b, 0xa2, 0x82, 0xae, 0xc5, 0x07, 0x0b, 0x2e,
	0xf4, 0x43, 0xc8, 0xf3, 0x0f, 0xd2, 0xb5, 0x7a, 0x94, 0x3b, 0xcf, 0x90, 0xe6, 0x38, 0x6d, 0x8f,
	0x93, 0xd0, 0x23, 0xe6, 0xca, 0x68, 0x60, 0x99, 0x06, 0xb1, 0xba, 0x3c, 0x00, 0x32, 0xce, 0x06,
	0x94, 0x46, 0x57, 0xfd, 0x73, 0x02, 0xee, 0x9f, 0x52, 0xa6, 0x62, 0x68, 0x79, 0x9e, 0x65, 0xf7,
	0x48, 0xcc, 0x18, 0xf3, 0xec, 0xc2, 0xa2, 0x97, 0x1c, 0x8d, 0x8c, 0xf9, 0x37, 0x7a, 0x06, 0x77,
	0x3c, 0x86, 0xd9, 0x36, 0x29, 0xb1, 0xc7, 0xc3, 0x13, 0xea, 0x72, 0xb3, 0x32, 0x2e, 0x84, 0x64,
	0x9d, 0x53, 0xaf, 0x81, 0x4b, 0x5e, 0x07, 0xf7, 0xdb, 0xf8, 0xcb, 0xc9, 0xfc, 0xa1, 0x5f, 0x08,
	0x97, 0x3f, 0x89, 0xa9, 0x52, 0x0f, 0x5e, 0x56, 0xb3, 0x7d, 0x77, 0x12, 0x7b, 0xe8, 0x59, 0x47,
	0x53, 0x73, 0x8e, 0x6e, 0xbd, 0x82, 0xd5, 0x19, 0x49, 0xa4, 0x40, 0xf2, 0x8c, 0x4e, 0x02, 0xd7,
	0xd8, 0x27, 0xda, 0x80, 0xd4, 0x85, 0x31, 0x18, 0xd3, 0x20, 0x8c, 0xe2, 0xf0, 0xcb, 0xc4, 0xcf,
	0x25, 0xf5, 0x9f, 0x49, 0xd8, 0x0a, 0xde, 0xeb, 0xfb, 0x08, 0xd3, 0x9b, 0xeb, 0x61, 0xaa, 0x88,
	0x30, 0x7d, 0x1a, 0xd4, 0x27, 0xe3, 0xa4, 0x4d, 0x4b, 0x2b, 0xc5, 0x55, 0x3d, 0x5f, 0xaa, 0xaa,
	0x73, 0x35, 0x55, 0x14, 0x16, 0xdd, 0x6c, 0xb8, 0xd3, 0x5f, 0x33, 0xdc, 0x5b, 0x87, 0x90, 0x8b,
	0x99, 0x5c, 0x20, 0x5a, 0x8e, 0x8b, 0x2e, 0x6e, 0x0e, 0xb1, 0xd7, 0xfb, 0xaf, 0x04, 0xb9, 0x91,
	0x4b, 0xc9, 0xc8, 0xa5, 0x23, 0xc3, 0xa5, 0xdf, 0xf9, 0x73, 0x3d, 0x86, 0x9c, 0xe8, 0x15, 0x84,
	0x05, 0x9d, 0x77, 0x96, 0x99, 0xf6, 0x81, 0x76, 0xe2, 0xed, 0x83, 0xa7, 0x6a, 0x6e, 0x57, 0x11,
	0xaf, 0x30, 0xa5, 0x63, 0xfe, 0xe6, 0xaf, 0x79, 0x9d, 0xdf, 0x1c, 0x6c, 0xf5, 0x6f, 0x12, 0xac,
	0x7c, 0x33, 0xce, 0xdd, 0x5c, 0x87, 0xea, 0x5f, 0x25, 0x48, 0x9b, 0xce, 0x70, 0x68, 0xf9, 0xdf,
	0x3c, 0x54, 0x1d, 0xe0, 0x64, 0xe0, 0x98, 0x67, 0xc4, 0xb2, 0x4f, 0x1d, 0x6e, 0x90, 0x9f, 0x02,
	0x58, 0x02, 0x75, 0x8e, 0xd3, 0x02, 0x4c, 0x8f, 0x42, 0x01, 0x6e, 0x4f, 0xec, 0x33, 0x59, 0x4e,
	0xe1, 0x53, 0xe3, 0xf7, 0x00, 0x66, 0x9f, 0x9a, 0x67, 0x23, 0xc7, 0xb2, 0xfd, 0x45, 0x9e, 0x4a,
	0x0b, 0x3d, 0x9d, 0x45, 0x99, 0x98, 0x43, 0x89, 0x0a, 0x90, 0x08, 0x1a, 0x7b, 0x16, 0x27, 0xac,
	0x2e, 0xdb, 0xa8, 0x7a, 0xd4, 0xa6, 0x9e, 0xe5, 0x05, 0x33, 0x2d, 0x3c, 0xaa, 0xbf, 0x06, 0xf9,
	0xc2, 0x24, 0xb5, 0xdb, 0x5b, 0x16, 0xaa, 0x13, 0xa1, 0x6a, 0xb5, 0x07, 0xa9, 0x0b, 0x93, 0xb4,
	0x8e, 0x6e, 0xaf, 0xe1, 0x16, 0x03, 0x2a, 0xcc, 0x82, 0xe4, 0x34, 0x0b, 0xd4, 0x7f, 0x4b, 0x90,
	0xb9, 0x30, 0xc9, 0x89, 0xe1, 0x59, 0xde, 0xc2, 0x34, 0xc9, 0x83, 0xd4, 0x0f, 0x42, 0x21, 0xf5,
	0xd1, 0x36, 0xc8, 0xa6, 0x47, 0x59, 0x0e, 0xb0, 0x7e, 0x06, 0xa2, 0x92, 0x98, 0xab, 0x98, 0xd3,
	0xd1, 0x63, 0x90, 0x47, 0xec, 0x5e, 0xb4, 0xce, 0x5c, 0x74, 0xdf, 0x3a, 0xc2, 0xfc, 0x82, 0x31,
	0x9c, 0x33, 0x86, 0xd4, 0x02, 0x06, 0x76, 0xb1, 0xa4, 0x00, 0xe3, 0x31, 0x5f, 0x99, 0x8d, 0xb9,
	0x03, 0x39, 0x06, 0x98, 0x98, 0x7d, 0xc3, 0xee, 0x51, 0xf4, 0x84, 0xcd, 0x77, 0xc6, 0x26, 0xe6,
	0x7b, 0x21, 0xb2, 0xc4, 0xa9, 0x58, 0x5c, 0xb2, 0xe5, 0xc1, 0xb3, 0x7a, 0xb6, 0xe1, 0x8f, 0x5d,
	0x1a, 0xa6, 0x51, 0x44, 0xb8, 0x79, 0xa3, 0x51, 0xff, 0x22, 0x41, 0xc6, 0xa6, 0x97, 0x84, 0x87,
	0x69, 0x51, 0xe8, 0x9e, 0x83, 0x7c, 0xc5, 0x7c, 0x4d, 0x70, 0x5f, 0x8b, 0x02, 0x41, 0x28, 0x51,
	0xf9, 0xe0, 0xd1, 0xa0, 0xd1, 0x73, 0xae, 0x25, 0xeb, 0xc3, 0xd6, 0xcf, 0x20, 0x1b, 0x49, 0x7c,
	0xd6, 0x44, 0xfd, 0x00, 0x85, 0x53, 0xcb, 0xb6, 0xbc, 0x3e, 0xb9, 0x30, 0x31, 0xbd, 0x6e, 0x49,
	0x9a, 0x0f, 0x71, 0xe8, 0x4a, 0x22, 0xe6, 0xca, 0x3a, 0xa4, 0x06, 0xce, 0x25, 0xe9, 0x87, 0xb9,
	0x33, 0x70, 0x2e, 0xeb, 0xea, 0x31, 0xac, 0x8b, 0xe5, 0x61, 0x76, 0xb3, 0x9a, 0xcf, 0x44, 0x69,
	0xd9, 0xaa, 0x34, 0x5f, 0x68, 0xea, 0x0e, 0x14, 0x6c, 0xda, 0x73, 0x7c, 0xcb, 0xf0, 0xa9, 0x08,
	0xef, 0xcd, 0x90, 0x55, 0x1f, 0x36, 0x67, 0x05, 0x88, 0x4b, 0xbd, 0x11, 0xfb, 0x35, 0xf4, 0x25,
	0xce, 0xe6, 0x41, 0xb2, 0x03, 0x47, 0x25, 0x9b, 0x65, 0x9c, 0xeb, 0x8c, 0x7d, 0xea, 0x8a, 0x2a,
	0xcf, 0xe3, 0xf0, 0xa8, 0x56, 0x60, 0xd5, 0xa5, 0xa6, 0x73, 0x41, 0xdd, 0x09, 0xb1, 0x6c, 0x6b,
	0x59, 0x60, 0xd5, 0x3f, 0x25, 0x60, 0x2d, 0x12, 0xb8, 0x2d, 0xc0, 0x57, 0x90, 0x36, 0xfb, 0x67,
	0x23, 0xdf, 0x0b, 0xd2, 0xe8, 0x47, 0xe1, 0x0e, 0x31, 0xa7, 0xa7, 0x52, 0xe3, 0x5c, 0xc1, 0xea,
	0x20, 0x44, 0x50, 0x09, 0x44, 0xd7, 0xac, 0x53, 0xab, 0xd7, 0xf7, 0x03, 0x9f, 0xe2, 0x24, 0xf4,
	0x04, 0x56, 0x07, 0x86, 0xe7, 0xbf, 0x0e, 0x5b, 0x67, 0xd0, 0xbb, 0x67, 0x89, 0xf1, 0xaa, 0x4b,
	0xcd, 0x54, 0xdd, 0xd6, 0x2f, 0x20, 0x17, 0x33, 0xfc, 0x59, 0x89, 0xf9, 0x9b, 0x58, 0x34, 0x78,
	0x1e, 0xb5, 0x8e, 0x6a, 0xcb, 0xa2, 0x31, 0xd3, 0x8d, 0xd4, 0x7f, 0x48, 0x80, 0x62, 0x81, 0x60,
	0x5b, 0xd5, 0x2d, 0x74, 0xbc, 0x04, 0x60, 0x23, 0xdc, 0xa5, 0x64, 0x5a, 0x9c, 0x6b, 0x22, 0xaa,
	0xb1, 0xdd, 0x05, 0x67, 0x05, 0x53, 0x9b, 0xfa, 0xe8, 0x29, 0x1f, 0xfa, 0x64, 0xda, 0xf8, 0x56,
	0x23, 0x76, 0xce, 0x9a, 0x0e, 0xf8, 0x7e, 0x0c, 0x2b, 0xe6, 0xd0, 0x27, 0xd3, 0x06, 0x98, 0x0f,
	0x7f, 0x97, 0xb3, 0x29, 0x8c, 0xd3, 0xe6, 0xd0, 0x6f, 0x53, 0x5f, 0x7d, 0x06, 0x72, 0x4b, 0xf4,
	0xc2, 0x24, 0x63, 0x95, 0x16, 0xa9, 0x64, 0x37, 0xea, 0x53, 0x90, 0x6b, 0x8c, 0x71, 0x3b, 0xce,
	0x38, 0xab, 0x93, 0xf3, 0xbd, 0x82, 0x8c, 0xd1, 0xed, 0x12, 0xdb, 0xe9, 0x2e, 0x4d, 0xa7, 0xe0,
	0x81, 0xc4, 0x63, 0xb0, 0x4f, 0xf5, 0x77, 0x90, 0xe9, 0xd2, 0xc1, 0x97, 0x09, 0xf3, 0xc1, 0xcf,
	0xab, 0x41, 0x0c, 0xe2, 0x64, 0x30, 0xf8, 0x39, 0x29, 0xf8, 0xfd, 0x96, 0x73, 0xa9, 0xd1, 0x9d,
	0x90, 0x53, 0xc7, 0x25, 0xf6, 0xe7, 0xa3, 0xfb, 0xa3, 0x04, 0x05, 0xa3, 0xe7, 0x52, 0x4a, 0xc6,
	0xa3, 0x2e, 0xab, 0x6e, 0xfb, 0x96, 0x9d, 0x1d, 0x81, 0x7c, 0x3a, 0x30, 0x7a, 0x5c, 0x57, 0x06,
	0xf3, 0xef, 0x50, 0x7d, 0x72, 0x8a, 0x9f, 0xfd, 0xfc, 0x8c, 0xc0, 0x46, 0x7b, 0x4b, 0x44, 0x11,
	0xad, 0x20, 0xc5, 0x3b, 0xbf, 0x64, 0xab, 0xff, 0x91, 0x20, 0x13, 0xc1, 0x08, 0x0d, 0x48, 0x31,
	0x03, 0x4b, 0x16, 0x88, 0xeb, 0xf6, 0xb9, 0x7e, 0x39, 0xd0, 0x1f, 0x35, 0xa3, 0xd4, 0x82, 0x21,
	0x92, 0x8e, 0x0f, 0x91, 0x10, 0xc4, 0xfc, 0x10, 0xf9, 0xf2, 0x29, 0x71, 0x0c, 0xab, 0xc1, 0x94,
	0x10, 0xba, 0xbf, 0xd6, 0x90, 0x38, 0x49, 0xf3, 0x7f, 0xb1, 0x7e, 0xfa, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf6, 0x1c, 0x10, 0xc8, 0x06, 0x13, 0x00, 0x00,
}
