// Code generated by protoc-gen-go.
// source: transaction.proto
// DO NOT EDIT!

package version1_1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type InvalidTransactionRecord_ErrType int32

const (
	InvalidTransactionRecord_OUTOFBALANCE           InvalidTransactionRecord_ErrType = 0
	InvalidTransactionRecord_SIGFAILED              InvalidTransactionRecord_ErrType = 1
	InvalidTransactionRecord_INVOKE_CONTRACT_FAILED InvalidTransactionRecord_ErrType = 2
	InvalidTransactionRecord_DEPLOY_CONTRACT_FAILED InvalidTransactionRecord_ErrType = 3
	InvalidTransactionRecord_INVALID_PERMISSION     InvalidTransactionRecord_ErrType = 4
)

var InvalidTransactionRecord_ErrType_name = map[int32]string{
	0: "OUTOFBALANCE",
	1: "SIGFAILED",
	2: "INVOKE_CONTRACT_FAILED",
	3: "DEPLOY_CONTRACT_FAILED",
	4: "INVALID_PERMISSION",
}
var InvalidTransactionRecord_ErrType_value = map[string]int32{
	"OUTOFBALANCE":           0,
	"SIGFAILED":              1,
	"INVOKE_CONTRACT_FAILED": 2,
	"DEPLOY_CONTRACT_FAILED": 3,
	"INVALID_PERMISSION":     4,
}

func (x InvalidTransactionRecord_ErrType) String() string {
	return proto.EnumName(InvalidTransactionRecord_ErrType_name, int32(x))
}
func (InvalidTransactionRecord_ErrType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{1, 0}
}

type Transaction struct {
	Version         []byte `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	From            []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To              []byte `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value           []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp       int64  `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Signature       []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Id              uint64 `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	TransactionHash []byte `protobuf:"bytes,8,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	Nonce           int64  `protobuf:"varint,9,opt,name=nonce" json:"nonce,omitempty"`
	Puk             []byte `protobuf:"bytes,10,opt,name=puk,proto3" json:"puk,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Transaction) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetPuk() []byte {
	if m != nil {
		return m.Puk
	}
	return nil
}

type InvalidTransactionRecord struct {
	Tx      *Transaction                     `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	ErrType InvalidTransactionRecord_ErrType `protobuf:"varint,2,opt,name=errType,enum=version1_1.InvalidTransactionRecord_ErrType" json:"errType,omitempty"`
	ErrMsg  []byte                           `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (m *InvalidTransactionRecord) Reset()                    { *m = InvalidTransactionRecord{} }
func (m *InvalidTransactionRecord) String() string            { return proto.CompactTextString(m) }
func (*InvalidTransactionRecord) ProtoMessage()               {}
func (*InvalidTransactionRecord) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *InvalidTransactionRecord) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *InvalidTransactionRecord) GetErrType() InvalidTransactionRecord_ErrType {
	if m != nil {
		return m.ErrType
	}
	return InvalidTransactionRecord_OUTOFBALANCE
}

func (m *InvalidTransactionRecord) GetErrMsg() []byte {
	if m != nil {
		return m.ErrMsg
	}
	return nil
}

type InvalidTransactionRecords struct {
	Records []*InvalidTransactionRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
}

func (m *InvalidTransactionRecords) Reset()                    { *m = InvalidTransactionRecords{} }
func (m *InvalidTransactionRecords) String() string            { return proto.CompactTextString(m) }
func (*InvalidTransactionRecords) ProtoMessage()               {}
func (*InvalidTransactionRecords) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *InvalidTransactionRecords) GetRecords() []*InvalidTransactionRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type TransactionMeta struct {
	BlockIndex uint64 `protobuf:"varint,1,opt,name=BlockIndex" json:"BlockIndex,omitempty"`
	Index      int64  `protobuf:"varint,2,opt,name=Index" json:"Index,omitempty"`
}

func (m *TransactionMeta) Reset()                    { *m = TransactionMeta{} }
func (m *TransactionMeta) String() string            { return proto.CompactTextString(m) }
func (*TransactionMeta) ProtoMessage()               {}
func (*TransactionMeta) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *TransactionMeta) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *TransactionMeta) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "version1_1.Transaction")
	proto.RegisterType((*InvalidTransactionRecord)(nil), "version1_1.InvalidTransactionRecord")
	proto.RegisterType((*InvalidTransactionRecords)(nil), "version1_1.InvalidTransactionRecords")
	proto.RegisterType((*TransactionMeta)(nil), "version1_1.TransactionMeta")
	proto.RegisterEnum("version1_1.InvalidTransactionRecord_ErrType", InvalidTransactionRecord_ErrType_name, InvalidTransactionRecord_ErrType_value)
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x5d, 0x8b, 0xd3, 0x4c,
	0x14, 0x7e, 0xf3, 0xb1, 0xcd, 0xdb, 0xd3, 0x75, 0x37, 0x1e, 0xa4, 0x8e, 0x22, 0x52, 0x82, 0x60,
	0x2e, 0xa4, 0xb0, 0xf5, 0x5e, 0xc8, 0xb6, 0xe9, 0x3a, 0xd8, 0x26, 0xcb, 0x34, 0x2e, 0x88, 0x17,
	0x25, 0x36, 0xe3, 0x1a, 0xb6, 0xcd, 0x94, 0xc9, 0xb4, 0xac, 0xfe, 0x19, 0x7f, 0xaa, 0x92, 0x49,
	0x4a, 0x83, 0xb2, 0xe0, 0xdd, 0x79, 0xbe, 0x32, 0x39, 0xcf, 0x0c, 0x3c, 0x56, 0x32, 0x2d, 0xca,
	0x74, 0xa5, 0x72, 0x51, 0x0c, 0xb7, 0x52, 0x28, 0x81, 0xb0, 0xe7, 0xb2, 0xcc, 0x45, 0x71, 0xb1,
	0xbc, 0xf0, 0x7e, 0x19, 0xd0, 0x4b, 0x8e, 0x0e, 0x24, 0xe0, 0x34, 0x2a, 0x31, 0x06, 0x86, 0x7f,
	0xca, 0x0e, 0x10, 0x11, 0xec, 0xaf, 0x52, 0x6c, 0x88, 0xa9, 0x69, 0x3d, 0xe3, 0x19, 0x98, 0x4a,
	0x10, 0x4b, 0x33, 0xa6, 0x12, 0xf8, 0x04, 0x4e, 0xf6, 0xe9, 0x7a, 0xc7, 0x89, 0xad, 0xa9, 0x1a,
	0xe0, 0x0b, 0xe8, 0xaa, 0x7c, 0xc3, 0x4b, 0x95, 0x6e, 0xb6, 0xe4, 0x64, 0x60, 0xf8, 0x16, 0x3b,
	0x12, 0x95, 0x5a, 0xe6, 0xb7, 0x45, 0xaa, 0x76, 0x92, 0x93, 0x8e, 0xce, 0x1d, 0x89, 0xea, 0x84,
	0x3c, 0x23, 0xce, 0xc0, 0xf0, 0x6d, 0x66, 0xe6, 0x19, 0xfa, 0x70, 0xde, 0x5a, 0xe8, 0x7d, 0x5a,
	0x7e, 0x23, 0xff, 0xeb, 0xcc, 0x9f, 0x74, 0xf5, 0x2f, 0x85, 0x28, 0x56, 0x9c, 0x74, 0xf5, 0x89,
	0x35, 0x40, 0x17, 0xac, 0xed, 0xee, 0x8e, 0x80, 0xce, 0x54, 0xa3, 0xf7, 0xd3, 0x04, 0x42, 0x8b,
	0x7d, 0xba, 0xce, 0xb3, 0x56, 0x11, 0x8c, 0xaf, 0x84, 0xcc, 0xf0, 0x35, 0x98, 0xea, 0x5e, 0x37,
	0xd1, 0x1b, 0x3d, 0x1d, 0x1e, 0x7b, 0x1b, 0xb6, 0xad, 0xa6, 0xba, 0xc7, 0x29, 0x38, 0x5c, 0xca,
	0xe4, 0xfb, 0x96, 0xeb, 0x82, 0xce, 0x46, 0x6f, 0xda, 0xee, 0x87, 0xbe, 0x3f, 0x0c, 0xeb, 0x0c,
	0x3b, 0x84, 0xb1, 0x0f, 0x1d, 0x2e, 0xe5, 0xbc, 0xbc, 0x6d, 0x5a, 0x6d, 0x90, 0xf7, 0x03, 0x9c,
	0xc6, 0x8b, 0x2e, 0x9c, 0xc6, 0x1f, 0x93, 0x78, 0x7a, 0x19, 0xcc, 0x82, 0x68, 0x1c, 0xba, 0xff,
	0xe1, 0x23, 0xe8, 0x2e, 0xe8, 0xd5, 0x34, 0xa0, 0xb3, 0x70, 0xe2, 0x1a, 0xf8, 0x1c, 0xfa, 0x34,
	0xba, 0x89, 0x3f, 0x84, 0xcb, 0x71, 0x1c, 0x25, 0x2c, 0x18, 0x27, 0xcb, 0x46, 0x33, 0x2b, 0x6d,
	0x12, 0x5e, 0xcf, 0xe2, 0x4f, 0x7f, 0x69, 0x16, 0xf6, 0x01, 0x69, 0x74, 0x13, 0xcc, 0xe8, 0x64,
	0x79, 0x1d, 0xb2, 0x39, 0x5d, 0x2c, 0x68, 0x1c, 0xb9, 0xb6, 0xf7, 0x19, 0x9e, 0x3d, 0xb4, 0x40,
	0x89, 0xef, 0xc0, 0x91, 0xf5, 0x48, 0x8c, 0x81, 0xe5, 0xf7, 0x46, 0xaf, 0xfe, 0x65, 0x71, 0x76,
	0x08, 0x79, 0x57, 0x70, 0xde, 0x52, 0xe7, 0x5c, 0xa5, 0xf8, 0x12, 0xe0, 0x72, 0x2d, 0x56, 0x77,
	0xb4, 0xc8, 0x78, 0x5d, 0xbe, 0xcd, 0x5a, 0x4c, 0x75, 0xb3, 0xb5, 0x64, 0xd6, 0x37, 0xab, 0xc1,
	0x97, 0x8e, 0x7e, 0xdc, 0x6f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x21, 0xa5, 0x5b, 0xf1,
	0x02, 0x00, 0x00,
}
