###########################################################
#  _   _                        ____ _           _        #
# | | | |_   _ _ __   ___ _ __ / ___| |__   __ _(_)_ __   #
# | |_| | | | | '_ \ / _ \ '__| |   | '_ \ / _\` | | '_ \ #
# |  _  | |_| | |_) |  __/ |  | |___| | | | (_| | | | | | #
# |_| |_|\__, | .__/ \___|_|   \____|_| |_|\__,_|_|_| |_| #
#        |___/|_|                                         #
###########################################################

global:

    ##########################
    # data storage config #
    ##########################

    account:
        keystoredir: "namespaces/global/config/keystore"
        keynodesdir: "namespaces/global/config/keynodes"

    dbConfig: "namespaces/global/config/db.yaml"

    configs:
        caconfig: "namespaces/global/config/caconfig.toml"
        peers: "namespaces/global/config/local_peerconfig.json"
        genesis: "namespaces/global/config/genesis.json"
        static_peers: "namespaces/global/config/static_peers.json"

        ratelimit:
                enable   : true
                txRatePeak : 100
                txFillRate: 0.5ms
                contractRatePeak : 100
                contractFillRate: 0.5ms

        hmpublickey:
            "N": "14315727801779002117"
            Nsquare: "204940062494628260128356353732290481689"
            G: "90976693534933209671098397317966944738726332459523400324197777885595356310417"
    security:
        enabletls: false
        enablesymmetrical: false
    connection:
        retryTimeLimit: 6
        retryTimeout: 10s
        recoveryTimeLimit: 5
        recoveryTimeout: 5s
        keepAliveTimeLimit: 3
        keepAliveInterval: 3s
    ######################################################
    # config log's level by module                       #
    #                                                    #
    # CRITICAL ERROR WARNING NOTICE INFO DEBUG           #
    # high <------------- log level -------> low         #
    #                                                    #
    ######################################################
    logs:
        # dump the log file or not
        dumpfile: true
        newLogFileInterval: 10s  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
                                # such as "300ms", "2h45m".

        logsdir: "./namespaces/global/data/logs"
        # default loglevel for all modules which can be override by module level log setting
        loglevel: "NOTICE"
        file_format: "[%{module}][%{level:.5s}] %{time:15:04:05.000} %{shortfile} %{message}"
        console_format: "%{color}[%{module}][%{level:.5s}] %{time:15:04:05.000} %{shortfile} %{message} %{color:reset}"

        module:
            #set log level by module
            p2p: "NOTICE"
            consensus: "NOTICE"
            core: "NOTICE"
            hyperdb: "NOTICE"
            common/hyper_logger: "NOTICE"
            hyperstate: "DEBUG"
            api: "DEBUG"

    ######################################################
    # configs related to the executor                    #
    ######################################################
    executor:
        sync_chain:
            sync_batch_size: 500
            sync_resend_interval: 15m
        sync_replica:
            interval : 500s
            enable   : false
        buckettree:
            global:
                globalDataNodeCacheSize: 10000
                globalDataNodeCacheLength: 20
            state:
                size: 1000003
                levelGroup: 5
                bucketCacheSize: 100000
                dataNodeCacheSize: 100000
            storage:
                size: 1000003
                levelGroup: 5
                bucketCacheSize: 100000
                dataNodeCacheSize: 100000
    ######################################################
    # configs related to the consensus                   #
    #                                                    #
    # 1. choose which consensus algorithm to use         #
    # 2. define the algorithm related configurations     #
    #                                                    #
    ######################################################
    consensus:
           algo: "PBFT"
           algo_config_path: "namespaces/global/config/pbft.yaml"

