self:
  "N": 4
  id: 1
  hostname: node1
  # type 0 creator type 1 add new
  type: 1
  introducer: node1
nodes:
  -
    id: 1
    hostname: node1
  -
    id: 2
    hostname: node2
  -
    id: 3
    hostname: node3
  -
    id: 4
    hostname: node4