global:
  configs:
    peers: config/peerconfig.json
  logs:
    console_format: '%{color}[%{module}][%{level:.5s}] %{time:15:04:05.000} %{shortfile}
      %{message} %{color:reset}'
    dumpfile: true
    file_format: '[%{module}][%{level:.5s}] %{time:15:04:05.000} %{shortfile} %{message}'
    loglevel: NOTICE
    logsdir: ./logs
    module:
      consensus: NOTICE
      core: NOTICE
      eventhub: NOTICE
      hyperdb: NOTICE
      p2p: NOTICE
    newlogfileinterval: 24h
  namespace:
    start:
      global: true
      ns1: false
      ns2: false
  nsconfigrootpath: ./namespaces
