// Code generated by protoc-gen-go.
// source: contract.proto
// DO NOT EDIT!

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	contract.proto

It has these top-level messages:
	Request
	Response
	RequestContext
	Key
	BatchKey
	BathValue
	BatchKV
	Range
	Value
	KeyValue
	LedgerContext
*/
package contract

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Context *RequestContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Method  string          `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Args    [][]byte        `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetContext() *RequestContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type Response struct {
	Ok       bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Result   []byte `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	CodeHash string `protobuf:"bytes,3,opt,name=codeHash" json:"codeHash,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RequestContext struct {
	Txid      string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Cid       string `protobuf:"bytes,3,opt,name=cid" json:"cid,omitempty"`
}

func (m *RequestContext) Reset()                    { *m = RequestContext{} }
func (m *RequestContext) String() string            { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()               {}
func (*RequestContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Key struct {
	Context *LedgerContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	K       []byte         `protobuf:"bytes,2,opt,name=k,proto3" json:"k,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Key) GetContext() *LedgerContext {
	if m != nil {
		return m.Context
	}
	return nil
}

// BatchKey used to fetch data by batch
type BatchKey struct {
	Context *LedgerContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	K       [][]byte       `protobuf:"bytes,2,rep,name=k,proto3" json:"k,omitempty"`
}

func (m *BatchKey) Reset()                    { *m = BatchKey{} }
func (m *BatchKey) String() string            { return proto.CompactTextString(m) }
func (*BatchKey) ProtoMessage()               {}
func (*BatchKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BatchKey) GetContext() *LedgerContext {
	if m != nil {
		return m.Context
	}
	return nil
}

// BathKV bach result
type BathValue struct {
	Id      string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	HasMore bool     `protobuf:"varint,2,opt,name=hasMore" json:"hasMore,omitempty"`
	V       [][]byte `protobuf:"bytes,3,rep,name=v,proto3" json:"v,omitempty"`
}

func (m *BathValue) Reset()                    { *m = BathValue{} }
func (m *BathValue) String() string            { return proto.CompactTextString(m) }
func (*BathValue) ProtoMessage()               {}
func (*BathValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type BatchKV struct {
	Context *LedgerContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Kv      []*KeyValue    `protobuf:"bytes,2,rep,name=kv" json:"kv,omitempty"`
}

func (m *BatchKV) Reset()                    { *m = BatchKV{} }
func (m *BatchKV) String() string            { return proto.CompactTextString(m) }
func (*BatchKV) ProtoMessage()               {}
func (*BatchKV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BatchKV) GetContext() *LedgerContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *BatchKV) GetKv() []*KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

// Range specifiy query range
type Range struct {
	Context *LedgerContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Start   []byte         `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End     []byte         `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *Range) Reset()                    { *m = Range{} }
func (m *Range) String() string            { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()               {}
func (*Range) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Range) GetContext() *LedgerContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type Value struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	V  []byte `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type KeyValue struct {
	Context *LedgerContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	K       []byte         `protobuf:"bytes,2,opt,name=k,proto3" json:"k,omitempty"`
	V       []byte         `protobuf:"bytes,3,opt,name=v,proto3" json:"v,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *KeyValue) GetContext() *LedgerContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type LedgerContext struct {
	Txid      string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Cid       string `protobuf:"bytes,3,opt,name=cid" json:"cid,omitempty"`
}

func (m *LedgerContext) Reset()                    { *m = LedgerContext{} }
func (m *LedgerContext) String() string            { return proto.CompactTextString(m) }
func (*LedgerContext) ProtoMessage()               {}
func (*LedgerContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*RequestContext)(nil), "RequestContext")
	proto.RegisterType((*Key)(nil), "Key")
	proto.RegisterType((*BatchKey)(nil), "BatchKey")
	proto.RegisterType((*BathValue)(nil), "BathValue")
	proto.RegisterType((*BatchKV)(nil), "BatchKV")
	proto.RegisterType((*Range)(nil), "Range")
	proto.RegisterType((*Value)(nil), "Value")
	proto.RegisterType((*KeyValue)(nil), "KeyValue")
	proto.RegisterType((*LedgerContext)(nil), "LedgerContext")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.

// Client API for Contract service

type ContractClient interface {
	// used tp execute contract method remotely
	Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// used to detect the health state of contract
	HeartBeat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type contractClient struct {
	cc *grpc.ClientConn
}

func NewContractClient(cc *grpc.ClientConn) ContractClient {
	return &contractClient{cc}
}

func (c *contractClient) Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Contract/Execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) HeartBeat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Contract/HeartBeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contract service

type ContractServer interface {
	// used tp execute contract method remotely
	Execute(context.Context, *Request) (*Response, error)
	// used to detect the health state of contract
	HeartBeat(context.Context, *Request) (*Response, error)
}

func RegisterContractServer(s *grpc.Server, srv ContractServer) {
	s.RegisterService(&_Contract_serviceDesc, srv)
}

func _Contract_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Contract/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).Execute(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Contract/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).HeartBeat(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contract_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Contract",
	HandlerType: (*ContractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Contract_Execute_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _Contract_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for Ledger service

type LedgerClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	Put(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error)
	BatchRead(ctx context.Context, in *BatchKey, opts ...grpc.CallOption) (*BathValue, error)
	BatchWrite(ctx context.Context, in *BatchKV, opts ...grpc.CallOption) (*Response, error)
	RangeQuery(ctx context.Context, in *Range, opts ...grpc.CallOption) (Ledger_RangeQueryClient, error)
}

type ledgerClient struct {
	cc *grpc.ClientConn
}

func NewLedgerClient(cc *grpc.ClientConn) LedgerClient {
	return &ledgerClient{cc}
}

func (c *ledgerClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := grpc.Invoke(ctx, "/Ledger/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) Put(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Ledger/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Ledger/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) BatchRead(ctx context.Context, in *BatchKey, opts ...grpc.CallOption) (*BathValue, error) {
	out := new(BathValue)
	err := grpc.Invoke(ctx, "/Ledger/BatchRead", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) BatchWrite(ctx context.Context, in *BatchKV, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Ledger/BatchWrite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerClient) RangeQuery(ctx context.Context, in *Range, opts ...grpc.CallOption) (Ledger_RangeQueryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ledger_serviceDesc.Streams[0], c.cc, "/Ledger/RangeQuery", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerRangeQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ledger_RangeQueryClient interface {
	Recv() (*BathValue, error)
	grpc.ClientStream
}

type ledgerRangeQueryClient struct {
	grpc.ClientStream
}

func (x *ledgerRangeQueryClient) Recv() (*BathValue, error) {
	m := new(BathValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ledger service

type LedgerServer interface {
	Get(context.Context, *Key) (*Value, error)
	Put(context.Context, *KeyValue) (*Response, error)
	Delete(context.Context, *Key) (*Response, error)
	BatchRead(context.Context, *BatchKey) (*BathValue, error)
	BatchWrite(context.Context, *BatchKV) (*Response, error)
	RangeQuery(*Range, Ledger_RangeQueryServer) error
}

func RegisterLedgerServer(s *grpc.Server, srv LedgerServer) {
	s.RegisterService(&_Ledger_serviceDesc, srv)
}

func _Ledger_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ledger/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ledger/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).Put(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ledger/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).Delete(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_BatchRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).BatchRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ledger/BatchRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).BatchRead(ctx, req.(*BatchKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_BatchWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchKV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).BatchWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ledger/BatchWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).BatchWrite(ctx, req.(*BatchKV))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ledger_RangeQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Range)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServer).RangeQuery(m, &ledgerRangeQueryServer{stream})
}

type Ledger_RangeQueryServer interface {
	Send(*BathValue) error
	grpc.ServerStream
}

type ledgerRangeQueryServer struct {
	grpc.ServerStream
}

func (x *ledgerRangeQueryServer) Send(m *BathValue) error {
	return x.ServerStream.SendMsg(m)
}

var _Ledger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ledger",
	HandlerType: (*LedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Ledger_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Ledger_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Ledger_Delete_Handler,
		},
		{
			MethodName: "BatchRead",
			Handler:    _Ledger_BatchRead_Handler,
		},
		{
			MethodName: "BatchWrite",
			Handler:    _Ledger_BatchWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RangeQuery",
			Handler:       _Ledger_RangeQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x8d, 0xed, 0xc6, 0xb1, 0xa7, 0x69, 0xbe, 0x4f, 0xa3, 0x82, 0x42, 0x00, 0x29, 0x5a, 0x40,
	0x84, 0x8b, 0x85, 0xc2, 0x99, 0x8b, 0x03, 0xa2, 0x52, 0xa1, 0x0a, 0x0b, 0x2a, 0xe2, 0xc6, 0x62,
	0x8f, 0xe2, 0xc8, 0xa9, 0x1d, 0x76, 0xd7, 0x51, 0xf2, 0x1f, 0xf9, 0x51, 0xc8, 0xeb, 0x75, 0xaa,
	0x14, 0x38, 0xb4, 0xe2, 0x36, 0x6f, 0xc7, 0xfb, 0xf6, 0xcd, 0x9b, 0x19, 0xc3, 0x20, 0x29, 0x0b,
	0x2d, 0x45, 0xa2, 0xa3, 0xb5, 0x2c, 0x75, 0xc9, 0xbe, 0x41, 0x8f, 0xd3, 0x8f, 0x8a, 0x94, 0xc6,
	0x17, 0xd0, 0xab, 0x93, 0xb4, 0xd5, 0x43, 0x67, 0xec, 0x4c, 0x8e, 0xa7, 0xff, 0x45, 0x36, 0x35,
	0x6b, 0x8e, 0x79, 0x9b, 0xc7, 0xfb, 0xe0, 0x5f, 0x91, 0xce, 0xca, 0x74, 0xe8, 0x8e, 0x9d, 0x49,
	0xc8, 0x2d, 0x42, 0x84, 0x23, 0x21, 0x17, 0x6a, 0xe8, 0x8d, 0xbd, 0x49, 0x9f, 0x9b, 0x98, 0x5d,
	0x40, 0xc0, 0x49, 0xad, 0xcb, 0x42, 0x11, 0x0e, 0xc0, 0x2d, 0x73, 0xc3, 0x1e, 0x70, 0xb7, 0xcc,
	0x6b, 0x1e, 0x49, 0xaa, 0x5a, 0x69, 0xc3, 0xd3, 0xe7, 0x16, 0xe1, 0x08, 0x82, 0xa4, 0x4c, 0xe9,
	0x4c, 0xa8, 0x6c, 0xe8, 0x99, 0x17, 0xf6, 0x98, 0x7d, 0x86, 0xc1, 0xa1, 0xac, 0xfa, 0x55, 0xbd,
	0x5d, 0xa6, 0x86, 0x37, 0xe4, 0x26, 0xc6, 0x47, 0x10, 0x16, 0xe2, 0x8a, 0xd4, 0x5a, 0x24, 0x64,
	0x45, 0x5e, 0x1f, 0xe0, 0xff, 0xe0, 0x25, 0xcb, 0xd4, 0x52, 0xd7, 0x21, 0x7b, 0x0d, 0xde, 0x39,
	0xed, 0x70, 0x72, 0xd3, 0x83, 0x41, 0xf4, 0x9e, 0xd2, 0x05, 0xc9, 0xdf, 0x2c, 0xe8, 0x83, 0x93,
	0x5b, 0xd5, 0x4e, 0xce, 0x62, 0x08, 0x62, 0xa1, 0x93, 0xec, 0x4e, 0x1c, 0x5e, 0xc3, 0x31, 0x83,
	0x30, 0x16, 0x3a, 0xbb, 0x14, 0xab, 0xca, 0x38, 0xb5, 0xaf, 0xc8, 0x5d, 0xa6, 0x38, 0x84, 0x5e,
	0x26, 0xd4, 0x87, 0x52, 0x36, 0xd5, 0x04, 0xbc, 0x85, 0x35, 0xc9, 0xc6, 0x1a, 0xee, 0x6c, 0xd8,
	0x05, 0xf4, 0x1a, 0x21, 0x97, 0xb7, 0xd0, 0xf1, 0x00, 0xdc, 0x7c, 0x63, 0x84, 0x1c, 0x4f, 0xc3,
	0xe8, 0x9c, 0x76, 0x46, 0x03, 0x77, 0xf3, 0x0d, 0xfb, 0x0a, 0x5d, 0x2e, 0x8a, 0x05, 0xdd, 0x82,
	0xed, 0x14, 0xba, 0x4a, 0x0b, 0xd9, 0xf6, 0xb4, 0x01, 0xb5, 0xe5, 0x54, 0x34, 0x96, 0xf7, 0x79,
	0x1d, 0xb2, 0x67, 0xd0, 0xfd, 0x73, 0xad, 0xa6, 0x22, 0x6b, 0xed, 0x86, 0xcd, 0x21, 0x68, 0x15,
	0xdd, 0xb5, 0x3d, 0xad, 0x47, 0x96, 0xf1, 0x13, 0x9c, 0x1c, 0xdc, 0xfa, 0x17, 0x03, 0x34, 0x9d,
	0x43, 0x30, 0xb3, 0xab, 0x85, 0x63, 0xe8, 0xbd, 0xdd, 0x52, 0x52, 0x69, 0xc2, 0xa0, 0xdd, 0xa1,
	0x51, 0x18, 0xb5, 0x6b, 0xc0, 0x3a, 0xc8, 0x20, 0x3c, 0x23, 0x21, 0x75, 0x4c, 0x42, 0xff, 0xe5,
	0x9b, 0xe9, 0x4f, 0x07, 0xfc, 0x46, 0x27, 0xde, 0x03, 0xef, 0x1d, 0x69, 0x3c, 0xaa, 0x7b, 0x33,
	0xf2, 0x23, 0x63, 0x06, 0xeb, 0xe0, 0x63, 0xf0, 0xe6, 0x95, 0xc6, 0xeb, 0x96, 0x1d, 0x3e, 0xf2,
	0x10, 0xfc, 0x37, 0xb4, 0x22, 0x4d, 0xf6, 0xe2, 0x41, 0xf2, 0xa9, 0x99, 0xb6, 0x24, 0xe3, 0x24,
	0x52, 0x0c, 0xa3, 0x76, 0x7a, 0x47, 0x10, 0xed, 0x87, 0x90, 0x75, 0xf0, 0x09, 0x80, 0xc9, 0x7c,
	0x91, 0x4b, 0x53, 0x8c, 0x9d, 0xad, 0x9b, 0x54, 0x60, 0x66, 0xe4, 0x63, 0x45, 0x72, 0x87, 0x7e,
	0x64, 0xc0, 0x21, 0xd1, 0x4b, 0x27, 0x7e, 0x0e, 0xa7, 0x49, 0x11, 0x65, 0xbb, 0x35, 0xc9, 0x24,
	0x13, 0xcb, 0xa2, 0xf9, 0x01, 0xa9, 0xf8, 0xa4, 0xb5, 0x6d, 0x5e, 0xe3, 0x79, 0xe7, 0xbb, 0x6f,
	0x12, 0xaf, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x6a, 0x87, 0xc2, 0xab, 0x04, 0x00, 0x00,
}
