// Code generated by protoc-gen-go.
// source: consensus.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	consensus.proto

It has these top-level messages:
	Message
	ExeMessage
	UpdateStateMessage
	StateUpdatedMessage
	BlockchainInfo
	NullRequestMessage
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_TRANSACTION   Message_Type = 0
	Message_CONSENSUS     Message_Type = 1
	Message_STATE_UPDATED Message_Type = 2
	Message_NULL_REQUEST  Message_Type = 3
)

var Message_Type_name = map[int32]string{
	0: "TRANSACTION",
	1: "CONSENSUS",
	2: "STATE_UPDATED",
	3: "NULL_REQUEST",
}
var Message_Type_value = map[string]int32{
	"TRANSACTION":   0,
	"CONSENSUS":     1,
	"STATE_UPDATED": 2,
	"NULL_REQUEST":  3,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// This message type is used between consensus and outside
type Message struct {
	Type      Message_Type `protobuf:"varint,1,opt,name=type,enum=protos.Message_Type" json:"type,omitempty"`
	Timestamp int64        `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   []byte       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Id        uint64       `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ExeMessage struct {
	Batch     []*Message `protobuf:"bytes,1,rep,name=batch" json:"batch,omitempty"`
	Timestamp int64      `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	No        uint64     `protobuf:"varint,3,opt,name=no" json:"no,omitempty"`
}

func (m *ExeMessage) Reset()                    { *m = ExeMessage{} }
func (m *ExeMessage) String() string            { return proto.CompactTextString(m) }
func (*ExeMessage) ProtoMessage()               {}
func (*ExeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExeMessage) GetBatch() []*Message {
	if m != nil {
		return m.Batch
	}
	return nil
}

type UpdateStateMessage struct {
	Id       uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SeqNo    uint64   `protobuf:"varint,2,opt,name=seqNo" json:"seqNo,omitempty"`
	TargetId []byte   `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Replicas []uint64 `protobuf:"varint,4,rep,packed,name=replicas" json:"replicas,omitempty"`
}

func (m *UpdateStateMessage) Reset()                    { *m = UpdateStateMessage{} }
func (m *UpdateStateMessage) String() string            { return proto.CompactTextString(m) }
func (*UpdateStateMessage) ProtoMessage()               {}
func (*UpdateStateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StateUpdatedMessage struct {
	SeqNo uint64 `protobuf:"varint,1,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *StateUpdatedMessage) Reset()                    { *m = StateUpdatedMessage{} }
func (m *StateUpdatedMessage) String() string            { return proto.CompactTextString(m) }
func (*StateUpdatedMessage) ProtoMessage()               {}
func (*StateUpdatedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// BlockchainInfo
type BlockchainInfo struct {
	Height            uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	CurrentBlockHash  []byte `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash []byte `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
}

func (m *BlockchainInfo) Reset()                    { *m = BlockchainInfo{} }
func (m *BlockchainInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockchainInfo) ProtoMessage()               {}
func (*BlockchainInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type NullRequestMessage struct {
	SeqNo uint64 `protobuf:"varint,1,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *NullRequestMessage) Reset()                    { *m = NullRequestMessage{} }
func (m *NullRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*NullRequestMessage) ProtoMessage()               {}
func (*NullRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*ExeMessage)(nil), "protos.ExeMessage")
	proto.RegisterType((*UpdateStateMessage)(nil), "protos.UpdateStateMessage")
	proto.RegisterType((*StateUpdatedMessage)(nil), "protos.StateUpdatedMessage")
	proto.RegisterType((*BlockchainInfo)(nil), "protos.BlockchainInfo")
	proto.RegisterType((*NullRequestMessage)(nil), "protos.NullRequestMessage")
	proto.RegisterEnum("protos.Message_Type", Message_Type_name, Message_Type_value)
}

func init() { proto.RegisterFile("consensus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0x5d, 0xaf, 0xd2, 0x40,
	0x10, 0xb5, 0xb4, 0xf7, 0x5e, 0xef, 0xf0, 0x55, 0x46, 0x62, 0x1a, 0xe3, 0x83, 0x69, 0x62, 0x42,
	0xd0, 0xf0, 0x80, 0xbf, 0x00, 0xa1, 0x89, 0x44, 0x2c, 0xba, 0x6d, 0x9f, 0xc9, 0xd2, 0xae, 0xb4,
	0xb1, 0x74, 0x4b, 0x77, 0x6b, 0xe4, 0xd5, 0x5f, 0xe7, 0xcf, 0x72, 0x69, 0x29, 0x18, 0x49, 0xf4,
	0xa5, 0xdb, 0x33, 0xe7, 0xec, 0x9c, 0x39, 0x93, 0x85, 0x7e, 0xc8, 0x33, 0xc1, 0x32, 0x51, 0x8a,
	0x49, 0x5e, 0x70, 0xc9, 0xf1, 0xbe, 0x3a, 0x84, 0xfd, 0x4b, 0x83, 0x87, 0x4f, 0x4c, 0x08, 0xba,
	0x63, 0x38, 0x02, 0x43, 0x1e, 0x73, 0x66, 0x69, 0xaf, 0xb4, 0x51, 0x6f, 0x3a, 0xac, 0x95, 0x62,
	0x72, 0xa6, 0x27, 0xbe, 0xe2, 0x48, 0xa5, 0xc0, 0x97, 0xf0, 0x28, 0x93, 0x3d, 0x13, 0x92, 0xee,
	0x73, 0xab, 0xa5, 0xe4, 0x3a, 0xb9, 0x16, 0xd0, 0x82, 0x87, 0x9c, 0x1e, 0x53, 0x4e, 0x23, 0x4b,
	0x57, 0x5c, 0x87, 0x34, 0x10, 0x7b, 0xd0, 0x4a, 0x22, 0xcb, 0x50, 0x45, 0x83, 0xa8, 0x3f, 0xfb,
	0x23, 0x18, 0xa7, 0xae, 0xd8, 0x87, 0xb6, 0x4f, 0x66, 0xae, 0x37, 0x9b, 0xfb, 0xcb, 0xb5, 0x6b,
	0x3e, 0xc1, 0x2e, 0x3c, 0xce, 0xd7, 0xae, 0xe7, 0xb8, 0x5e, 0xe0, 0x99, 0x1a, 0x0e, 0xa0, 0xeb,
	0xf9, 0x33, 0xdf, 0xd9, 0x04, 0x9f, 0x17, 0xea, 0x58, 0x98, 0x2d, 0x34, 0xa1, 0xe3, 0x06, 0xab,
	0xd5, 0x86, 0x38, 0x5f, 0x02, 0xc7, 0xf3, 0x4d, 0xdd, 0xa6, 0x00, 0xce, 0x0f, 0xd6, 0x84, 0x79,
	0x0d, 0x77, 0x5b, 0x2a, 0xc3, 0x58, 0xa5, 0xd1, 0x47, 0xed, 0x69, 0xff, 0xaf, 0x34, 0xa4, 0x66,
	0xff, 0x93, 0x44, 0xcd, 0x9b, 0xf1, 0x2a, 0x84, 0x9a, 0x37, 0xe3, 0x76, 0x01, 0x18, 0xe4, 0x11,
	0x95, 0xcc, 0x93, 0xea, 0xd3, 0x58, 0xd5, 0xa9, 0xb4, 0x26, 0x15, 0x0e, 0xe1, 0x4e, 0xb0, 0x83,
	0xcb, 0xab, 0x7e, 0x06, 0xa9, 0x01, 0xbe, 0x80, 0xa7, 0x92, 0x16, 0x3b, 0x26, 0x97, 0xcd, 0x5a,
	0x2e, 0xf8, 0xc4, 0x15, 0x2c, 0x4f, 0x93, 0x90, 0x0a, 0xb5, 0x1d, 0x5d, 0x5d, 0xba, 0x60, 0xfb,
	0x0d, 0x3c, 0xab, 0xdc, 0x6a, 0xe3, 0xa8, 0x31, 0xbd, 0x98, 0x68, 0x7f, 0x98, 0xd8, 0x3f, 0x35,
	0xe8, 0xbd, 0x4f, 0x79, 0xf8, 0x2d, 0x8c, 0x69, 0x92, 0x2d, 0xb3, 0xaf, 0x1c, 0x9f, 0xc3, 0x7d,
	0xcc, 0x92, 0x5d, 0x2c, 0xcf, 0xca, 0x33, 0xc2, 0x31, 0x98, 0x61, 0x59, 0x14, 0x2c, 0x93, 0xd5,
	0x85, 0x0f, 0x54, 0xc4, 0xd5, 0xc0, 0x1d, 0x72, 0x53, 0xc7, 0xb7, 0x30, 0xc8, 0x0b, 0xf6, 0x3d,
	0xe1, 0xa5, 0xb8, 0x8a, 0xeb, 0x10, 0xb7, 0x84, 0x3d, 0x06, 0x74, 0xcb, 0x34, 0x25, 0xec, 0x50,
	0xaa, 0x3d, 0xfe, 0x73, 0xe0, 0x6d, 0xfd, 0x0e, 0xdf, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x15,
	0x3c, 0xf4, 0x37, 0xa1, 0x02, 0x00, 0x00,
}
