// Code generated by protoc-gen-go.
// source: consensus.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	consensus.proto

It has these top-level messages:
	Message
	UpdateStateMessage
	StateUpdatedMessage
	BlockchainInfo
	NullRequestMessage
	ValidatedTxs
	NewNodeMessage
	AddNodeMessage
	DelNodeMessage
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_TRANSACTION    Message_Type = 0
	Message_CONSENSUS      Message_Type = 1
	Message_STATE_UPDATED  Message_Type = 2
	Message_NULL_REQUEST   Message_Type = 3
	Message_NEGOTIATE_VIEW Message_Type = 4
)

var Message_Type_name = map[int32]string{
	0: "TRANSACTION",
	1: "CONSENSUS",
	2: "STATE_UPDATED",
	3: "NULL_REQUEST",
	4: "NEGOTIATE_VIEW",
}
var Message_Type_value = map[string]int32{
	"TRANSACTION":    0,
	"CONSENSUS":      1,
	"STATE_UPDATED":  2,
	"NULL_REQUEST":   3,
	"NEGOTIATE_VIEW": 4,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// This message type is used between consensus and outside
type Message struct {
	Type      Message_Type `protobuf:"varint,1,opt,name=type,enum=protos.Message_Type" json:"type,omitempty"`
	Timestamp int64        `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   []byte       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Id        uint64       `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_TRANSACTION
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateStateMessage struct {
	Id       uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SeqNo    uint64   `protobuf:"varint,2,opt,name=seqNo" json:"seqNo,omitempty"`
	TargetId []byte   `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Replicas []uint64 `protobuf:"varint,4,rep,packed,name=replicas" json:"replicas,omitempty"`
}

func (m *UpdateStateMessage) Reset()                    { *m = UpdateStateMessage{} }
func (m *UpdateStateMessage) String() string            { return proto.CompactTextString(m) }
func (*UpdateStateMessage) ProtoMessage()               {}
func (*UpdateStateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateStateMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateStateMessage) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *UpdateStateMessage) GetTargetId() []byte {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *UpdateStateMessage) GetReplicas() []uint64 {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type StateUpdatedMessage struct {
	SeqNo uint64 `protobuf:"varint,1,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *StateUpdatedMessage) Reset()                    { *m = StateUpdatedMessage{} }
func (m *StateUpdatedMessage) String() string            { return proto.CompactTextString(m) }
func (*StateUpdatedMessage) ProtoMessage()               {}
func (*StateUpdatedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StateUpdatedMessage) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

// BlockchainInfo
type BlockchainInfo struct {
	Height            uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	CurrentBlockHash  []byte `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash []byte `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
}

func (m *BlockchainInfo) Reset()                    { *m = BlockchainInfo{} }
func (m *BlockchainInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockchainInfo) ProtoMessage()               {}
func (*BlockchainInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BlockchainInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockchainInfo) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *BlockchainInfo) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

type NullRequestMessage struct {
	SeqNo uint64 `protobuf:"varint,1,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *NullRequestMessage) Reset()                    { *m = NullRequestMessage{} }
func (m *NullRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*NullRequestMessage) ProtoMessage()               {}
func (*NullRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NullRequestMessage) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

type ValidatedTxs struct {
	Transactions []*types.Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	Hash         string               `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	SeqNo        uint64               `protobuf:"varint,3,opt,name=seqNo" json:"seqNo,omitempty"`
	View         uint64               `protobuf:"varint,4,opt,name=view" json:"view,omitempty"`
	Timestamp    int64                `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ValidatedTxs) Reset()                    { *m = ValidatedTxs{} }
func (m *ValidatedTxs) String() string            { return proto.CompactTextString(m) }
func (*ValidatedTxs) ProtoMessage()               {}
func (*ValidatedTxs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ValidatedTxs) GetTransactions() []*types.Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *ValidatedTxs) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ValidatedTxs) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *ValidatedTxs) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ValidatedTxs) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type NewNodeMessage struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *NewNodeMessage) Reset()                    { *m = NewNodeMessage{} }
func (m *NewNodeMessage) String() string            { return proto.CompactTextString(m) }
func (*NewNodeMessage) ProtoMessage()               {}
func (*NewNodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NewNodeMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type AddNodeMessage struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *AddNodeMessage) Reset()                    { *m = AddNodeMessage{} }
func (m *AddNodeMessage) String() string            { return proto.CompactTextString(m) }
func (*AddNodeMessage) ProtoMessage()               {}
func (*AddNodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AddNodeMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DelNodeMessage struct {
	DelHash    []byte `protobuf:"bytes,1,opt,name=delHash,proto3" json:"delHash,omitempty"`
	RouterHash string `protobuf:"bytes,2,opt,name=routerHash" json:"routerHash,omitempty"`
	Id         uint64 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
}

func (m *DelNodeMessage) Reset()                    { *m = DelNodeMessage{} }
func (m *DelNodeMessage) String() string            { return proto.CompactTextString(m) }
func (*DelNodeMessage) ProtoMessage()               {}
func (*DelNodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DelNodeMessage) GetDelHash() []byte {
	if m != nil {
		return m.DelHash
	}
	return nil
}

func (m *DelNodeMessage) GetRouterHash() string {
	if m != nil {
		return m.RouterHash
	}
	return ""
}

func (m *DelNodeMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*UpdateStateMessage)(nil), "protos.UpdateStateMessage")
	proto.RegisterType((*StateUpdatedMessage)(nil), "protos.StateUpdatedMessage")
	proto.RegisterType((*BlockchainInfo)(nil), "protos.BlockchainInfo")
	proto.RegisterType((*NullRequestMessage)(nil), "protos.NullRequestMessage")
	proto.RegisterType((*ValidatedTxs)(nil), "protos.ValidatedTxs")
	proto.RegisterType((*NewNodeMessage)(nil), "protos.NewNodeMessage")
	proto.RegisterType((*AddNodeMessage)(nil), "protos.AddNodeMessage")
	proto.RegisterType((*DelNodeMessage)(nil), "protos.DelNodeMessage")
	proto.RegisterEnum("protos.Message_Type", Message_Type_name, Message_Type_value)
}

func init() { proto.RegisterFile("consensus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x4e, 0xd4, 0x40,
	0x14, 0x75, 0xb6, 0x05, 0xe4, 0xb2, 0x2c, 0xe5, 0x4a, 0x4c, 0x43, 0x8c, 0xd9, 0xf4, 0xc5, 0x06,
	0xcd, 0x92, 0x60, 0xe2, 0xfb, 0x0a, 0x8d, 0x6c, 0x82, 0x45, 0xa7, 0x5d, 0x4c, 0x7c, 0x21, 0x63,
	0x3b, 0xd2, 0xc6, 0xd2, 0x29, 0x33, 0x53, 0x70, 0x5f, 0xfd, 0x14, 0xbf, 0xcb, 0x8f, 0x31, 0x3b,
	0x6d, 0x77, 0x17, 0x48, 0x8c, 0x4f, 0x9d, 0x73, 0xef, 0x99, 0x9e, 0x7b, 0x7a, 0x4f, 0x61, 0x27,
	0x11, 0xa5, 0xe2, 0xa5, 0xaa, 0xd5, 0xa8, 0x92, 0x42, 0x0b, 0x5c, 0x37, 0x0f, 0xb5, 0xff, 0x2a,
	0x9b, 0x55, 0x5c, 0x26, 0x19, 0xcb, 0xcb, 0xc3, 0x44, 0x48, 0x7e, 0xa8, 0x67, 0x15, 0x57, 0x87,
	0x5a, 0xb2, 0x52, 0xb1, 0x44, 0xe7, 0xa2, 0x6c, 0x2e, 0x78, 0x7f, 0x08, 0x6c, 0x7c, 0xe4, 0x4a,
	0xb1, 0x2b, 0x8e, 0x3e, 0xd8, 0x73, 0x9a, 0x4b, 0x86, 0xc4, 0x1f, 0x1c, 0xed, 0x35, 0x0c, 0x35,
	0x6a, 0xdb, 0xa3, 0x78, 0x56, 0x71, 0x6a, 0x18, 0xf8, 0x02, 0x36, 0x75, 0x7e, 0xcd, 0x95, 0x66,
	0xd7, 0x95, 0xdb, 0x1b, 0x12, 0xdf, 0xa2, 0xcb, 0x02, 0xba, 0xb0, 0x51, 0xb1, 0x59, 0x21, 0x58,
	0xea, 0x5a, 0x43, 0xe2, 0xf7, 0x69, 0x07, 0x71, 0x00, 0xbd, 0x3c, 0x75, 0xed, 0x21, 0xf1, 0x6d,
	0xda, 0xcb, 0x53, 0xef, 0x12, 0xec, 0xf9, 0x5b, 0x71, 0x07, 0xb6, 0x62, 0x3a, 0x0e, 0xa3, 0xf1,
	0x71, 0x3c, 0x39, 0x0f, 0x9d, 0x27, 0xb8, 0x0d, 0x9b, 0xc7, 0xe7, 0x61, 0x14, 0x84, 0xd1, 0x34,
	0x72, 0x08, 0xee, 0xc2, 0x76, 0x14, 0x8f, 0xe3, 0xe0, 0x72, 0xfa, 0xe9, 0x64, 0x1c, 0x07, 0x27,
	0x4e, 0x0f, 0x1d, 0xe8, 0x87, 0xd3, 0xb3, 0xb3, 0x4b, 0x1a, 0x7c, 0x9e, 0x06, 0x51, 0xec, 0x58,
	0x88, 0x30, 0x08, 0x83, 0x0f, 0xe7, 0xf1, 0x64, 0x4e, 0xbc, 0x98, 0x04, 0x5f, 0x1c, 0xdb, 0x93,
	0x80, 0xd3, 0x2a, 0x65, 0x9a, 0x47, 0x9a, 0x69, 0xde, 0x19, 0x6d, 0xc6, 0x20, 0xdd, 0x18, 0xb8,
	0x07, 0x6b, 0x8a, 0xdf, 0x84, 0xc2, 0x58, 0xb1, 0x69, 0x03, 0x70, 0x1f, 0x9e, 0x6a, 0x26, 0xaf,
	0xb8, 0x9e, 0x74, 0x3e, 0x16, 0x78, 0xde, 0x93, 0xbc, 0x2a, 0xf2, 0x84, 0x29, 0xd7, 0x1e, 0x5a,
	0xbe, 0x4d, 0x17, 0xd8, 0x7b, 0x0d, 0xcf, 0x8c, 0x5a, 0x23, 0x9c, 0x76, 0xa2, 0x0b, 0x11, 0xb2,
	0x22, 0xe2, 0xfd, 0x22, 0x30, 0x78, 0x5f, 0x88, 0xe4, 0x87, 0xd9, 0xd5, 0xa4, 0xfc, 0x2e, 0xf0,
	0x39, 0xac, 0x67, 0x3c, 0xbf, 0xca, 0x74, 0xcb, 0x6c, 0x11, 0x1e, 0x80, 0x93, 0xd4, 0x52, 0xf2,
	0x52, 0x9b, 0x0b, 0xa7, 0x4c, 0x65, 0x66, 0xe0, 0x3e, 0x7d, 0x54, 0xc7, 0x37, 0xb0, 0x5b, 0x49,
	0x7e, 0x9b, 0x8b, 0x5a, 0x2d, 0xc9, 0x8d, 0x89, 0xc7, 0x0d, 0xef, 0x00, 0x30, 0xac, 0x8b, 0x82,
	0xf2, 0x9b, 0x9a, 0x2b, 0xfd, 0xef, 0x81, 0x7f, 0x13, 0xe8, 0x5f, 0xb0, 0x22, 0x37, 0xde, 0xe2,
	0x9f, 0x0a, 0xdf, 0x41, 0x7f, 0x25, 0x56, 0xca, 0x25, 0x43, 0xcb, 0xdf, 0x3a, 0xc2, 0x91, 0x49,
	0xdc, 0x28, 0x5e, 0xb6, 0xe8, 0x3d, 0x1e, 0x22, 0xd8, 0x59, 0x67, 0x61, 0x93, 0x9a, 0xf3, 0x52,
	0xd2, 0x5a, 0x5d, 0x04, 0x82, 0x7d, 0x9b, 0xf3, 0xbb, 0x36, 0x37, 0xe6, 0x7c, 0x3f, 0x81, 0x6b,
	0x0f, 0x12, 0xe8, 0x1d, 0xc0, 0x20, 0xe4, 0x77, 0xa1, 0x48, 0x17, 0x2b, 0x5f, 0xc9, 0x24, 0xb9,
	0x97, 0xc9, 0x39, 0x77, 0x9c, 0xa6, 0xff, 0xc7, 0xfd, 0x0a, 0x83, 0x13, 0x5e, 0x3c, 0xe0, 0xa6,
	0xbc, 0x30, 0x9f, 0xb7, 0xe5, 0xb6, 0x10, 0x5f, 0x02, 0x48, 0x51, 0x6b, 0x2e, 0x4f, 0x97, 0x2e,
	0x57, 0x2a, 0x6d, 0x08, 0xad, 0x2e, 0x84, 0xdf, 0x9a, 0x5f, 0xf7, 0xed, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x80, 0x92, 0x04, 0x0d, 0xd4, 0x03, 0x00, 0x00,
}
