// Code generated by protoc-gen-go.
// source: chain.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	chain.proto

It has these top-level messages:
	MemChain
	Chain
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemChain struct {
	Data    *Chain `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	CpChan  *Chain `protobuf:"bytes,2,opt,name=cpChan" json:"cpChan,omitempty"`
	TxDelta uint64 `protobuf:"varint,3,opt,name=txDelta" json:"txDelta,omitempty"`
}

func (m *MemChain) Reset()                    { *m = MemChain{} }
func (m *MemChain) String() string            { return proto.CompactTextString(m) }
func (*MemChain) ProtoMessage()               {}
func (*MemChain) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MemChain) GetData() *Chain {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MemChain) GetCpChan() *Chain {
	if m != nil {
		return m.CpChan
	}
	return nil
}

func (m *MemChain) GetTxDelta() uint64 {
	if m != nil {
		return m.TxDelta
	}
	return 0
}

type Chain struct {
	LatestBlockHash  []byte `protobuf:"bytes,1,opt,name=latestBlockHash,proto3" json:"latestBlockHash,omitempty"`
	ParentBlockHash  []byte `protobuf:"bytes,2,opt,name=parentBlockHash,proto3" json:"parentBlockHash,omitempty"`
	Height           uint64 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	RequiredBlockNum uint64 `protobuf:"varint,4,opt,name=requiredBlockNum" json:"requiredBlockNum,omitempty"`
	RequireBlockHash []byte `protobuf:"bytes,5,opt,name=requireBlockHash,proto3" json:"requireBlockHash,omitempty"`
	RecoveryNum      uint64 `protobuf:"varint,6,opt,name=recoveryNum" json:"recoveryNum,omitempty"`
	CurrentTxSum     uint64 `protobuf:"varint,7,opt,name=currentTxSum" json:"currentTxSum,omitempty"`
	Genesis          uint64 `protobuf:"varint,8,opt,name=genesis" json:"genesis,omitempty"`
	Extra            []byte `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (m *Chain) Reset()                    { *m = Chain{} }
func (m *Chain) String() string            { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()               {}
func (*Chain) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Chain) GetLatestBlockHash() []byte {
	if m != nil {
		return m.LatestBlockHash
	}
	return nil
}

func (m *Chain) GetParentBlockHash() []byte {
	if m != nil {
		return m.ParentBlockHash
	}
	return nil
}

func (m *Chain) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Chain) GetRequiredBlockNum() uint64 {
	if m != nil {
		return m.RequiredBlockNum
	}
	return 0
}

func (m *Chain) GetRequireBlockHash() []byte {
	if m != nil {
		return m.RequireBlockHash
	}
	return nil
}

func (m *Chain) GetRecoveryNum() uint64 {
	if m != nil {
		return m.RecoveryNum
	}
	return 0
}

func (m *Chain) GetCurrentTxSum() uint64 {
	if m != nil {
		return m.CurrentTxSum
	}
	return 0
}

func (m *Chain) GetGenesis() uint64 {
	if m != nil {
		return m.Genesis
	}
	return 0
}

func (m *Chain) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*MemChain)(nil), "types.MemChain")
	proto.RegisterType((*Chain)(nil), "types.Chain")
}

func init() { proto.RegisterFile("chain.proto", fileDescriptor0) }

var fileDescriptor1 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4e, 0x84, 0x40,
	0x10, 0x85, 0x03, 0x02, 0x33, 0x16, 0x24, 0x9a, 0x8e, 0x31, 0xbd, 0x24, 0xc4, 0x05, 0x71, 0xc1,
	0x42, 0x6f, 0xe0, 0xb8, 0x70, 0xa3, 0x0b, 0xf4, 0x02, 0x6d, 0x4f, 0x65, 0x9a, 0xc8, 0x9f, 0xdd,
	0x8d, 0x61, 0x8e, 0xe7, 0xcd, 0x4c, 0x17, 0x18, 0x71, 0x66, 0x96, 0xef, 0xbd, 0x2f, 0xf5, 0x2a,
	0x55, 0x10, 0x4b, 0x25, 0xaa, 0xb6, 0xe8, 0x75, 0x67, 0x3b, 0x16, 0xda, 0x7d, 0x8f, 0x26, 0xab,
	0x61, 0xfd, 0x8c, 0xcd, 0xc6, 0x05, 0x2c, 0x85, 0x60, 0x2b, 0xac, 0xe0, 0x5e, 0xea, 0xe5, 0xf1,
	0x5d, 0x52, 0x10, 0x51, 0x50, 0x56, 0x52, 0xc2, 0x6e, 0x20, 0x92, 0xfd, 0x46, 0x89, 0x96, 0xfb,
	0x27, 0x98, 0x39, 0x63, 0x1c, 0x56, 0x76, 0x7c, 0xc4, 0xda, 0x0a, 0x7e, 0x96, 0x7a, 0x79, 0x50,
	0xfe, 0xca, 0xec, 0xdb, 0x87, 0x70, 0xea, 0xca, 0xe1, 0xa2, 0x16, 0x16, 0x8d, 0x7d, 0xa8, 0x3b,
	0xf9, 0xf1, 0x24, 0x8c, 0xa2, 0xda, 0xa4, 0x3c, 0xb4, 0x1d, 0xd9, 0x0b, 0x8d, 0xed, 0x82, 0xf4,
	0x27, 0xf2, 0xc0, 0x66, 0xd7, 0x10, 0x29, 0xac, 0x76, 0xca, 0xce, 0xb5, 0xb3, 0x62, 0xb7, 0x70,
	0xa9, 0xf1, 0x73, 0xa8, 0x34, 0x6e, 0x09, 0x7e, 0x19, 0x1a, 0x1e, 0x10, 0x71, 0xe4, 0x2f, 0xd8,
	0xbf, 0xba, 0x90, 0xea, 0x8e, 0x7c, 0x96, 0x42, 0xac, 0x51, 0x76, 0x5f, 0xa8, 0xf7, 0x6e, 0x64,
	0x44, 0x23, 0x97, 0x16, 0xcb, 0x20, 0x91, 0x83, 0x76, 0x5b, 0xbe, 0x8d, 0xaf, 0x43, 0xc3, 0x57,
	0x84, 0xfc, 0xf3, 0xdc, 0xb5, 0x76, 0xd8, 0xa2, 0xa9, 0x0c, 0x5f, 0x4f, 0xd7, 0x9a, 0x25, 0xbb,
	0x82, 0x10, 0x47, 0xab, 0x05, 0x3f, 0xa7, 0x05, 0x26, 0xf1, 0x1e, 0xd1, 0xff, 0xee, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x26, 0x7b, 0x58, 0x5f, 0xce, 0x01, 0x00, 0x00,
}
