// Code generated by protoc-gen-go.
// source: transaction_value.proto
// DO NOT EDIT!

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TransactionValue_Opcode int32

const (
	TransactionValue_NORMAL   TransactionValue_Opcode = 0
	TransactionValue_UPDATE   TransactionValue_Opcode = 1
	TransactionValue_FREEZE   TransactionValue_Opcode = 2
	TransactionValue_UNFREEZE TransactionValue_Opcode = 3
	TransactionValue_ARCHIVE  TransactionValue_Opcode = 100
)

var TransactionValue_Opcode_name = map[int32]string{
	0:   "NORMAL",
	1:   "UPDATE",
	2:   "FREEZE",
	3:   "UNFREEZE",
	100: "ARCHIVE",
}
var TransactionValue_Opcode_value = map[string]int32{
	"NORMAL":   0,
	"UPDATE":   1,
	"FREEZE":   2,
	"UNFREEZE": 3,
	"ARCHIVE":  100,
}

func (x TransactionValue_Opcode) String() string {
	return proto.EnumName(TransactionValue_Opcode_name, int32(x))
}
func (TransactionValue_Opcode) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0, 0} }

type TransactionValue_VmType int32

const (
	TransactionValue_EVM TransactionValue_VmType = 0
	TransactionValue_JVM TransactionValue_VmType = 1
)

var TransactionValue_VmType_name = map[int32]string{
	0: "EVM",
	1: "JVM",
}
var TransactionValue_VmType_value = map[string]int32{
	"EVM": 0,
	"JVM": 1,
}

func (x TransactionValue_VmType) String() string {
	return proto.EnumName(TransactionValue_VmType_name, int32(x))
}
func (TransactionValue_VmType) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0, 1} }

type TransactionValue struct {
	Price              int64                   `protobuf:"varint,1,opt,name=price" json:"price,omitempty"`
	GasLimit           int64                   `protobuf:"varint,2,opt,name=gasLimit" json:"gasLimit,omitempty"`
	Amount             int64                   `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Payload            []byte                  `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	EncryptedAmount    []byte                  `protobuf:"bytes,5,opt,name=encryptedAmount,proto3" json:"encryptedAmount,omitempty"`
	HomomorphicAmount  []byte                  `protobuf:"bytes,6,opt,name=homomorphicAmount,proto3" json:"homomorphicAmount,omitempty"`
	HomomorphicBalance []byte                  `protobuf:"bytes,7,opt,name=homomorphicBalance,proto3" json:"homomorphicBalance,omitempty"`
	Op                 TransactionValue_Opcode `protobuf:"varint,8,opt,name=op,enum=types.TransactionValue_Opcode" json:"op,omitempty"`
	VmType             TransactionValue_VmType `protobuf:"varint,9,opt,name=vmType,enum=types.TransactionValue_VmType" json:"vmType,omitempty"`
}

func (m *TransactionValue) Reset()                    { *m = TransactionValue{} }
func (m *TransactionValue) String() string            { return proto.CompactTextString(m) }
func (*TransactionValue) ProtoMessage()               {}
func (*TransactionValue) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *TransactionValue) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TransactionValue) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *TransactionValue) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionValue) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TransactionValue) GetEncryptedAmount() []byte {
	if m != nil {
		return m.EncryptedAmount
	}
	return nil
}

func (m *TransactionValue) GetHomomorphicAmount() []byte {
	if m != nil {
		return m.HomomorphicAmount
	}
	return nil
}

func (m *TransactionValue) GetHomomorphicBalance() []byte {
	if m != nil {
		return m.HomomorphicBalance
	}
	return nil
}

func (m *TransactionValue) GetOp() TransactionValue_Opcode {
	if m != nil {
		return m.Op
	}
	return TransactionValue_NORMAL
}

func (m *TransactionValue) GetVmType() TransactionValue_VmType {
	if m != nil {
		return m.VmType
	}
	return TransactionValue_EVM
}

type InvokeArgs struct {
	Code       []byte   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	MethodName string   `protobuf:"bytes,2,opt,name=methodName" json:"methodName,omitempty"`
	Args       [][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *InvokeArgs) Reset()                    { *m = InvokeArgs{} }
func (m *InvokeArgs) String() string            { return proto.CompactTextString(m) }
func (*InvokeArgs) ProtoMessage()               {}
func (*InvokeArgs) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *InvokeArgs) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *InvokeArgs) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *InvokeArgs) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionValue)(nil), "types.TransactionValue")
	proto.RegisterType((*InvokeArgs)(nil), "types.InvokeArgs")
	proto.RegisterEnum("types.TransactionValue_Opcode", TransactionValue_Opcode_name, TransactionValue_Opcode_value)
	proto.RegisterEnum("types.TransactionValue_VmType", TransactionValue_VmType_name, TransactionValue_VmType_value)
}

func init() { proto.RegisterFile("transaction_value.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0xaf, 0x93, 0x40,
	0x14, 0xc5, 0x1f, 0xf0, 0x0a, 0xed, 0xb5, 0x51, 0xbc, 0x31, 0x3a, 0xe9, 0xa2, 0x21, 0xac, 0x58,
	0x18, 0x16, 0x9a, 0xb8, 0x47, 0x45, 0xad, 0xe9, 0x1f, 0x33, 0xa1, 0x2c, 0xdc, 0x98, 0x11, 0x26,
	0x2d, 0xb1, 0x30, 0x13, 0x98, 0x36, 0xe1, 0x33, 0xfa, 0xa5, 0xcc, 0x0c, 0xa8, 0x4d, 0x35, 0x6f,
	0x77, 0xce, 0x3d, 0xbf, 0x33, 0x24, 0xf7, 0x02, 0x2f, 0x54, 0xcb, 0x9a, 0x8e, 0x15, 0xaa, 0x12,
	0xcd, 0xb7, 0x0b, 0x3b, 0x9d, 0x79, 0x2c, 0x5b, 0xa1, 0x04, 0x4e, 0x54, 0x2f, 0x79, 0x17, 0xfe,
	0x74, 0xc0, 0xcf, 0xfe, 0x22, 0xb9, 0x26, 0xf0, 0x19, 0x4c, 0x64, 0x5b, 0x15, 0x9c, 0x58, 0x81,
	0x15, 0x39, 0x74, 0x30, 0xb8, 0x80, 0xe9, 0x81, 0x75, 0xeb, 0xaa, 0xae, 0x14, 0xb1, 0x4d, 0xf0,
	0xc7, 0xe3, 0x73, 0x70, 0x59, 0x2d, 0xce, 0x8d, 0x22, 0x8e, 0x49, 0x46, 0x87, 0x04, 0x3c, 0xc9,
	0xfa, 0x93, 0x60, 0x25, 0xb9, 0x0f, 0xac, 0x68, 0x4e, 0x7f, 0x5b, 0x8c, 0xe0, 0x09, 0x6f, 0x8a,
	0xb6, 0x97, 0x8a, 0x97, 0xc9, 0x50, 0x9d, 0x18, 0xe2, 0x76, 0x8c, 0x2f, 0xe1, 0xe9, 0x51, 0xd4,
	0xa2, 0x16, 0xad, 0x3c, 0x56, 0xc5, 0xc8, 0xba, 0x86, 0xfd, 0x37, 0xc0, 0x18, 0xf0, 0x6a, 0xf8,
	0x96, 0x9d, 0x58, 0x53, 0x70, 0xe2, 0x19, 0xfc, 0x3f, 0x09, 0xc6, 0x60, 0x0b, 0x49, 0xa6, 0x81,
	0x15, 0x3d, 0x7e, 0xb5, 0x8c, 0xcd, 0x52, 0xe2, 0xdb, 0x85, 0xc4, 0x3b, 0x59, 0x88, 0x92, 0x53,
	0x5b, 0x48, 0x7c, 0x03, 0xee, 0xa5, 0xce, 0x7a, 0xc9, 0xc9, 0xec, 0xe1, 0x4e, 0x6e, 0x28, 0x3a,
	0xd2, 0xe1, 0x47, 0x70, 0x87, 0x57, 0x10, 0xc0, 0xdd, 0xee, 0xe8, 0x26, 0x59, 0xfb, 0x77, 0x5a,
	0xef, 0xbf, 0xbc, 0x4f, 0xb2, 0xd4, 0xb7, 0xb4, 0xfe, 0x40, 0xd3, 0xf4, 0x6b, 0xea, 0xdb, 0x38,
	0x87, 0xe9, 0x7e, 0x3b, 0x3a, 0x07, 0x1f, 0x81, 0x97, 0xd0, 0x77, 0x9f, 0x56, 0x79, 0xea, 0x97,
	0xe1, 0x02, 0xdc, 0xe1, 0x69, 0xf4, 0xc0, 0x49, 0xf3, 0x8d, 0x7f, 0xa7, 0xc5, 0xe7, 0x7c, 0xe3,
	0x5b, 0x61, 0x06, 0xb0, 0x6a, 0x2e, 0xe2, 0x07, 0x4f, 0xda, 0x43, 0x87, 0x08, 0xf7, 0xfa, 0x83,
	0xe6, 0x8a, 0x73, 0x6a, 0x34, 0x2e, 0x01, 0x6a, 0xae, 0x8e, 0xa2, 0xdc, 0xb2, 0x9a, 0x9b, 0x33,
	0xce, 0xe8, 0xd5, 0x44, 0x77, 0x58, 0x7b, 0xe8, 0x88, 0x13, 0x38, 0xba, 0xa3, 0xf5, 0x77, 0xd7,
	0xfc, 0x31, 0xaf, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xc6, 0xc5, 0xb7, 0x4c, 0x02, 0x00,
	0x00,
}
