// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package pbft is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ConsensusMessage
	TransactionBatch
	ReturnRequestBatch
	PrePrepare
	Prepare
	Commit
	BlockInfo
	Checkpoint
	ViewChange
	NewView
	FinishVcReset
	FetchRequestBatch
	NegotiateView
	NegotiateViewResponse
	RecoveryInit
	RecoveryResponse
	RecoveryFetchPQC
	RecoveryReturnPQC
	Pset
	Cset
	AddNode
	DelNode
	ReadyForN
	AgreeUpdateN
	UpdateN
	FinishUpdate
*/
package pbft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsensusMessage_Type int32

const (
	ConsensusMessage_TRANSACTION             ConsensusMessage_Type = 0
	ConsensusMessage_PRE_PREPARE             ConsensusMessage_Type = 1
	ConsensusMessage_PREPARE                 ConsensusMessage_Type = 2
	ConsensusMessage_COMMIT                  ConsensusMessage_Type = 3
	ConsensusMessage_CHECKPOINT              ConsensusMessage_Type = 4
	ConsensusMessage_VIEW_CHANGE             ConsensusMessage_Type = 5
	ConsensusMessage_NEW_VIEW                ConsensusMessage_Type = 6
	ConsensusMessage_FINISH_VCRESET          ConsensusMessage_Type = 7
	ConsensusMessage_FRTCH_REQUEST_BATCH     ConsensusMessage_Type = 8
	ConsensusMessage_RETURN_REQUEST_BATCH    ConsensusMessage_Type = 9
	ConsensusMessage_NEGOTIATE_VIEW          ConsensusMessage_Type = 10
	ConsensusMessage_NEGOTIATE_VIEW_RESPONSE ConsensusMessage_Type = 11
	ConsensusMessage_RECOVERY_INIT           ConsensusMessage_Type = 12
	ConsensusMessage_RECOVERY_RESPONSE       ConsensusMessage_Type = 13
	ConsensusMessage_RECOVERY_FETCH_QPC      ConsensusMessage_Type = 14
	ConsensusMessage_RECOVERY_RETURN_QPC     ConsensusMessage_Type = 15
	ConsensusMessage_ADD_NODE                ConsensusMessage_Type = 16
	ConsensusMessage_DEL_NODE                ConsensusMessage_Type = 17
	ConsensusMessage_READY_FOR_N             ConsensusMessage_Type = 18
	ConsensusMessage_AGREE_UPDATE_N          ConsensusMessage_Type = 19
	ConsensusMessage_UPDATE_N                ConsensusMessage_Type = 20
	ConsensusMessage_FINISH_UPDATE           ConsensusMessage_Type = 21
)

var ConsensusMessage_Type_name = map[int32]string{
	0:  "TRANSACTION",
	1:  "PRE_PREPARE",
	2:  "PREPARE",
	3:  "COMMIT",
	4:  "CHECKPOINT",
	5:  "VIEW_CHANGE",
	6:  "NEW_VIEW",
	7:  "FINISH_VCRESET",
	8:  "FRTCH_REQUEST_BATCH",
	9:  "RETURN_REQUEST_BATCH",
	10: "NEGOTIATE_VIEW",
	11: "NEGOTIATE_VIEW_RESPONSE",
	12: "RECOVERY_INIT",
	13: "RECOVERY_RESPONSE",
	14: "RECOVERY_FETCH_QPC",
	15: "RECOVERY_RETURN_QPC",
	16: "ADD_NODE",
	17: "DEL_NODE",
	18: "READY_FOR_N",
	19: "AGREE_UPDATE_N",
	20: "UPDATE_N",
	21: "FINISH_UPDATE",
}
var ConsensusMessage_Type_value = map[string]int32{
	"TRANSACTION":             0,
	"PRE_PREPARE":             1,
	"PREPARE":                 2,
	"COMMIT":                  3,
	"CHECKPOINT":              4,
	"VIEW_CHANGE":             5,
	"NEW_VIEW":                6,
	"FINISH_VCRESET":          7,
	"FRTCH_REQUEST_BATCH":     8,
	"RETURN_REQUEST_BATCH":    9,
	"NEGOTIATE_VIEW":          10,
	"NEGOTIATE_VIEW_RESPONSE": 11,
	"RECOVERY_INIT":           12,
	"RECOVERY_RESPONSE":       13,
	"RECOVERY_FETCH_QPC":      14,
	"RECOVERY_RETURN_QPC":     15,
	"ADD_NODE":                16,
	"DEL_NODE":                17,
	"READY_FOR_N":             18,
	"AGREE_UPDATE_N":          19,
	"UPDATE_N":                20,
	"FINISH_UPDATE":           21,
}

func (x ConsensusMessage_Type) String() string {
	return proto.EnumName(ConsensusMessage_Type_name, int32(x))
}
func (ConsensusMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ConsensusMessage struct {
	Type    ConsensusMessage_Type `protobuf:"varint,1,opt,name=type,enum=pbft.ConsensusMessage_Type" json:"type,omitempty"`
	Payload []byte                `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ConsensusMessage) Reset()                    { *m = ConsensusMessage{} }
func (m *ConsensusMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusMessage) ProtoMessage()               {}
func (*ConsensusMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConsensusMessage) GetType() ConsensusMessage_Type {
	if m != nil {
		return m.Type
	}
	return ConsensusMessage_TRANSACTION
}

func (m *ConsensusMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TransactionBatch struct {
	Batch     []*types.Transaction `protobuf:"bytes,1,rep,name=batch" json:"batch,omitempty"`
	Timestamp int64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *TransactionBatch) Reset()                    { *m = TransactionBatch{} }
func (m *TransactionBatch) String() string            { return proto.CompactTextString(m) }
func (*TransactionBatch) ProtoMessage()               {}
func (*TransactionBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionBatch) GetBatch() []*types.Transaction {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *TransactionBatch) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ReturnRequestBatch struct {
	Batch  *TransactionBatch `protobuf:"bytes,1,opt,name=batch" json:"batch,omitempty"`
	Digest string            `protobuf:"bytes,2,opt,name=digest" json:"digest,omitempty"`
}

func (m *ReturnRequestBatch) Reset()                    { *m = ReturnRequestBatch{} }
func (m *ReturnRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*ReturnRequestBatch) ProtoMessage()               {}
func (*ReturnRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReturnRequestBatch) GetBatch() *TransactionBatch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *ReturnRequestBatch) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

type PrePrepare struct {
	View             uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber   uint64            `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest      string            `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	TransactionBatch *TransactionBatch `protobuf:"bytes,4,opt,name=transaction_batch,json=transactionBatch" json:"transaction_batch,omitempty"`
	ReplicaId        uint64            `protobuf:"varint,5,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *PrePrepare) Reset()                    { *m = PrePrepare{} }
func (m *PrePrepare) String() string            { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()               {}
func (*PrePrepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *PrePrepare) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *PrePrepare) GetTransactionBatch() *TransactionBatch {
	if m != nil {
		return m.TransactionBatch
	}
	return nil
}

func (m *PrePrepare) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type Prepare struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Prepare) Reset()                    { *m = Prepare{} }
func (m *Prepare) String() string            { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()               {}
func (*Prepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Prepare) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *Prepare) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type Commit struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Commit) Reset()                    { *m = Commit{} }
func (m *Commit) String() string            { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()               {}
func (*Commit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Commit) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *Commit) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type BlockInfo struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number,omitempty"`
	BlockHash   []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (m *BlockInfo) Reset()                    { *m = BlockInfo{} }
func (m *BlockInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()               {}
func (*BlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BlockInfo) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *BlockInfo) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type Checkpoint struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Checkpoint) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Checkpoint) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Checkpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ViewChange struct {
	View      uint64           `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	H         uint64           `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Cset      []*ViewChange_C  `protobuf:"bytes,3,rep,name=cset" json:"cset,omitempty"`
	Pset      []*ViewChange_PQ `protobuf:"bytes,4,rep,name=pset" json:"pset,omitempty"`
	Qset      []*ViewChange_PQ `protobuf:"bytes,5,rep,name=qset" json:"qset,omitempty"`
	ReplicaId uint64           `protobuf:"varint,6,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Signature []byte           `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp int64            `protobuf:"varint,8,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ViewChange) Reset()                    { *m = ViewChange{} }
func (m *ViewChange) String() string            { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()               {}
func (*ViewChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ViewChange) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ViewChange) GetH() uint64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *ViewChange) GetCset() []*ViewChange_C {
	if m != nil {
		return m.Cset
	}
	return nil
}

func (m *ViewChange) GetPset() []*ViewChange_PQ {
	if m != nil {
		return m.Pset
	}
	return nil
}

func (m *ViewChange) GetQset() []*ViewChange_PQ {
	if m != nil {
		return m.Qset
	}
	return nil
}

func (m *ViewChange) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *ViewChange) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ViewChange) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// This message should go away and become a checkpoint once replica_id is removed
type ViewChange_C struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *ViewChange_C) Reset()                    { *m = ViewChange_C{} }
func (m *ViewChange_C) String() string            { return proto.CompactTextString(m) }
func (*ViewChange_C) ProtoMessage()               {}
func (*ViewChange_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *ViewChange_C) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ViewChange_C) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ViewChange_PQ struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,2,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	View           uint64 `protobuf:"varint,3,opt,name=view" json:"view,omitempty"`
}

func (m *ViewChange_PQ) Reset()                    { *m = ViewChange_PQ{} }
func (m *ViewChange_PQ) String() string            { return proto.CompactTextString(m) }
func (*ViewChange_PQ) ProtoMessage()               {}
func (*ViewChange_PQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 1} }

func (m *ViewChange_PQ) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ViewChange_PQ) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *ViewChange_PQ) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

type NewView struct {
	View      uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	Vset      []*ViewChange     `protobuf:"bytes,2,rep,name=vset" json:"vset,omitempty"`
	Xset      map[uint64]string `protobuf:"bytes,3,rep,name=xset" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReplicaId uint64            `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NewView) Reset()                    { *m = NewView{} }
func (m *NewView) String() string            { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()               {}
func (*NewView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *NewView) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NewView) GetVset() []*ViewChange {
	if m != nil {
		return m.Vset
	}
	return nil
}

func (m *NewView) GetXset() map[uint64]string {
	if m != nil {
		return m.Xset
	}
	return nil
}

func (m *NewView) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type FinishVcReset struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
	LowH      uint64 `protobuf:"varint,3,opt,name=low_h,json=lowH" json:"low_h,omitempty"`
}

func (m *FinishVcReset) Reset()                    { *m = FinishVcReset{} }
func (m *FinishVcReset) String() string            { return proto.CompactTextString(m) }
func (*FinishVcReset) ProtoMessage()               {}
func (*FinishVcReset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FinishVcReset) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *FinishVcReset) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *FinishVcReset) GetLowH() uint64 {
	if m != nil {
		return m.LowH
	}
	return 0
}

type FetchRequestBatch struct {
	BatchDigest string `protobuf:"bytes,1,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId   uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *FetchRequestBatch) Reset()                    { *m = FetchRequestBatch{} }
func (m *FetchRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*FetchRequestBatch) ProtoMessage()               {}
func (*FetchRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *FetchRequestBatch) GetBatchDigest() string {
	if m != nil {
		return m.BatchDigest
	}
	return ""
}

func (m *FetchRequestBatch) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type NegotiateView struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NegotiateView) Reset()                    { *m = NegotiateView{} }
func (m *NegotiateView) String() string            { return proto.CompactTextString(m) }
func (*NegotiateView) ProtoMessage()               {}
func (*NegotiateView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *NegotiateView) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type NegotiateViewResponse struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
	N         uint64 `protobuf:"varint,3,opt,name=n" json:"n,omitempty"`
	Routers   []byte `protobuf:"bytes,4,opt,name=routers,proto3" json:"routers,omitempty"`
}

func (m *NegotiateViewResponse) Reset()                    { *m = NegotiateViewResponse{} }
func (m *NegotiateViewResponse) String() string            { return proto.CompactTextString(m) }
func (*NegotiateViewResponse) ProtoMessage()               {}
func (*NegotiateViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *NegotiateViewResponse) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *NegotiateViewResponse) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *NegotiateViewResponse) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *NegotiateViewResponse) GetRouters() []byte {
	if m != nil {
		return m.Routers
	}
	return nil
}

type RecoveryInit struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *RecoveryInit) Reset()                    { *m = RecoveryInit{} }
func (m *RecoveryInit) String() string            { return proto.CompactTextString(m) }
func (*RecoveryInit) ProtoMessage()               {}
func (*RecoveryInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RecoveryInit) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

type RecoveryResponse struct {
	ReplicaId     uint64            `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Chkpts        map[uint64]string `protobuf:"bytes,2,rep,name=chkpts" json:"chkpts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BlockHeight   uint64            `protobuf:"varint,3,opt,name=blockHeight" json:"blockHeight,omitempty"`
	LastBlockHash string            `protobuf:"bytes,4,opt,name=lastBlockHash" json:"lastBlockHash,omitempty"`
}

func (m *RecoveryResponse) Reset()                    { *m = RecoveryResponse{} }
func (m *RecoveryResponse) String() string            { return proto.CompactTextString(m) }
func (*RecoveryResponse) ProtoMessage()               {}
func (*RecoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RecoveryResponse) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *RecoveryResponse) GetChkpts() map[uint64]string {
	if m != nil {
		return m.Chkpts
	}
	return nil
}

func (m *RecoveryResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *RecoveryResponse) GetLastBlockHash() string {
	if m != nil {
		return m.LastBlockHash
	}
	return ""
}

type RecoveryFetchPQC struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	H         uint64 `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
}

func (m *RecoveryFetchPQC) Reset()                    { *m = RecoveryFetchPQC{} }
func (m *RecoveryFetchPQC) String() string            { return proto.CompactTextString(m) }
func (*RecoveryFetchPQC) ProtoMessage()               {}
func (*RecoveryFetchPQC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RecoveryFetchPQC) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *RecoveryFetchPQC) GetH() uint64 {
	if m != nil {
		return m.H
	}
	return 0
}

type RecoveryReturnPQC struct {
	ReplicaId uint64        `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	PrepreSet []*PrePrepare `protobuf:"bytes,2,rep,name=prepre_set,json=prepreSet" json:"prepre_set,omitempty"`
	PreSent   []bool        `protobuf:"varint,3,rep,packed,name=pre_sent,json=preSent" json:"pre_sent,omitempty"`
	CmtSent   []bool        `protobuf:"varint,4,rep,packed,name=cmt_sent,json=cmtSent" json:"cmt_sent,omitempty"`
}

func (m *RecoveryReturnPQC) Reset()                    { *m = RecoveryReturnPQC{} }
func (m *RecoveryReturnPQC) String() string            { return proto.CompactTextString(m) }
func (*RecoveryReturnPQC) ProtoMessage()               {}
func (*RecoveryReturnPQC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RecoveryReturnPQC) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *RecoveryReturnPQC) GetPrepreSet() []*PrePrepare {
	if m != nil {
		return m.PrepreSet
	}
	return nil
}

func (m *RecoveryReturnPQC) GetPreSent() []bool {
	if m != nil {
		return m.PreSent
	}
	return nil
}

func (m *RecoveryReturnPQC) GetCmtSent() []bool {
	if m != nil {
		return m.CmtSent
	}
	return nil
}

type Pset struct {
	Set []*Prepare `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (m *Pset) Reset()                    { *m = Pset{} }
func (m *Pset) String() string            { return proto.CompactTextString(m) }
func (*Pset) ProtoMessage()               {}
func (*Pset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Pset) GetSet() []*Prepare {
	if m != nil {
		return m.Set
	}
	return nil
}

type Cset struct {
	Set []*Commit `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (m *Cset) Reset()                    { *m = Cset{} }
func (m *Cset) String() string            { return proto.CompactTextString(m) }
func (*Cset) ProtoMessage()               {}
func (*Cset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Cset) GetSet() []*Commit {
	if m != nil {
		return m.Set
	}
	return nil
}

type AddNode struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *AddNode) Reset()                    { *m = AddNode{} }
func (m *AddNode) String() string            { return proto.CompactTextString(m) }
func (*AddNode) ProtoMessage()               {}
func (*AddNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *AddNode) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *AddNode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelNode struct {
	ReplicaId  uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key        string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	RouterHash string `protobuf:"bytes,3,opt,name=router_hash,json=routerHash" json:"router_hash,omitempty"`
}

func (m *DelNode) Reset()                    { *m = DelNode{} }
func (m *DelNode) String() string            { return proto.CompactTextString(m) }
func (*DelNode) ProtoMessage()               {}
func (*DelNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DelNode) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *DelNode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DelNode) GetRouterHash() string {
	if m != nil {
		return m.RouterHash
	}
	return ""
}

type ReadyForN struct {
	ReplicaId uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key       string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *ReadyForN) Reset()                    { *m = ReadyForN{} }
func (m *ReadyForN) String() string            { return proto.CompactTextString(m) }
func (*ReadyForN) ProtoMessage()               {}
func (*ReadyForN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ReadyForN) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *ReadyForN) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type AgreeUpdateN struct {
	Flag       bool             `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
	ReplicaId  uint64           `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key        string           `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	RouterHash string           `protobuf:"bytes,4,opt,name=routerHash" json:"routerHash,omitempty"`
	N          int64            `protobuf:"varint,5,opt,name=n" json:"n,omitempty"`
	View       uint64           `protobuf:"varint,6,opt,name=view" json:"view,omitempty"`
	H          uint64           `protobuf:"varint,7,opt,name=h" json:"h,omitempty"`
	Cset       []*ViewChange_C  `protobuf:"bytes,8,rep,name=cset" json:"cset,omitempty"`
	Pset       []*ViewChange_PQ `protobuf:"bytes,9,rep,name=pset" json:"pset,omitempty"`
	Qset       []*ViewChange_PQ `protobuf:"bytes,10,rep,name=qset" json:"qset,omitempty"`
}

func (m *AgreeUpdateN) Reset()                    { *m = AgreeUpdateN{} }
func (m *AgreeUpdateN) String() string            { return proto.CompactTextString(m) }
func (*AgreeUpdateN) ProtoMessage()               {}
func (*AgreeUpdateN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *AgreeUpdateN) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *AgreeUpdateN) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *AgreeUpdateN) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AgreeUpdateN) GetRouterHash() string {
	if m != nil {
		return m.RouterHash
	}
	return ""
}

func (m *AgreeUpdateN) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *AgreeUpdateN) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *AgreeUpdateN) GetH() uint64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *AgreeUpdateN) GetCset() []*ViewChange_C {
	if m != nil {
		return m.Cset
	}
	return nil
}

func (m *AgreeUpdateN) GetPset() []*ViewChange_PQ {
	if m != nil {
		return m.Pset
	}
	return nil
}

func (m *AgreeUpdateN) GetQset() []*ViewChange_PQ {
	if m != nil {
		return m.Qset
	}
	return nil
}

type UpdateN struct {
	Flag      bool              `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
	ReplicaId uint64            `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Key       string            `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	N         int64             `protobuf:"varint,4,opt,name=n" json:"n,omitempty"`
	View      uint64            `protobuf:"varint,5,opt,name=view" json:"view,omitempty"`
	Aset      []*AgreeUpdateN   `protobuf:"bytes,6,rep,name=aset" json:"aset,omitempty"`
	Xset      map[uint64]string `protobuf:"bytes,7,rep,name=xset" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *UpdateN) Reset()                    { *m = UpdateN{} }
func (m *UpdateN) String() string            { return proto.CompactTextString(m) }
func (*UpdateN) ProtoMessage()               {}
func (*UpdateN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *UpdateN) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *UpdateN) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *UpdateN) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateN) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *UpdateN) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *UpdateN) GetAset() []*AgreeUpdateN {
	if m != nil {
		return m.Aset
	}
	return nil
}

func (m *UpdateN) GetXset() map[uint64]string {
	if m != nil {
		return m.Xset
	}
	return nil
}

type FinishUpdate struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
	LowH      uint64 `protobuf:"varint,3,opt,name=low_h,json=lowH" json:"low_h,omitempty"`
}

func (m *FinishUpdate) Reset()                    { *m = FinishUpdate{} }
func (m *FinishUpdate) String() string            { return proto.CompactTextString(m) }
func (*FinishUpdate) ProtoMessage()               {}
func (*FinishUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *FinishUpdate) GetReplicaId() uint64 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *FinishUpdate) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *FinishUpdate) GetLowH() uint64 {
	if m != nil {
		return m.LowH
	}
	return 0
}

func init() {
	proto.RegisterType((*ConsensusMessage)(nil), "pbft.consensus_message")
	proto.RegisterType((*TransactionBatch)(nil), "pbft.transaction_batch")
	proto.RegisterType((*ReturnRequestBatch)(nil), "pbft.return_request_batch")
	proto.RegisterType((*PrePrepare)(nil), "pbft.pre_prepare")
	proto.RegisterType((*Prepare)(nil), "pbft.prepare")
	proto.RegisterType((*Commit)(nil), "pbft.commit")
	proto.RegisterType((*BlockInfo)(nil), "pbft.block_info")
	proto.RegisterType((*Checkpoint)(nil), "pbft.checkpoint")
	proto.RegisterType((*ViewChange)(nil), "pbft.view_change")
	proto.RegisterType((*ViewChange_C)(nil), "pbft.view_change.C")
	proto.RegisterType((*ViewChange_PQ)(nil), "pbft.view_change.PQ")
	proto.RegisterType((*NewView)(nil), "pbft.new_view")
	proto.RegisterType((*FinishVcReset)(nil), "pbft.finish_vcReset")
	proto.RegisterType((*FetchRequestBatch)(nil), "pbft.fetch_request_batch")
	proto.RegisterType((*NegotiateView)(nil), "pbft.negotiate_view")
	proto.RegisterType((*NegotiateViewResponse)(nil), "pbft.negotiate_view_response")
	proto.RegisterType((*RecoveryInit)(nil), "pbft.recovery_init")
	proto.RegisterType((*RecoveryResponse)(nil), "pbft.recovery_response")
	proto.RegisterType((*RecoveryFetchPQC)(nil), "pbft.recovery_fetchPQC")
	proto.RegisterType((*RecoveryReturnPQC)(nil), "pbft.recovery_returnPQC")
	proto.RegisterType((*Pset)(nil), "pbft.Pset")
	proto.RegisterType((*Cset)(nil), "pbft.Cset")
	proto.RegisterType((*AddNode)(nil), "pbft.add_node")
	proto.RegisterType((*DelNode)(nil), "pbft.del_node")
	proto.RegisterType((*ReadyForN)(nil), "pbft.ready_for_n")
	proto.RegisterType((*AgreeUpdateN)(nil), "pbft.agree_update_n")
	proto.RegisterType((*UpdateN)(nil), "pbft.update_n")
	proto.RegisterType((*FinishUpdate)(nil), "pbft.finish_update")
	proto.RegisterEnum("pbft.ConsensusMessage_Type", ConsensusMessage_Type_name, ConsensusMessage_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x57, 0xcb, 0x72, 0xdb, 0x36,
	0x17, 0xfe, 0x29, 0x51, 0xb7, 0x23, 0x59, 0xa1, 0x61, 0x27, 0xd6, 0xef, 0x3f, 0x17, 0xff, 0xec,
	0xc5, 0x5e, 0xb4, 0x72, 0x26, 0x5d, 0xf4, 0x92, 0x4e, 0xa7, 0x0a, 0x45, 0x47, 0x9a, 0x36, 0x94,
	0x0c, 0x2b, 0x71, 0x32, 0x6d, 0x07, 0x43, 0x93, 0xb0, 0xc8, 0xb1, 0x44, 0x32, 0x24, 0x65, 0x57,
	0xdb, 0x6e, 0xd2, 0x77, 0xe8, 0xae, 0x33, 0x5d, 0xf5, 0x51, 0xba, 0xeb, 0xa3, 0xf4, 0x09, 0x3a,
	0x00, 0x28, 0x99, 0xa2, 0x3c, 0x91, 0x93, 0xc9, 0xb4, 0x3b, 0xe2, 0xe0, 0xc3, 0x39, 0xdf, 0x77,
	0x70, 0x80, 0x03, 0x42, 0x7d, 0x4c, 0xa3, 0xc8, 0x1c, 0xd2, 0xa8, 0x19, 0x84, 0x7e, 0xec, 0x23,
	0x39, 0x38, 0x39, 0x8d, 0xb7, 0x77, 0x9d, 0x69, 0x40, 0x43, 0xcb, 0x31, 0x5d, 0x6f, 0xdf, 0xf2,
	0x43, 0xba, 0x1f, 0x4f, 0x03, 0x1a, 0xed, 0xc7, 0xa1, 0xe9, 0x45, 0xa6, 0x15, 0xbb, 0xbe, 0x27,
	0xe0, 0xea, 0x2b, 0x19, 0xd6, 0x2d, 0xdf, 0x8b, 0xa8, 0x17, 0x4d, 0x22, 0x92, 0xf8, 0x42, 0xf7,
	0x41, 0x66, 0x0b, 0x1a, 0xd2, 0x8e, 0xb4, 0x57, 0x7f, 0x70, 0xbb, 0xc9, 0x7c, 0x36, 0x97, 0x60,
	0xcd, 0xc1, 0x34, 0xa0, 0x98, 0x23, 0x51, 0x03, 0x4a, 0x81, 0x39, 0x1d, 0xf9, 0xa6, 0xdd, 0xc8,
	0xed, 0x48, 0x7b, 0x35, 0x3c, 0x1b, 0xaa, 0xbf, 0xe5, 0x41, 0x66, 0x40, 0x74, 0x03, 0xaa, 0x03,
	0xdc, 0x32, 0x8e, 0x5a, 0xda, 0xa0, 0xdb, 0x33, 0x94, 0xff, 0x30, 0x43, 0x1f, 0xeb, 0xa4, 0x8f,
	0xf5, 0x7e, 0x0b, 0xeb, 0x8a, 0x84, 0xaa, 0x50, 0x9a, 0x0d, 0x72, 0x08, 0xa0, 0xa8, 0xf5, 0x9e,
	0x3c, 0xe9, 0x0e, 0x94, 0x3c, 0xaa, 0x03, 0x68, 0x1d, 0x5d, 0xfb, 0xa6, 0xdf, 0xeb, 0x1a, 0x03,
	0x45, 0x66, 0x2b, 0x9f, 0x75, 0xf5, 0x63, 0xa2, 0x75, 0x5a, 0xc6, 0x63, 0x5d, 0x29, 0xa0, 0x1a,
	0x94, 0x0d, 0xfd, 0x98, 0x30, 0xa3, 0x52, 0x44, 0x08, 0xea, 0x07, 0x5d, 0xa3, 0x7b, 0xd4, 0x21,
	0xcf, 0x34, 0xac, 0x1f, 0xe9, 0x03, 0xa5, 0x84, 0xb6, 0x60, 0xe3, 0x00, 0x0f, 0xb4, 0x0e, 0xc1,
	0xfa, 0xe1, 0x53, 0xfd, 0x68, 0x40, 0x1e, 0xb5, 0x06, 0x5a, 0x47, 0x29, 0xa3, 0x06, 0x6c, 0x62,
	0x7d, 0xf0, 0x14, 0x1b, 0x99, 0x99, 0x0a, 0x73, 0x63, 0xe8, 0x8f, 0x7b, 0x83, 0x6e, 0x6b, 0xa0,
	0x0b, 0xd7, 0x80, 0xfe, 0x07, 0x5b, 0x8b, 0x36, 0x82, 0xf5, 0xa3, 0x7e, 0xcf, 0x38, 0xd2, 0x95,
	0x2a, 0x5a, 0x87, 0x35, 0xac, 0x6b, 0xbd, 0x67, 0x3a, 0x7e, 0x41, 0xba, 0x46, 0x77, 0xa0, 0xd4,
	0xd0, 0x4d, 0x58, 0x9f, 0x9b, 0xe6, 0xc8, 0x35, 0x74, 0x0b, 0xd0, 0xdc, 0x7c, 0xa0, 0x33, 0x5a,
	0x87, 0x7d, 0x4d, 0xa9, 0x33, 0x96, 0x29, 0x38, 0x67, 0xc5, 0x26, 0x6e, 0x30, 0x81, 0xad, 0x76,
	0x9b, 0x18, 0xbd, 0xb6, 0xae, 0x28, 0x6c, 0xd4, 0xd6, 0xbf, 0x15, 0xa3, 0x75, 0x96, 0x0d, 0xac,
	0xb7, 0xda, 0x2f, 0xc8, 0x41, 0x0f, 0x13, 0x43, 0x41, 0x8c, 0x78, 0xeb, 0x31, 0xd6, 0x75, 0xf2,
	0xb4, 0xdf, 0x66, 0x3c, 0x0d, 0x65, 0x83, 0x2d, 0x99, 0x8f, 0x36, 0x19, 0xd3, 0x24, 0x43, 0xc2,
	0xa8, 0xdc, 0x54, 0xbf, 0x83, 0xf5, 0x54, 0x79, 0x90, 0x13, 0x33, 0xb6, 0x1c, 0xb4, 0x07, 0x05,
	0xfe, 0xd1, 0x90, 0x76, 0xf2, 0x7b, 0xd5, 0x07, 0xa8, 0xc9, 0xeb, 0xa8, 0x39, 0xb8, 0x04, 0x62,
	0x01, 0x40, 0xb7, 0xa1, 0x12, 0xbb, 0x63, 0x1a, 0xc5, 0xe6, 0x38, 0xe0, 0x25, 0x90, 0xc7, 0x97,
	0x06, 0xf5, 0x07, 0xd8, 0x0c, 0x69, 0x3c, 0x09, 0x3d, 0x12, 0xd2, 0x97, 0x13, 0x1a, 0xc5, 0x89,
	0xff, 0x8f, 0x2f, 0xfd, 0x4b, 0x7b, 0xd5, 0x07, 0x5b, 0xa2, 0xd2, 0x96, 0x78, 0xcc, 0x82, 0xdc,
	0x82, 0xa2, 0xed, 0x0e, 0x69, 0x14, 0xf3, 0x08, 0x15, 0x9c, 0x8c, 0xd4, 0x3f, 0x25, 0xa8, 0x06,
	0x21, 0x25, 0x41, 0x48, 0x03, 0x33, 0xa4, 0x08, 0x81, 0x7c, 0xee, 0xd2, 0x0b, 0xee, 0x55, 0xc6,
	0xfc, 0x1b, 0xed, 0xc2, 0x8d, 0x88, 0xc5, 0xf6, 0x2c, 0x4a, 0xbc, 0xc9, 0xf8, 0x84, 0x86, 0xdc,
	0x89, 0x8c, 0xeb, 0x33, 0xb3, 0xc1, 0xad, 0xe8, 0xff, 0x50, 0xe3, 0xd1, 0x48, 0x12, 0x2a, 0xcf,
	0x43, 0x55, 0xb9, 0xad, 0xcd, 0x4d, 0xa8, 0x7d, 0x45, 0xae, 0x1a, 0xf2, 0xeb, 0x25, 0x28, 0x29,
	0xd3, 0x23, 0xae, 0xe6, 0x0e, 0x40, 0x48, 0x83, 0x91, 0x6b, 0x99, 0xc4, 0xb5, 0x1b, 0x05, 0x4e,
	0xa6, 0x92, 0x58, 0xba, 0xb6, 0xfa, 0xb3, 0x04, 0xa5, 0x7f, 0x4a, 0xd0, 0x22, 0x15, 0x39, 0x4b,
	0xe5, 0x95, 0x04, 0x45, 0xcb, 0x1f, 0x8f, 0xdd, 0xf8, 0xdf, 0x66, 0x62, 0x00, 0x9c, 0x8c, 0x7c,
	0xeb, 0x8c, 0xb8, 0xde, 0xa9, 0xcf, 0xfd, 0xf1, 0x51, 0x12, 0x55, 0x90, 0xaa, 0x72, 0x5b, 0x12,
	0xf2, 0xce, 0x6c, 0x81, 0x63, 0x46, 0x4e, 0x72, 0x37, 0x55, 0xb8, 0xa5, 0x63, 0x46, 0x8e, 0x6a,
	0x03, 0x58, 0x0e, 0xb5, 0xce, 0x02, 0xdf, 0xf5, 0xe2, 0xab, 0x84, 0x48, 0x57, 0x0a, 0x59, 0x64,
	0x99, 0xcb, 0xb0, 0x44, 0x75, 0xc8, 0xb9, 0x76, 0xa2, 0x2e, 0xe7, 0xda, 0xea, 0xef, 0x79, 0xa8,
	0xb2, 0x4c, 0x11, 0xcb, 0x31, 0xbd, 0xe1, 0xd5, 0xdb, 0x59, 0x03, 0xc9, 0x49, 0x3c, 0x49, 0x0e,
	0xda, 0x05, 0xd9, 0x8a, 0x28, 0xcb, 0x10, 0x3b, 0x77, 0x1b, 0xa2, 0xa8, 0x52, 0x2e, 0x9a, 0x1a,
	0xe6, 0x00, 0xb4, 0x07, 0x72, 0xc0, 0x80, 0x32, 0x07, 0x6e, 0x2e, 0x03, 0xfb, 0x87, 0x98, 0x23,
	0x18, 0xf2, 0x25, 0x43, 0x16, 0x5e, 0x87, 0x64, 0x88, 0x8c, 0xba, 0x62, 0x56, 0xdd, 0x6d, 0xa8,
	0x44, 0xee, 0xd0, 0x33, 0xe3, 0x49, 0x48, 0x1b, 0x25, 0x91, 0xd1, 0xb9, 0x61, 0xf1, 0x22, 0x28,
	0x67, 0x2e, 0x82, 0xed, 0x2f, 0x41, 0xd2, 0xae, 0x9f, 0xe6, 0x4c, 0x1e, 0xb7, 0x6d, 0xc8, 0xf5,
	0x0f, 0xaf, 0xbf, 0x3c, 0x5b, 0x6e, 0xb9, 0xe5, 0x72, 0x9b, 0xed, 0x44, 0xfe, 0x72, 0x27, 0xd4,
	0x3f, 0x24, 0x28, 0x7b, 0xf4, 0x82, 0xf0, 0x6d, 0xb9, 0x6a, 0xab, 0x3e, 0x00, 0xf9, 0x9c, 0x65,
	0x32, 0xc7, 0x33, 0xb9, 0xbe, 0x94, 0x49, 0xcc, 0xa7, 0xd1, 0x47, 0x20, 0xff, 0x78, 0xb9, 0x87,
	0x0d, 0x01, 0x9b, 0x39, 0x6e, 0x3e, 0x8f, 0x68, 0xac, 0x7b, 0x71, 0x38, 0xc5, 0x1c, 0xb5, 0xa2,
	0xf0, 0xb7, 0x3f, 0x85, 0xca, 0x7c, 0x05, 0x52, 0x20, 0x7f, 0x46, 0xa7, 0x09, 0x27, 0xf6, 0x89,
	0x36, 0xa1, 0x70, 0x6e, 0x8e, 0x26, 0x34, 0xd1, 0x28, 0x06, 0x5f, 0xe4, 0x3e, 0x93, 0xd4, 0xe7,
	0x50, 0x3f, 0x75, 0x3d, 0x37, 0x72, 0xc8, 0xb9, 0x85, 0xe9, 0x72, 0x24, 0x29, 0xbb, 0xbd, 0x33,
	0xc5, 0xb9, 0x94, 0xe2, 0x0d, 0x28, 0x8c, 0xfc, 0x0b, 0xe2, 0xcc, 0xf2, 0x34, 0xf2, 0x2f, 0x3a,
	0xea, 0x31, 0x6c, 0x9c, 0x52, 0x96, 0xde, 0xc5, 0x3b, 0x3d, 0x9b, 0x75, 0x69, 0xd5, 0x21, 0xcf,
	0x1e, 0x1f, 0x75, 0x1f, 0xea, 0x1e, 0x1d, 0xfa, 0xb1, 0x6b, 0xc6, 0x54, 0xec, 0xc2, 0xeb, 0x29,
	0xab, 0x31, 0x6c, 0x2d, 0x2e, 0x20, 0x21, 0x8d, 0x02, 0xf6, 0x5e, 0x79, 0x1b, 0xb1, 0x35, 0x90,
	0xbc, 0x44, 0xa8, 0xe4, 0xb1, 0x97, 0x4d, 0xe8, 0x4f, 0x62, 0x1a, 0x46, 0x7c, 0x53, 0x6a, 0x78,
	0x36, 0x54, 0x9b, 0xb0, 0x16, 0x52, 0xcb, 0x3f, 0xa7, 0xe1, 0x94, 0xb8, 0x9e, 0xbb, 0x2a, 0xb1,
	0xea, 0x5f, 0x12, 0xac, 0xcf, 0x17, 0x5c, 0x97, 0xe0, 0x43, 0x28, 0x5a, 0xce, 0x59, 0x10, 0x47,
	0x49, 0xb5, 0xbd, 0x27, 0xca, 0x68, 0xc9, 0x4f, 0x53, 0xe3, 0x28, 0x51, 0x51, 0xc9, 0x12, 0xb4,
	0x03, 0xe2, 0x2e, 0xec, 0x50, 0x77, 0xe8, 0xc4, 0x89, 0xa6, 0xb4, 0x09, 0xbd, 0x0f, 0x6b, 0x23,
	0x33, 0x8a, 0x1f, 0xcd, 0x2e, 0x44, 0xae, 0xb1, 0x82, 0x17, 0x8d, 0xdb, 0x9f, 0x43, 0x35, 0xe5,
	0xfe, 0x8d, 0xca, 0xef, 0xeb, 0x94, 0x66, 0x5e, 0x2d, 0xfd, 0x43, 0x6d, 0x95, 0xe6, 0x85, 0xab,
	0x50, 0xfd, 0x45, 0x02, 0x94, 0x92, 0xcb, 0x5e, 0x11, 0xd7, 0xf0, 0x71, 0x1f, 0x80, 0x35, 0xcf,
	0x90, 0x92, 0xa5, 0x93, 0x9a, 0x7a, 0x29, 0xe0, 0x8a, 0x00, 0x1d, 0xd1, 0x18, 0xfd, 0x17, 0xca,
	0x02, 0xee, 0x89, 0x23, 0x5b, 0xc6, 0x25, 0x3e, 0xe3, 0xf1, 0x29, 0x6b, 0x1c, 0x8b, 0x29, 0x59,
	0x4c, 0x59, 0xe3, 0x98, 0x4d, 0xa9, 0xbb, 0x20, 0xf7, 0xd9, 0xa1, 0xba, 0x07, 0x79, 0x16, 0x48,
	0xbc, 0x93, 0xd6, 0xe6, 0x81, 0x78, 0x10, 0x36, 0xa3, 0x7e, 0x08, 0xb2, 0xc6, 0x80, 0x77, 0xd3,
	0xc0, 0xda, 0xec, 0x69, 0xcd, 0x7a, 0xab, 0xc0, 0x3d, 0x84, 0xb2, 0x69, 0xdb, 0xc4, 0xf3, 0xed,
	0x95, 0xb5, 0x91, 0xec, 0x83, 0xc8, 0x39, 0xfb, 0x54, 0xbf, 0x87, 0xb2, 0x4d, 0x47, 0x6f, 0xb7,
	0x18, 0xdd, 0x83, 0xaa, 0x28, 0x6d, 0xd1, 0x2b, 0xc5, 0xb5, 0x0b, 0xc2, 0xc4, 0x9b, 0xe5, 0x57,
	0x50, 0x0d, 0xa9, 0x69, 0x4f, 0xc9, 0xa9, 0x1f, 0x12, 0x6f, 0x55, 0x13, 0x4c, 0x02, 0xe4, 0x2f,
	0xd9, 0xfd, 0x9a, 0x83, 0xba, 0x39, 0x0c, 0x29, 0x25, 0x93, 0xc0, 0x66, 0x47, 0xd5, 0x63, 0xe7,
	0xef, 0x74, 0x64, 0x0e, 0x39, 0xbd, 0x32, 0xe6, 0xdf, 0x6f, 0xec, 0x17, 0xdd, 0x85, 0x14, 0xcb,
	0xa4, 0x82, 0x53, 0x16, 0x71, 0xa0, 0x0b, 0xbc, 0x15, 0x49, 0xde, 0xfc, 0xc8, 0x17, 0xb3, 0xcd,
	0xb7, 0x94, 0x6d, 0xbe, 0xe5, 0xeb, 0x36, 0xdf, 0xca, 0xb5, 0x9b, 0x2f, 0xac, 0x6a, 0xbe, 0xea,
	0x4f, 0x39, 0x28, 0xbf, 0xdb, 0xf4, 0x70, 0xf9, 0x72, 0x56, 0x7e, 0x21, 0x25, 0x7f, 0x0f, 0x64,
	0x93, 0xb1, 0x2b, 0xa6, 0xd9, 0x2d, 0xee, 0x14, 0xe6, 0x88, 0x79, 0x4f, 0x2b, 0xa5, 0x7b, 0xda,
	0x0c, 0x93, 0xed, 0x69, 0x6f, 0xdf, 0xb4, 0x8e, 0x61, 0x2d, 0x69, 0x5a, 0xc2, 0xf7, 0xbb, 0xea,
	0x59, 0x27, 0x45, 0xfe, 0xdb, 0xfb, 0xc9, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0x12, 0x4c,
	0xb7, 0x37, 0x0f, 0x00, 0x00,
}
