// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package pbft is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ConsensusMessage
	TransactionBatch
	PrePrepare
	Prepare
	Commit
	BlockInfo
	Checkpoint
	ViewChange
	PQset
	NewView
	FetchRequestBatch
	NegotiateView
	NegotiateViewResponse
	RecoveryInit
	RecoveryResponse
	RecoveryFetchPQC
	RecoveryReturnPQC
	Metadata
*/
package pbft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsensusMessage_Type int32

const (
	ConsensusMessage_TRANSACTION             ConsensusMessage_Type = 0
	ConsensusMessage_TRANSATION_BATCH        ConsensusMessage_Type = 1
	ConsensusMessage_PRE_PREPARE             ConsensusMessage_Type = 2
	ConsensusMessage_PREPARE                 ConsensusMessage_Type = 3
	ConsensusMessage_COMMIT                  ConsensusMessage_Type = 4
	ConsensusMessage_CHECKPOINT              ConsensusMessage_Type = 5
	ConsensusMessage_VIEW_CHANGE             ConsensusMessage_Type = 6
	ConsensusMessage_NEW_VIEW                ConsensusMessage_Type = 7
	ConsensusMessage_FRTCH_REQUEST_BATCH     ConsensusMessage_Type = 8
	ConsensusMessage_RETURN_REQUEST_BATCH    ConsensusMessage_Type = 9
	ConsensusMessage_NEGOTIATE_VIEW          ConsensusMessage_Type = 10
	ConsensusMessage_NEGOTIATE_VIEW_RESPONSE ConsensusMessage_Type = 11
	ConsensusMessage_RECOVERY_INIT           ConsensusMessage_Type = 12
	ConsensusMessage_RECOVERY_RESPONSE       ConsensusMessage_Type = 13
	ConsensusMessage_RECOVERY_FETCH_QPC      ConsensusMessage_Type = 14
	ConsensusMessage_RECOVERY_RETURN_QPC     ConsensusMessage_Type = 15
)

var ConsensusMessage_Type_name = map[int32]string{
	0:  "TRANSACTION",
	1:  "TRANSATION_BATCH",
	2:  "PRE_PREPARE",
	3:  "PREPARE",
	4:  "COMMIT",
	5:  "CHECKPOINT",
	6:  "VIEW_CHANGE",
	7:  "NEW_VIEW",
	8:  "FRTCH_REQUEST_BATCH",
	9:  "RETURN_REQUEST_BATCH",
	10: "NEGOTIATE_VIEW",
	11: "NEGOTIATE_VIEW_RESPONSE",
	12: "RECOVERY_INIT",
	13: "RECOVERY_RESPONSE",
	14: "RECOVERY_FETCH_QPC",
	15: "RECOVERY_RETURN_QPC",
}
var ConsensusMessage_Type_value = map[string]int32{
	"TRANSACTION":             0,
	"TRANSATION_BATCH":        1,
	"PRE_PREPARE":             2,
	"PREPARE":                 3,
	"COMMIT":                  4,
	"CHECKPOINT":              5,
	"VIEW_CHANGE":             6,
	"NEW_VIEW":                7,
	"FRTCH_REQUEST_BATCH":     8,
	"RETURN_REQUEST_BATCH":    9,
	"NEGOTIATE_VIEW":          10,
	"NEGOTIATE_VIEW_RESPONSE": 11,
	"RECOVERY_INIT":           12,
	"RECOVERY_RESPONSE":       13,
	"RECOVERY_FETCH_QPC":      14,
	"RECOVERY_RETURN_QPC":     15,
}

func (x ConsensusMessage_Type) String() string {
	return proto.EnumName(ConsensusMessage_Type_name, int32(x))
}
func (ConsensusMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ConsensusMessage struct {
	Type    ConsensusMessage_Type `protobuf:"varint,1,opt,name=type,enum=pbft.ConsensusMessage_Type" json:"type,omitempty"`
	Payload []byte                `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ConsensusMessage) Reset()                    { *m = ConsensusMessage{} }
func (m *ConsensusMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusMessage) ProtoMessage()               {}
func (*ConsensusMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TransactionBatch struct {
	Batch     []*types.Transaction `protobuf:"bytes,1,rep,name=batch" json:"batch,omitempty"`
	Timestamp int64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *TransactionBatch) Reset()                    { *m = TransactionBatch{} }
func (m *TransactionBatch) String() string            { return proto.CompactTextString(m) }
func (*TransactionBatch) ProtoMessage()               {}
func (*TransactionBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionBatch) GetBatch() []*types.Transaction {
	if m != nil {
		return m.Batch
	}
	return nil
}

type PrePrepare struct {
	View             uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber   uint64            `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest      string            `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	TransactionBatch *TransactionBatch `protobuf:"bytes,4,opt,name=transaction_batch,json=transactionBatch" json:"transaction_batch,omitempty"`
	ReplicaId        uint64            `protobuf:"varint,5,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *PrePrepare) Reset()                    { *m = PrePrepare{} }
func (m *PrePrepare) String() string            { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()               {}
func (*PrePrepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrePrepare) GetTransactionBatch() *TransactionBatch {
	if m != nil {
		return m.TransactionBatch
	}
	return nil
}

type Prepare struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Prepare) Reset()                    { *m = Prepare{} }
func (m *Prepare) String() string            { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()               {}
func (*Prepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Commit struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Commit) Reset()                    { *m = Commit{} }
func (m *Commit) String() string            { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()               {}
func (*Commit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type BlockInfo struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number,omitempty"`
	BlockHash   []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (m *BlockInfo) Reset()                    { *m = BlockInfo{} }
func (m *BlockInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()               {}
func (*BlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Checkpoint struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ViewChange struct {
	View      uint64           `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	H         uint64           `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Cset      []*ViewChange_C  `protobuf:"bytes,3,rep,name=cset" json:"cset,omitempty"`
	Pset      []*ViewChange_PQ `protobuf:"bytes,4,rep,name=pset" json:"pset,omitempty"`
	Qset      []*ViewChange_PQ `protobuf:"bytes,5,rep,name=qset" json:"qset,omitempty"`
	ReplicaId uint64           `protobuf:"varint,6,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Signature []byte           `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *ViewChange) Reset()                    { *m = ViewChange{} }
func (m *ViewChange) String() string            { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()               {}
func (*ViewChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ViewChange) GetCset() []*ViewChange_C {
	if m != nil {
		return m.Cset
	}
	return nil
}

func (m *ViewChange) GetPset() []*ViewChange_PQ {
	if m != nil {
		return m.Pset
	}
	return nil
}

func (m *ViewChange) GetQset() []*ViewChange_PQ {
	if m != nil {
		return m.Qset
	}
	return nil
}

// This message should go away and become a checkpoint once replica_id is removed
type ViewChange_C struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *ViewChange_C) Reset()                    { *m = ViewChange_C{} }
func (m *ViewChange_C) String() string            { return proto.CompactTextString(m) }
func (*ViewChange_C) ProtoMessage()               {}
func (*ViewChange_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type ViewChange_PQ struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,2,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	View           uint64 `protobuf:"varint,3,opt,name=view" json:"view,omitempty"`
}

func (m *ViewChange_PQ) Reset()                    { *m = ViewChange_PQ{} }
func (m *ViewChange_PQ) String() string            { return proto.CompactTextString(m) }
func (*ViewChange_PQ) ProtoMessage()               {}
func (*ViewChange_PQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

type PQset struct {
	Set []*ViewChange_PQ `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (m *PQset) Reset()                    { *m = PQset{} }
func (m *PQset) String() string            { return proto.CompactTextString(m) }
func (*PQset) ProtoMessage()               {}
func (*PQset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PQset) GetSet() []*ViewChange_PQ {
	if m != nil {
		return m.Set
	}
	return nil
}

type NewView struct {
	View      uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	Vset      []*ViewChange     `protobuf:"bytes,2,rep,name=vset" json:"vset,omitempty"`
	Xset      map[uint64]string `protobuf:"bytes,3,rep,name=xset" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReplicaId uint64            `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NewView) Reset()                    { *m = NewView{} }
func (m *NewView) String() string            { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()               {}
func (*NewView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *NewView) GetVset() []*ViewChange {
	if m != nil {
		return m.Vset
	}
	return nil
}

func (m *NewView) GetXset() map[uint64]string {
	if m != nil {
		return m.Xset
	}
	return nil
}

type FetchRequestBatch struct {
	BatchDigest string `protobuf:"bytes,1,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId   uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *FetchRequestBatch) Reset()                    { *m = FetchRequestBatch{} }
func (m *FetchRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*FetchRequestBatch) ProtoMessage()               {}
func (*FetchRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type NegotiateView struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NegotiateView) Reset()                    { *m = NegotiateView{} }
func (m *NegotiateView) String() string            { return proto.CompactTextString(m) }
func (*NegotiateView) ProtoMessage()               {}
func (*NegotiateView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type NegotiateViewResponse struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
}

func (m *NegotiateViewResponse) Reset()                    { *m = NegotiateViewResponse{} }
func (m *NegotiateViewResponse) String() string            { return proto.CompactTextString(m) }
func (*NegotiateViewResponse) ProtoMessage()               {}
func (*NegotiateViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type RecoveryInit struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *RecoveryInit) Reset()                    { *m = RecoveryInit{} }
func (m *RecoveryInit) String() string            { return proto.CompactTextString(m) }
func (*RecoveryInit) ProtoMessage()               {}
func (*RecoveryInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type RecoveryResponse struct {
	ReplicaId uint64            `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Chkpts    map[uint64]string `protobuf:"bytes,2,rep,name=chkpts" json:"chkpts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastExec  uint64            `protobuf:"varint,3,opt,name=lastExec" json:"lastExec,omitempty"`
}

func (m *RecoveryResponse) Reset()                    { *m = RecoveryResponse{} }
func (m *RecoveryResponse) String() string            { return proto.CompactTextString(m) }
func (*RecoveryResponse) ProtoMessage()               {}
func (*RecoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RecoveryResponse) GetChkpts() map[uint64]string {
	if m != nil {
		return m.Chkpts
	}
	return nil
}

type RecoveryFetchPQC struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	H         uint64 `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
}

func (m *RecoveryFetchPQC) Reset()                    { *m = RecoveryFetchPQC{} }
func (m *RecoveryFetchPQC) String() string            { return proto.CompactTextString(m) }
func (*RecoveryFetchPQC) ProtoMessage()               {}
func (*RecoveryFetchPQC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type RecoveryReturnPQC struct {
	ReplicaId uint64        `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	PrepreSet []*PrePrepare `protobuf:"bytes,2,rep,name=prepre_set,json=prepreSet" json:"prepre_set,omitempty"`
	PreSent   []bool        `protobuf:"varint,3,rep,packed,name=pre_sent,json=preSent" json:"pre_sent,omitempty"`
	CmtSent   []bool        `protobuf:"varint,4,rep,packed,name=cmt_sent,json=cmtSent" json:"cmt_sent,omitempty"`
}

func (m *RecoveryReturnPQC) Reset()                    { *m = RecoveryReturnPQC{} }
func (m *RecoveryReturnPQC) String() string            { return proto.CompactTextString(m) }
func (*RecoveryReturnPQC) ProtoMessage()               {}
func (*RecoveryReturnPQC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RecoveryReturnPQC) GetPrepreSet() []*PrePrepare {
	if m != nil {
		return m.PrepreSet
	}
	return nil
}

// consensus metadata
type Metadata struct {
	SeqNo uint64 `protobuf:"varint,1,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func init() {
	proto.RegisterType((*ConsensusMessage)(nil), "pbft.consensus_message")
	proto.RegisterType((*TransactionBatch)(nil), "pbft.transaction_batch")
	proto.RegisterType((*PrePrepare)(nil), "pbft.pre_prepare")
	proto.RegisterType((*Prepare)(nil), "pbft.prepare")
	proto.RegisterType((*Commit)(nil), "pbft.commit")
	proto.RegisterType((*BlockInfo)(nil), "pbft.block_info")
	proto.RegisterType((*Checkpoint)(nil), "pbft.checkpoint")
	proto.RegisterType((*ViewChange)(nil), "pbft.view_change")
	proto.RegisterType((*ViewChange_C)(nil), "pbft.view_change.C")
	proto.RegisterType((*ViewChange_PQ)(nil), "pbft.view_change.PQ")
	proto.RegisterType((*PQset)(nil), "pbft.PQset")
	proto.RegisterType((*NewView)(nil), "pbft.new_view")
	proto.RegisterType((*FetchRequestBatch)(nil), "pbft.fetch_request_batch")
	proto.RegisterType((*NegotiateView)(nil), "pbft.negotiate_view")
	proto.RegisterType((*NegotiateViewResponse)(nil), "pbft.negotiate_view_response")
	proto.RegisterType((*RecoveryInit)(nil), "pbft.recovery_init")
	proto.RegisterType((*RecoveryResponse)(nil), "pbft.recovery_response")
	proto.RegisterType((*RecoveryFetchPQC)(nil), "pbft.recovery_fetchPQC")
	proto.RegisterType((*RecoveryReturnPQC)(nil), "pbft.recovery_returnPQC")
	proto.RegisterType((*Metadata)(nil), "pbft.metadata")
	proto.RegisterEnum("pbft.ConsensusMessage_Type", ConsensusMessage_Type_name, ConsensusMessage_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1035 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x72, 0xdb, 0xd4,
	0x17, 0xff, 0x4b, 0x96, 0x13, 0xfb, 0x28, 0x71, 0xe4, 0x9b, 0xfc, 0x89, 0x31, 0xed, 0x4c, 0x11,
	0x03, 0xcd, 0x82, 0x51, 0x3a, 0x61, 0xc1, 0xe7, 0x02, 0x57, 0x55, 0x1b, 0x0f, 0x54, 0xb6, 0x6f,
	0xd4, 0x16, 0x86, 0x85, 0x46, 0x91, 0x6f, 0x62, 0x4d, 0x62, 0x49, 0x95, 0xae, 0x43, 0xfd, 0x04,
	0xb0, 0xe1, 0x09, 0x78, 0x00, 0x9e, 0x04, 0x36, 0xec, 0x78, 0x22, 0xee, 0x87, 0xec, 0xd8, 0xb2,
	0xa7, 0x0e, 0x1b, 0x58, 0x78, 0x46, 0xe7, 0x77, 0x7e, 0xe7, 0xdc, 0xf3, 0x79, 0xaf, 0xa1, 0x31,
	0x26, 0x79, 0x1e, 0x5c, 0x92, 0xdc, 0x4a, 0xb3, 0x84, 0x26, 0x48, 0x4b, 0xcf, 0x2f, 0x68, 0xfb,
	0xe1, 0x68, 0x9a, 0x92, 0x2c, 0x1c, 0x05, 0x51, 0x7c, 0x1c, 0x26, 0x19, 0x39, 0xa6, 0x4c, 0xce,
	0x8f, 0x69, 0x16, 0xc4, 0x79, 0x10, 0xd2, 0x28, 0x89, 0x25, 0xdd, 0xfc, 0xad, 0x02, 0xcd, 0x30,
	0x89, 0x73, 0x12, 0xe7, 0x93, 0xdc, 0x2f, 0x7c, 0xa1, 0x47, 0xa0, 0x71, 0x83, 0x96, 0xf2, 0x40,
	0x39, 0x6a, 0x9c, 0xdc, 0xb3, 0xb8, 0x4f, 0x6b, 0x85, 0x66, 0x79, 0x8c, 0x83, 0x05, 0x13, 0xb5,
	0x60, 0x3b, 0x0d, 0xa6, 0xd7, 0x49, 0x30, 0x6c, 0xa9, 0xcc, 0x68, 0x07, 0xcf, 0x44, 0xf3, 0x77,
	0x15, 0x34, 0x4e, 0x44, 0x7b, 0xa0, 0x7b, 0xb8, 0xe3, 0x9e, 0x75, 0x6c, 0xaf, 0xdb, 0x73, 0x8d,
	0xff, 0xa1, 0x03, 0x30, 0x24, 0xc0, 0x65, 0xff, 0x71, 0xc7, 0xb3, 0x4f, 0x0d, 0x85, 0xd3, 0xfa,
	0xd8, 0xf1, 0xd9, 0xaf, 0xdf, 0xc1, 0x8e, 0xa1, 0x22, 0x1d, 0xb6, 0x67, 0x42, 0x05, 0x01, 0x6c,
	0xd9, 0xbd, 0xe7, 0xcf, 0xbb, 0x9e, 0xa1, 0xa1, 0x06, 0x80, 0x7d, 0xea, 0xd8, 0xdf, 0xf4, 0x7b,
	0x5d, 0xd7, 0x33, 0xaa, 0xdc, 0xf2, 0x65, 0xd7, 0x79, 0xe5, 0xdb, 0xa7, 0x1d, 0xf7, 0x99, 0x63,
	0x6c, 0xa1, 0x1d, 0xa8, 0xb9, 0x4c, 0xe6, 0xa0, 0xb1, 0x8d, 0x0e, 0x61, 0xff, 0x29, 0x66, 0x67,
	0xf8, 0xd8, 0x19, 0xbc, 0x70, 0xce, 0xbc, 0xe2, 0xc4, 0x1a, 0x8b, 0xfd, 0x00, 0x3b, 0xde, 0x0b,
	0xec, 0x96, 0x34, 0x75, 0x84, 0xa0, 0xe1, 0x3a, 0xcf, 0x7a, 0x5e, 0xb7, 0xe3, 0x39, 0xd2, 0x0d,
	0xa0, 0xf7, 0xe0, 0x70, 0x19, 0x63, 0x56, 0x67, 0xfd, 0x9e, 0x7b, 0xe6, 0x18, 0x3a, 0x6a, 0xc2,
	0x2e, 0x76, 0xec, 0xde, 0x4b, 0x07, 0x7f, 0xef, 0x77, 0x5d, 0x16, 0xe5, 0x0e, 0xfa, 0x3f, 0x34,
	0xe7, 0xd0, 0x9c, 0xb9, 0x8b, 0xde, 0x01, 0x34, 0x87, 0x9f, 0x3a, 0x3c, 0xac, 0x41, 0xdf, 0x36,
	0x1a, 0x3c, 0xca, 0x05, 0xba, 0x88, 0x8a, 0x2b, 0xf6, 0xcc, 0x1f, 0xa0, 0xb9, 0xd0, 0x3e, 0xff,
	0x3c, 0xa0, 0xe1, 0x08, 0x1d, 0x41, 0x55, 0x7c, 0xb0, 0x4e, 0x55, 0x8e, 0xf4, 0x13, 0x64, 0x89,
	0x3e, 0x5b, 0xde, 0x2d, 0x11, 0x4b, 0x02, 0xba, 0x07, 0x75, 0x1a, 0xb1, 0xc6, 0xd1, 0x60, 0x9c,
	0x8a, 0x16, 0x55, 0xf0, 0x2d, 0x60, 0xfe, 0xa5, 0x80, 0x9e, 0x66, 0xc4, 0x67, 0xbf, 0x34, 0xc8,
	0x08, 0x4b, 0x5c, 0xbb, 0x89, 0xc8, 0x8f, 0x62, 0x00, 0x34, 0x2c, 0xbe, 0xd1, 0x43, 0xd8, 0xcb,
	0xc9, 0xeb, 0x09, 0x89, 0x43, 0xe2, 0xc7, 0x93, 0xf1, 0x39, 0xc9, 0x84, 0x1f, 0x0d, 0x37, 0x66,
	0xb0, 0x2b, 0x50, 0xf4, 0x3e, 0xec, 0x88, 0x33, 0xfd, 0x61, 0xc4, 0xe6, 0x92, 0xb6, 0x2a, 0x8c,
	0x55, 0xc7, 0xba, 0xc0, 0x9e, 0x08, 0x08, 0x3d, 0x59, 0x93, 0x4c, 0x4b, 0x63, 0x3c, 0xfd, 0xe4,
	0x50, 0x4e, 0xdb, 0x8a, 0x1a, 0x1b, 0x0b, 0xd0, 0x63, 0x91, 0xd3, 0x7d, 0x00, 0x16, 0xef, 0x75,
	0x14, 0x06, 0x7e, 0x34, 0x6c, 0x55, 0x45, 0x30, 0xf5, 0x02, 0xe9, 0x0e, 0xcd, 0x9f, 0x15, 0x36,
	0x94, 0xff, 0x52, 0x42, 0xcb, 0xa1, 0x68, 0xe5, 0x50, 0x7e, 0x52, 0x60, 0x2b, 0x4c, 0xc6, 0xe3,
	0x88, 0xfe, 0xd7, 0x91, 0xb8, 0x00, 0xe7, 0xd7, 0x49, 0x78, 0xe5, 0x47, 0xf1, 0x45, 0x22, 0xfc,
	0x09, 0xa9, 0x38, 0x55, 0x06, 0xa5, 0x0b, 0xac, 0x38, 0xf2, 0xfe, 0xcc, 0x60, 0x14, 0xe4, 0xa3,
	0x62, 0xb9, 0xeb, 0x02, 0x39, 0x65, 0x80, 0x39, 0x04, 0x08, 0x47, 0x24, 0xbc, 0x4a, 0x93, 0x28,
	0xa6, 0xeb, 0x12, 0x51, 0xd6, 0x26, 0xb2, 0x1c, 0xa5, 0x5a, 0x8a, 0x92, 0xad, 0xb6, 0xca, 0x60,
	0x99, 0x1d, 0xfb, 0x32, 0x7f, 0xa9, 0x80, 0xce, 0x2b, 0xe5, 0xb3, 0x2b, 0x2d, 0xbe, 0x5c, 0xdf,
	0xce, 0x1d, 0x50, 0x46, 0x85, 0x27, 0x65, 0xc4, 0x22, 0xd1, 0xc2, 0x9c, 0xf0, 0x0a, 0xf1, 0xc5,
	0xd8, 0x97, 0x43, 0xb5, 0xe0, 0xc2, 0xb2, 0xb1, 0x20, 0xb0, 0x15, 0xd2, 0x52, 0x4e, 0xd4, 0x04,
	0xf1, 0x60, 0x95, 0xd8, 0x1f, 0x60, 0xc1, 0xe0, 0xcc, 0xd7, 0x9c, 0x59, 0x7d, 0x1b, 0x93, 0x33,
	0x4a, 0xd9, 0x6d, 0x95, 0xb3, 0x63, 0xbb, 0x98, 0x47, 0x97, 0x71, 0x40, 0x27, 0x19, 0x69, 0x6d,
	0xcb, 0x8a, 0xce, 0x81, 0xf6, 0x57, 0xa0, 0xd8, 0x77, 0x2f, 0x64, 0xa9, 0x52, 0xed, 0x21, 0xa8,
	0xfd, 0xc1, 0xdd, 0xcd, 0xcb, 0x03, 0xa5, 0xae, 0x0e, 0xd4, 0xac, 0xd6, 0x95, 0xdb, 0x5a, 0x9b,
	0xc7, 0x50, 0xed, 0x0f, 0x78, 0xa6, 0x1f, 0x41, 0x85, 0x97, 0x44, 0x79, 0x4b, 0x49, 0x38, 0xc1,
	0xfc, 0x53, 0x81, 0x5a, 0xcc, 0x60, 0xd1, 0xa9, 0x75, 0xdd, 0xfb, 0x90, 0x61, 0xdc, 0x93, 0x2a,
	0x3c, 0x35, 0x57, 0x3c, 0x61, 0xa1, 0x46, 0x1f, 0x83, 0xf6, 0xe6, 0xb6, 0xad, 0x2d, 0x49, 0x9b,
	0x39, 0xb6, 0xbe, 0x63, 0x2a, 0x27, 0xa6, 0xd9, 0x14, 0x0b, 0xd6, 0x86, 0x5d, 0x68, 0x7f, 0x0a,
	0xf5, 0xb9, 0x05, 0x32, 0xa0, 0x72, 0x45, 0xa6, 0x45, 0x4c, 0xfc, 0x93, 0xbd, 0x4f, 0xd5, 0x9b,
	0xe0, 0x7a, 0x42, 0x8a, 0xa2, 0x48, 0xe1, 0x0b, 0xf5, 0x33, 0xc5, 0x7c, 0x05, 0xfb, 0x17, 0x84,
	0x57, 0x2d, 0xe3, 0xd5, 0xcc, 0x69, 0x71, 0x1b, 0x97, 0x8b, 0xa9, 0x6c, 0xda, 0xce, 0xf2, 0xdc,
	0xb3, 0xba, 0x36, 0x62, 0x72, 0x99, 0xd0, 0x28, 0xa0, 0x44, 0xd6, 0x6a, 0xd9, 0x40, 0x29, 0x1b,
	0x7c, 0x0b, 0x87, 0xcb, 0x06, 0x2c, 0xa4, 0x3c, 0xe5, 0x2f, 0xf5, 0x06, 0xcb, 0x79, 0x13, 0xd4,
	0x85, 0xb6, 0x5a, 0xb0, 0x9b, 0x91, 0x30, 0xb9, 0x21, 0xd9, 0x94, 0xdd, 0x0f, 0x11, 0xdd, 0x74,
	0xfa, 0x1f, 0x0a, 0x34, 0xe7, 0x06, 0x77, 0x3d, 0xf8, 0x4b, 0x76, 0x15, 0x8e, 0xae, 0x52, 0x9a,
	0x17, 0xbd, 0xfe, 0x40, 0x36, 0x71, 0xc5, 0x8f, 0x65, 0x0b, 0x96, 0xec, 0x67, 0x61, 0x82, 0xda,
	0x50, 0xbb, 0x0e, 0x72, 0xea, 0xbc, 0x21, 0x61, 0x31, 0x90, 0x73, 0xb9, 0xfd, 0x39, 0xe8, 0x0b,
	0x26, 0xff, 0xa8, 0xa1, 0x5f, 0x2f, 0xe4, 0x21, 0x3a, 0xdb, 0x1f, 0xd8, 0x9b, 0xf2, 0x58, 0xba,
	0x6f, 0xcc, 0x5f, 0x15, 0x40, 0x0b, 0x29, 0xb0, 0x4d, 0x8e, 0xef, 0xe0, 0xe3, 0x11, 0x00, 0x7f,
	0xa1, 0xd8, 0xcb, 0xbb, 0x32, 0xfb, 0x0b, 0xcf, 0x31, 0xae, 0x4b, 0xd2, 0x19, 0x1b, 0xe9, 0x77,
	0xa1, 0x26, 0xe9, 0xb1, 0x5c, 0x82, 0x1a, 0xde, 0x16, 0x9a, 0x58, 0xa8, 0xc2, 0x31, 0x95, 0x2a,
	0x4d, 0xaa, 0x98, 0xcc, 0x55, 0xe6, 0x03, 0xa8, 0x8d, 0x09, 0x0d, 0x86, 0x01, 0x0d, 0x78, 0x15,
	0xd8, 0x25, 0xe0, 0x26, 0x45, 0x34, 0x52, 0x38, 0xdf, 0x12, 0xff, 0x07, 0x3f, 0xf9, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x76, 0x95, 0x0a, 0xfc, 0x50, 0x0a, 0x00, 0x00,
}
