// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package pbft is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ConsensusMessage
	TransactionBatch
	PrePrepare
	Prepare
	Commit
	BlockInfo
	Checkpoint
	ViewChange
	PQset
	NewView
	FetchRequestBatch
	NegotiateView
	NegotiateViewResponse
	RecoveryInit
	RecoveryResponse
	NewNode
	AddNode
	RoutingTable
	ReadyForN
	UpdateN
*/
package pbft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsensusMessage_Type int32

const (
	ConsensusMessage_TRANSACTION             ConsensusMessage_Type = 0
	ConsensusMessage_TRANSATION_BATCH        ConsensusMessage_Type = 1
	ConsensusMessage_PRE_PREPARE             ConsensusMessage_Type = 2
	ConsensusMessage_PREPARE                 ConsensusMessage_Type = 3
	ConsensusMessage_COMMIT                  ConsensusMessage_Type = 4
	ConsensusMessage_CHECKPOINT              ConsensusMessage_Type = 5
	ConsensusMessage_VIEW_CHANGE             ConsensusMessage_Type = 6
	ConsensusMessage_NEW_VIEW                ConsensusMessage_Type = 7
	ConsensusMessage_FRTCH_REQUEST_BATCH     ConsensusMessage_Type = 8
	ConsensusMessage_RETURN_REQUEST_BATCH    ConsensusMessage_Type = 9
	ConsensusMessage_NEGOTIATE_VIEW          ConsensusMessage_Type = 10
	ConsensusMessage_NEGOTIATE_VIEW_RESPONSE ConsensusMessage_Type = 11
	ConsensusMessage_RECOVERY_INIT           ConsensusMessage_Type = 12
	ConsensusMessage_RECOVERY_RESPONSE       ConsensusMessage_Type = 13
	ConsensusMessage_NEW_NODE                ConsensusMessage_Type = 14
	ConsensusMessage_ADD_NODE                ConsensusMessage_Type = 15
	ConsensusMessage_ROUTING_TABLE           ConsensusMessage_Type = 16
	ConsensusMessage_READY_FOR_N             ConsensusMessage_Type = 17
	ConsensusMessage_UPDATE_N                ConsensusMessage_Type = 18
)

var ConsensusMessage_Type_name = map[int32]string{
	0:  "TRANSACTION",
	1:  "TRANSATION_BATCH",
	2:  "PRE_PREPARE",
	3:  "PREPARE",
	4:  "COMMIT",
	5:  "CHECKPOINT",
	6:  "VIEW_CHANGE",
	7:  "NEW_VIEW",
	8:  "FRTCH_REQUEST_BATCH",
	9:  "RETURN_REQUEST_BATCH",
	10: "NEGOTIATE_VIEW",
	11: "NEGOTIATE_VIEW_RESPONSE",
	12: "RECOVERY_INIT",
	13: "RECOVERY_RESPONSE",
	14: "NEW_NODE",
	15: "ADD_NODE",
	16: "ROUTING_TABLE",
	17: "READY_FOR_N",
	18: "UPDATE_N",
}
var ConsensusMessage_Type_value = map[string]int32{
	"TRANSACTION":             0,
	"TRANSATION_BATCH":        1,
	"PRE_PREPARE":             2,
	"PREPARE":                 3,
	"COMMIT":                  4,
	"CHECKPOINT":              5,
	"VIEW_CHANGE":             6,
	"NEW_VIEW":                7,
	"FRTCH_REQUEST_BATCH":     8,
	"RETURN_REQUEST_BATCH":    9,
	"NEGOTIATE_VIEW":          10,
	"NEGOTIATE_VIEW_RESPONSE": 11,
	"RECOVERY_INIT":           12,
	"RECOVERY_RESPONSE":       13,
	"NEW_NODE":                14,
	"ADD_NODE":                15,
	"ROUTING_TABLE":           16,
	"READY_FOR_N":             17,
	"UPDATE_N":                18,
}

func (x ConsensusMessage_Type) String() string {
	return proto.EnumName(ConsensusMessage_Type_name, int32(x))
}
func (ConsensusMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ConsensusMessage struct {
	Type    ConsensusMessage_Type `protobuf:"varint,1,opt,name=type,enum=pbft.ConsensusMessage_Type" json:"type,omitempty"`
	Payload []byte                `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *ConsensusMessage) Reset()                    { *m = ConsensusMessage{} }
func (m *ConsensusMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusMessage) ProtoMessage()               {}
func (*ConsensusMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TransactionBatch struct {
	Batch     []*types.Transaction `protobuf:"bytes,1,rep,name=batch" json:"batch,omitempty"`
	Timestamp int64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *TransactionBatch) Reset()                    { *m = TransactionBatch{} }
func (m *TransactionBatch) String() string            { return proto.CompactTextString(m) }
func (*TransactionBatch) ProtoMessage()               {}
func (*TransactionBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionBatch) GetBatch() []*types.Transaction {
	if m != nil {
		return m.Batch
	}
	return nil
}

type PrePrepare struct {
	View             uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber   uint64            `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest      string            `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	TransactionBatch *TransactionBatch `protobuf:"bytes,4,opt,name=transaction_batch,json=transactionBatch" json:"transaction_batch,omitempty"`
	ReplicaId        uint64            `protobuf:"varint,5,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *PrePrepare) Reset()                    { *m = PrePrepare{} }
func (m *PrePrepare) String() string            { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()               {}
func (*PrePrepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrePrepare) GetTransactionBatch() *TransactionBatch {
	if m != nil {
		return m.TransactionBatch
	}
	return nil
}

type Prepare struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Prepare) Reset()                    { *m = Prepare{} }
func (m *Prepare) String() string            { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()               {}
func (*Prepare) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Commit struct {
	View           uint64 `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,3,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *Commit) Reset()                    { *m = Commit{} }
func (m *Commit) String() string            { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()               {}
func (*Commit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type BlockInfo struct {
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber" json:"block_number,omitempty"`
	BlockHash   []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (m *BlockInfo) Reset()                    { *m = BlockInfo{} }
func (m *BlockInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()               {}
func (*BlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Checkpoint struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	ReplicaId      uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ViewChange struct {
	View      uint64           `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	H         uint64           `protobuf:"varint,2,opt,name=h" json:"h,omitempty"`
	Cset      []*ViewChange_C  `protobuf:"bytes,3,rep,name=cset" json:"cset,omitempty"`
	Pset      []*ViewChange_PQ `protobuf:"bytes,4,rep,name=pset" json:"pset,omitempty"`
	Qset      []*ViewChange_PQ `protobuf:"bytes,5,rep,name=qset" json:"qset,omitempty"`
	ReplicaId uint64           `protobuf:"varint,6,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Signature []byte           `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *ViewChange) Reset()                    { *m = ViewChange{} }
func (m *ViewChange) String() string            { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()               {}
func (*ViewChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ViewChange) GetCset() []*ViewChange_C {
	if m != nil {
		return m.Cset
	}
	return nil
}

func (m *ViewChange) GetPset() []*ViewChange_PQ {
	if m != nil {
		return m.Pset
	}
	return nil
}

func (m *ViewChange) GetQset() []*ViewChange_PQ {
	if m != nil {
		return m.Qset
	}
	return nil
}

// This message should go away and become a checkpoint once replica_id is removed
type ViewChange_C struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	Id             string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *ViewChange_C) Reset()                    { *m = ViewChange_C{} }
func (m *ViewChange_C) String() string            { return proto.CompactTextString(m) }
func (*ViewChange_C) ProtoMessage()               {}
func (*ViewChange_C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type ViewChange_PQ struct {
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	BatchDigest    string `protobuf:"bytes,2,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	View           uint64 `protobuf:"varint,3,opt,name=view" json:"view,omitempty"`
}

func (m *ViewChange_PQ) Reset()                    { *m = ViewChange_PQ{} }
func (m *ViewChange_PQ) String() string            { return proto.CompactTextString(m) }
func (*ViewChange_PQ) ProtoMessage()               {}
func (*ViewChange_PQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

type PQset struct {
	Set []*ViewChange_PQ `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
}

func (m *PQset) Reset()                    { *m = PQset{} }
func (m *PQset) String() string            { return proto.CompactTextString(m) }
func (*PQset) ProtoMessage()               {}
func (*PQset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PQset) GetSet() []*ViewChange_PQ {
	if m != nil {
		return m.Set
	}
	return nil
}

type NewView struct {
	View      uint64            `protobuf:"varint,1,opt,name=view" json:"view,omitempty"`
	Vset      []*ViewChange     `protobuf:"bytes,2,rep,name=vset" json:"vset,omitempty"`
	Xset      map[uint64]string `protobuf:"bytes,3,rep,name=xset" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReplicaId uint64            `protobuf:"varint,4,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NewView) Reset()                    { *m = NewView{} }
func (m *NewView) String() string            { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()               {}
func (*NewView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *NewView) GetVset() []*ViewChange {
	if m != nil {
		return m.Vset
	}
	return nil
}

func (m *NewView) GetXset() map[uint64]string {
	if m != nil {
		return m.Xset
	}
	return nil
}

type FetchRequestBatch struct {
	BatchDigest string `protobuf:"bytes,1,opt,name=batch_digest,json=batchDigest" json:"batch_digest,omitempty"`
	ReplicaId   uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *FetchRequestBatch) Reset()                    { *m = FetchRequestBatch{} }
func (m *FetchRequestBatch) String() string            { return proto.CompactTextString(m) }
func (*FetchRequestBatch) ProtoMessage()               {}
func (*FetchRequestBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type NegotiateView struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *NegotiateView) Reset()                    { *m = NegotiateView{} }
func (m *NegotiateView) String() string            { return proto.CompactTextString(m) }
func (*NegotiateView) ProtoMessage()               {}
func (*NegotiateView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type NegotiateViewResponse struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	View      uint64 `protobuf:"varint,2,opt,name=view" json:"view,omitempty"`
}

func (m *NegotiateViewResponse) Reset()                    { *m = NegotiateViewResponse{} }
func (m *NegotiateViewResponse) String() string            { return proto.CompactTextString(m) }
func (*NegotiateViewResponse) ProtoMessage()               {}
func (*NegotiateViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type RecoveryInit struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
}

func (m *RecoveryInit) Reset()                    { *m = RecoveryInit{} }
func (m *RecoveryInit) String() string            { return proto.CompactTextString(m) }
func (*RecoveryInit) ProtoMessage()               {}
func (*RecoveryInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type RecoveryResponse struct {
	ReplicaId uint64       `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Blocks    []*BlockInfo `protobuf:"bytes,2,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *RecoveryResponse) Reset()                    { *m = RecoveryResponse{} }
func (m *RecoveryResponse) String() string            { return proto.CompactTextString(m) }
func (*RecoveryResponse) ProtoMessage()               {}
func (*RecoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RecoveryResponse) GetBlocks() []*BlockInfo {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type NewNode struct {
	ReplicaId   uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	TableDigest string `protobuf:"bytes,2,opt,name=table_digest,json=tableDigest" json:"table_digest,omitempty"`
}

func (m *NewNode) Reset()                    { *m = NewNode{} }
func (m *NewNode) String() string            { return proto.CompactTextString(m) }
func (*NewNode) ProtoMessage()               {}
func (*NewNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type AddNode struct {
	ReplicaId   uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	TableDigest string `protobuf:"bytes,2,opt,name=table_digest,json=tableDigest" json:"table_digest,omitempty"`
}

func (m *AddNode) Reset()                    { *m = AddNode{} }
func (m *AddNode) String() string            { return proto.CompactTextString(m) }
func (*AddNode) ProtoMessage()               {}
func (*AddNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type RoutingTable struct {
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	Table     string `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
}

func (m *RoutingTable) Reset()                    { *m = RoutingTable{} }
func (m *RoutingTable) String() string            { return proto.CompactTextString(m) }
func (*RoutingTable) ProtoMessage()               {}
func (*RoutingTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ReadyForN struct {
	ReplicaId   uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	TableDigest string `protobuf:"bytes,2,opt,name=table_digest,json=tableDigest" json:"table_digest,omitempty"`
}

func (m *ReadyForN) Reset()                    { *m = ReadyForN{} }
func (m *ReadyForN) String() string            { return proto.CompactTextString(m) }
func (*ReadyForN) ProtoMessage()               {}
func (*ReadyForN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type UpdateN struct {
	ReplicaId    uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId" json:"replica_id,omitempty"`
	TabldeDigest string `protobuf:"bytes,2,opt,name=tablde_digest,json=tabldeDigest" json:"tablde_digest,omitempty"`
	N            uint64 `protobuf:"varint,3,opt,name=n" json:"n,omitempty"`
	SeqNo        uint64 `protobuf:"varint,4,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *UpdateN) Reset()                    { *m = UpdateN{} }
func (m *UpdateN) String() string            { return proto.CompactTextString(m) }
func (*UpdateN) ProtoMessage()               {}
func (*UpdateN) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func init() {
	proto.RegisterType((*ConsensusMessage)(nil), "pbft.consensus_message")
	proto.RegisterType((*TransactionBatch)(nil), "pbft.transaction_batch")
	proto.RegisterType((*PrePrepare)(nil), "pbft.pre_prepare")
	proto.RegisterType((*Prepare)(nil), "pbft.prepare")
	proto.RegisterType((*Commit)(nil), "pbft.commit")
	proto.RegisterType((*BlockInfo)(nil), "pbft.block_info")
	proto.RegisterType((*Checkpoint)(nil), "pbft.checkpoint")
	proto.RegisterType((*ViewChange)(nil), "pbft.view_change")
	proto.RegisterType((*ViewChange_C)(nil), "pbft.view_change.C")
	proto.RegisterType((*ViewChange_PQ)(nil), "pbft.view_change.PQ")
	proto.RegisterType((*PQset)(nil), "pbft.PQset")
	proto.RegisterType((*NewView)(nil), "pbft.new_view")
	proto.RegisterType((*FetchRequestBatch)(nil), "pbft.fetch_request_batch")
	proto.RegisterType((*NegotiateView)(nil), "pbft.negotiate_view")
	proto.RegisterType((*NegotiateViewResponse)(nil), "pbft.negotiate_view_response")
	proto.RegisterType((*RecoveryInit)(nil), "pbft.recovery_init")
	proto.RegisterType((*RecoveryResponse)(nil), "pbft.recovery_response")
	proto.RegisterType((*NewNode)(nil), "pbft.new_node")
	proto.RegisterType((*AddNode)(nil), "pbft.add_node")
	proto.RegisterType((*RoutingTable)(nil), "pbft.routing_table")
	proto.RegisterType((*ReadyForN)(nil), "pbft.ready_for_n")
	proto.RegisterType((*UpdateN)(nil), "pbft.update_n")
	proto.RegisterEnum("pbft.ConsensusMessage_Type", ConsensusMessage_Type_name, ConsensusMessage_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x56, 0x41, 0x6f, 0xe3, 0x54,
	0x10, 0xc6, 0x8e, 0x93, 0x36, 0xe3, 0x34, 0x75, 0x5e, 0x8b, 0x1a, 0x95, 0x5d, 0x09, 0x8c, 0x60,
	0x7b, 0x40, 0x29, 0x2a, 0x07, 0x10, 0xe2, 0x92, 0x26, 0xde, 0x36, 0x62, 0xd7, 0x4e, 0x5f, 0xdd,
	0x5d, 0x56, 0x20, 0x59, 0x8e, 0xfd, 0xda, 0x58, 0x6d, 0x6d, 0xaf, 0xed, 0x14, 0xf2, 0x0b, 0xe0,
	0xc2, 0xbf, 0xe2, 0xc6, 0x8d, 0x9f, 0xc0, 0x2f, 0x61, 0xde, 0xb3, 0x93, 0x36, 0x4e, 0xb4, 0xe9,
	0x61, 0xc5, 0x1e, 0x2a, 0x79, 0xbe, 0xf7, 0xcd, 0xbc, 0x99, 0x6f, 0x66, 0x5e, 0x0a, 0xcd, 0x5b,
	0x96, 0xa6, 0xee, 0x15, 0x4b, 0x3b, 0x71, 0x12, 0x65, 0x11, 0x51, 0xe2, 0xd1, 0x65, 0xb6, 0xff,
	0x6c, 0x3c, 0x8d, 0x59, 0xe2, 0x8d, 0xdd, 0x20, 0x3c, 0xf4, 0xa2, 0x84, 0x1d, 0x66, 0x68, 0xa7,
	0x87, 0x59, 0xe2, 0x86, 0xa9, 0xeb, 0x65, 0x41, 0x14, 0xe6, 0x74, 0xfd, 0xaf, 0x0a, 0xb4, 0xbc,
	0x28, 0x4c, 0x59, 0x98, 0x4e, 0x52, 0xa7, 0x88, 0x45, 0xbe, 0x06, 0x85, 0x3b, 0xb4, 0xa5, 0x4f,
	0xa5, 0x83, 0xe6, 0xd1, 0x93, 0x0e, 0x8f, 0xd9, 0x59, 0xa2, 0x75, 0x6c, 0xe4, 0x50, 0xc1, 0x24,
	0x6d, 0xd8, 0x88, 0xdd, 0xe9, 0x4d, 0xe4, 0xfa, 0x6d, 0x19, 0x9d, 0x1a, 0x74, 0x66, 0xea, 0xff,
	0xca, 0xa0, 0x70, 0x22, 0xd9, 0x06, 0xd5, 0xa6, 0x5d, 0xf3, 0xbc, 0xdb, 0xb3, 0x07, 0x96, 0xa9,
	0x7d, 0x44, 0x76, 0x41, 0xcb, 0x01, 0x6e, 0x3b, 0xc7, 0x5d, 0xbb, 0x77, 0xaa, 0x49, 0x9c, 0x36,
	0xa4, 0x86, 0x83, 0x7f, 0xc3, 0x2e, 0x35, 0x34, 0x99, 0xa8, 0xb0, 0x31, 0x33, 0x2a, 0x04, 0xa0,
	0xd6, 0xb3, 0x5e, 0xbe, 0x1c, 0xd8, 0x9a, 0x42, 0x9a, 0x00, 0xbd, 0x53, 0xa3, 0xf7, 0xe3, 0xd0,
	0x1a, 0x98, 0xb6, 0x56, 0xe5, 0x9e, 0xaf, 0x06, 0xc6, 0x6b, 0xa7, 0x77, 0xda, 0x35, 0x4f, 0x0c,
	0xad, 0x46, 0x1a, 0xb0, 0x69, 0xa2, 0xcd, 0x41, 0x6d, 0x83, 0xec, 0xc1, 0xce, 0x73, 0x8a, 0x77,
	0x38, 0xd4, 0x38, 0xbb, 0x30, 0xce, 0xed, 0xe2, 0xc6, 0x4d, 0xcc, 0x7d, 0x97, 0x1a, 0xf6, 0x05,
	0x35, 0x4b, 0x27, 0x75, 0x42, 0xa0, 0x69, 0x1a, 0x27, 0x96, 0x3d, 0xe8, 0xda, 0x46, 0x1e, 0x06,
	0xc8, 0x27, 0xb0, 0xb7, 0x88, 0xa1, 0xd7, 0xf9, 0xd0, 0x32, 0xcf, 0x0d, 0x4d, 0x25, 0x2d, 0xd8,
	0xa2, 0x46, 0xcf, 0x7a, 0x65, 0xd0, 0x37, 0xce, 0xc0, 0xc4, 0x2c, 0x1b, 0xe4, 0x63, 0x68, 0xcd,
	0xa1, 0x39, 0x73, 0x6b, 0x96, 0x9b, 0x69, 0xf5, 0x0d, 0xad, 0xc9, 0xad, 0x6e, 0xbf, 0x9f, 0x5b,
	0xdb, 0x22, 0x8a, 0x75, 0x61, 0x0f, 0xcc, 0x13, 0xc7, 0xee, 0x1e, 0xbf, 0x30, 0x34, 0x8d, 0xd7,
	0x46, 0x8d, 0x6e, 0xff, 0x8d, 0xf3, 0xdc, 0xa2, 0x8e, 0xa9, 0xb5, 0xb8, 0xc7, 0xc5, 0xb0, 0xcf,
	0x73, 0x30, 0x35, 0xa2, 0xff, 0x0c, 0xad, 0x07, 0xbd, 0x75, 0x46, 0x6e, 0xe6, 0x8d, 0xc9, 0x01,
	0x54, 0xc5, 0x07, 0xb6, 0xb1, 0x72, 0xa0, 0x1e, 0x91, 0x8e, 0x18, 0x82, 0x8e, 0x7d, 0x4f, 0xa4,
	0x39, 0x81, 0x3c, 0x81, 0x7a, 0x16, 0x60, 0x57, 0x33, 0xf7, 0x36, 0x16, 0xfd, 0xab, 0xd0, 0x7b,
	0x40, 0xff, 0x47, 0x02, 0x35, 0x4e, 0x98, 0x83, 0x7f, 0xb1, 0x9b, 0x30, 0x54, 0x45, 0xb9, 0x0b,
	0xd8, 0xaf, 0x62, 0x3a, 0x14, 0x2a, 0xbe, 0xc9, 0x33, 0xd8, 0x4e, 0xd9, 0xdb, 0x09, 0x0b, 0x3d,
	0xe6, 0x84, 0x93, 0xdb, 0x11, 0x4b, 0x44, 0x1c, 0x85, 0x36, 0x67, 0xb0, 0x29, 0x50, 0xf2, 0x19,
	0x34, 0xc4, 0x9d, 0x8e, 0x1f, 0xe0, 0xd0, 0x66, 0xed, 0x0a, 0xb2, 0xea, 0x54, 0x15, 0x58, 0x5f,
	0x40, 0xa4, 0xbf, 0xa2, 0x98, 0xb6, 0x82, 0x3c, 0xf5, 0x68, 0x2f, 0x1f, 0xc5, 0xa5, 0x63, 0xaa,
	0x3d, 0x80, 0x8e, 0x45, 0x4d, 0x4f, 0x01, 0x30, 0xdf, 0x9b, 0xc0, 0x73, 0x9d, 0xc0, 0x6f, 0x57,
	0x45, 0x32, 0xf5, 0x02, 0x19, 0xf8, 0xfa, 0x1f, 0x12, 0x4e, 0xec, 0xff, 0x54, 0xd0, 0x62, 0x2a,
	0x4a, 0x39, 0x95, 0xdf, 0x25, 0xa8, 0x79, 0xd1, 0xed, 0x6d, 0x90, 0x7d, 0xe8, 0x4c, 0x4c, 0x80,
	0xd1, 0x4d, 0xe4, 0x5d, 0x3b, 0x41, 0x78, 0x19, 0x89, 0x78, 0xc2, 0x2a, 0x6e, 0xcd, 0x93, 0x52,
	0x05, 0x56, 0x5c, 0xf9, 0x74, 0xe6, 0x30, 0x76, 0xd3, 0x71, 0xb1, 0xf9, 0x75, 0x81, 0x9c, 0x22,
	0xa0, 0xfb, 0x00, 0xde, 0x98, 0x79, 0xd7, 0x71, 0x14, 0x84, 0xd9, 0xaa, 0x42, 0xa4, 0x95, 0x85,
	0x2c, 0x66, 0x29, 0x97, 0xb2, 0xc4, 0xbd, 0x97, 0x11, 0xce, 0xab, 0xc3, 0x2f, 0xfd, 0xcf, 0x0a,
	0xa8, 0x5c, 0x29, 0x07, 0xdf, 0xbb, 0xf0, 0x6a, 0x75, 0x3b, 0x1b, 0x20, 0x8d, 0x8b, 0x48, 0xd2,
	0x18, 0x33, 0x51, 0xbc, 0x94, 0x71, 0x85, 0xf8, 0x62, 0xec, 0xe4, 0x43, 0xf5, 0x20, 0x44, 0xa7,
	0x47, 0x05, 0x01, 0x57, 0x48, 0x89, 0x39, 0x51, 0x11, 0xc4, 0xdd, 0x65, 0xe2, 0xf0, 0x8c, 0x0a,
	0x06, 0x67, 0xbe, 0xe5, 0xcc, 0xea, 0xbb, 0x98, 0x9c, 0x51, 0xaa, 0xae, 0x56, 0xae, 0x0e, 0x77,
	0x31, 0x0d, 0xae, 0x42, 0x37, 0x9b, 0x24, 0xac, 0xbd, 0x91, 0x2b, 0x3a, 0x07, 0xf6, 0x7f, 0x00,
	0xa9, 0xf7, 0x78, 0x21, 0x4b, 0x4a, 0xed, 0xfb, 0x20, 0x0f, 0xcf, 0x1e, 0xef, 0x5e, 0x1e, 0x28,
	0x79, 0x79, 0xa0, 0x66, 0x5a, 0x57, 0xee, 0xb5, 0xd6, 0x0f, 0xa1, 0x3a, 0x3c, 0xe3, 0x95, 0x7e,
	0x09, 0x15, 0x2e, 0x89, 0xf4, 0x0e, 0x49, 0x38, 0x41, 0xff, 0x5b, 0x82, 0xcd, 0x10, 0x61, 0xd1,
	0xa9, 0x55, 0xdd, 0xfb, 0x02, 0x31, 0x1e, 0x49, 0x16, 0x91, 0x5a, 0x4b, 0x91, 0xa8, 0x38, 0x26,
	0x5f, 0x81, 0xf2, 0xdb, 0x7d, 0x5b, 0xdb, 0x39, 0x6d, 0x16, 0xb8, 0xf3, 0x13, 0x1e, 0x19, 0x61,
	0x96, 0x4c, 0xa9, 0x60, 0xad, 0xd9, 0x85, 0xfd, 0x6f, 0xa1, 0x3e, 0xf7, 0x20, 0x1a, 0x54, 0xae,
	0xd9, 0xb4, 0xc8, 0x89, 0x7f, 0xe2, 0x8f, 0x57, 0xf5, 0xce, 0xbd, 0x99, 0xb0, 0x42, 0x94, 0xdc,
	0xf8, 0x5e, 0xfe, 0x4e, 0xd2, 0x5f, 0xc3, 0xce, 0x25, 0xe3, 0xaa, 0x25, 0x5c, 0xcd, 0x34, 0x2b,
	0x5e, 0xe3, 0xb2, 0x98, 0xd2, 0xba, 0xed, 0x2c, 0xcf, 0x3d, 0xea, 0xda, 0x0c, 0xd9, 0x55, 0x94,
	0x05, 0x6e, 0xc6, 0x72, 0xad, 0x16, 0x1d, 0xa4, 0xb2, 0xc3, 0x0b, 0xd8, 0x5b, 0x74, 0xc0, 0x94,
	0xd2, 0x98, 0xff, 0x8c, 0xaf, 0xf1, 0x9c, 0x37, 0x41, 0x7e, 0xd0, 0xd6, 0x0e, 0x6c, 0x25, 0xcc,
	0x8b, 0xee, 0x58, 0x32, 0xc5, 0xf7, 0x21, 0xc8, 0xd6, 0xdd, 0xfe, 0x0b, 0xb4, 0xe6, 0xfc, 0xc7,
	0xde, 0x7b, 0x00, 0x35, 0xf1, 0x7a, 0xa4, 0x45, 0xab, 0xb5, 0xbc, 0x87, 0xf7, 0x8f, 0x12, 0x2d,
	0xce, 0xb1, 0x36, 0x31, 0x32, 0x61, 0xe4, 0xaf, 0x0d, 0x8a, 0xca, 0x67, 0xee, 0xe8, 0x86, 0x95,
	0xc6, 0x58, 0x60, 0xb9, 0xf2, 0x3c, 0x9a, 0xeb, 0xfb, 0xef, 0x2b, 0x5a, 0x1f, 0x95, 0x8a, 0x26,
	0x59, 0x10, 0x5e, 0x39, 0x02, 0x5e, 0x17, 0x12, 0x67, 0x49, 0xf0, 0x66, 0xb3, 0x24, 0x0c, 0xdd,
	0x02, 0x35, 0x61, 0xae, 0x3f, 0x75, 0x2e, 0xa3, 0xc4, 0x09, 0xdf, 0x43, 0x5a, 0x09, 0x6c, 0x4e,
	0x62, 0x9f, 0xcf, 0xc2, 0xda, 0x68, 0x9f, 0xc3, 0x16, 0xf7, 0xf4, 0x4b, 0xe1, 0x1a, 0x39, 0x58,
	0x8c, 0x2b, 0xbe, 0xa9, 0x61, 0xb1, 0xf8, 0x52, 0xc8, 0x8b, 0xc0, 0xe7, 0xc3, 0x8c, 0x8a, 0x4d,
	0xca, 0x8d, 0x51, 0x4d, 0xfc, 0x9b, 0xf9, 0xcd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xf5,
	0xab, 0x61, 0xa7, 0x0a, 0x00, 0x00,
}
