###########################################################
#  _   _                        ____ _           _        #
# | | | |_   _ _ __   ___ _ __ / ___| |__   __ _(_)_ __   #
# | |_| | | | | '_ \ / _ \ '__| |   | '_ \ / _\` | | '_ \ #
# |  _  | |_| | |_) |  __/ |  | |___| | | | (_| | | | | | #
# |_| |_|\__, | .__/ \___|_|   \____|_| |_|\__,_|_|_| |_| #
#        |___/|_|                                         #
###########################################################

global:
###########################
# configs
############################
    account:
        keystoredir: "./keystore"
    logs:
        # dump the log file or not
        dumpfile: false
        logsdir: "./logs"
        # loglevel contains those levels:
        #    High   CRITICAL
        #           ERROR
        #           WARNING
        #           NOTICE
        #           INFO
        #    Low    DEBUG
        loglevel: "DEBUG"
