// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package peermessage is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	PeerAddress
*/
package peermessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MsgType message type during data transfer
type Message_MsgType int32

const (
	Message_HELLO     Message_MsgType = 0
	Message_RESPONSE  Message_MsgType = 1
	Message_CONSUS    Message_MsgType = 2
	Message_KEEPALIVE Message_MsgType = 3
	Message_SYNCMSG   Message_MsgType = 4
)

var Message_MsgType_name = map[int32]string{
	0: "HELLO",
	1: "RESPONSE",
	2: "CONSUS",
	3: "KEEPALIVE",
	4: "SYNCMSG",
}
var Message_MsgType_value = map[string]int32{
	"HELLO":     0,
	"RESPONSE":  1,
	"CONSUS":    2,
	"KEEPALIVE": 3,
	"SYNCMSG":   4,
}

func (x Message_MsgType) String() string {
	return proto.EnumName(Message_MsgType_name, int32(x))
}
func (Message_MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	// From the message source
	From         *PeerAddress    `protobuf:"bytes,1,opt,name=From,json=from" json:"From,omitempty"`
	MessageType  Message_MsgType `protobuf:"varint,2,opt,name=MessageType,json=messageType,enum=peermessage.Message_MsgType" json:"MessageType,omitempty"`
	Payload      []byte          `protobuf:"bytes,3,opt,name=Payload,json=payload,proto3" json:"Payload,omitempty"`
	MsgTimeStamp int64           `protobuf:"varint,15,opt,name=MsgTimeStamp,json=msgTimeStamp" json:"MsgTimeStamp,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetFrom() *PeerAddress {
	if m != nil {
		return m.From
	}
	return nil
}

// PeerAddress the peer address
type PeerAddress struct {
	Ip   string `protobuf:"bytes,1,opt,name=Ip,json=ip" json:"Ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,json=port" json:"Port,omitempty"`
}

func (m *PeerAddress) Reset()                    { *m = PeerAddress{} }
func (m *PeerAddress) String() string            { return proto.CompactTextString(m) }
func (*PeerAddress) ProtoMessage()               {}
func (*PeerAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Message)(nil), "peermessage.Message")
	proto.RegisterType((*PeerAddress)(nil), "peermessage.PeerAddress")
	proto.RegisterEnum("peermessage.Message_MsgType", Message_MsgType_name, Message_MsgType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Chat service

type ChatClient interface {
	// double arrow data tranfer
	Chat(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Chat(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/peermessage.Chat/Chat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chat service

type ChatServer interface {
	// double arrow data tranfer
	Chat(context.Context, *Message) (*Message, error)
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peermessage.Chat/Chat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Chat(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "peermessage.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Chat_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4b, 0xf3, 0x30,
	0x18, 0xc6, 0xb7, 0x2e, 0x5b, 0xbf, 0xbd, 0xe9, 0xf6, 0x95, 0x17, 0x0f, 0x41, 0x3c, 0x48, 0x4f,
	0x1e, 0x64, 0xe0, 0xf4, 0x28, 0xc2, 0x28, 0x51, 0xa7, 0xed, 0x56, 0x12, 0x15, 0x3c, 0x56, 0x1a,
	0xe7, 0xc0, 0xd0, 0xd0, 0xf6, 0xb2, 0xa3, 0xff, 0xb9, 0x59, 0x5b, 0xb1, 0xc2, 0x4e, 0xef, 0xf3,
	0x3e, 0x7d, 0x7e, 0x25, 0x4f, 0x02, 0x13, 0xad, 0xca, 0x32, 0xdd, 0xa8, 0x99, 0x29, 0xf2, 0x2a,
	0x47, 0x6a, 0x94, 0x2a, 0x5a, 0x2b, 0xf8, 0x72, 0xc0, 0x8d, 0x1b, 0x8d, 0xe7, 0x40, 0x6e, 0x8b,
	0x5c, 0xb3, 0xfe, 0x69, 0xff, 0x8c, 0xce, 0xd9, 0xac, 0x93, 0x9b, 0x25, 0x56, 0x2f, 0xb2, 0xac,
	0xb0, 0xab, 0x20, 0xef, 0x36, 0x85, 0x37, 0x40, 0x5b, 0xf0, 0x69, 0x67, 0x14, 0x73, 0x2c, 0x34,
	0x9d, 0x9f, 0xfc, 0x81, 0xe2, 0x9f, 0x59, 0x6e, 0xf6, 0x19, 0x41, 0xf5, 0x2f, 0x80, 0x0c, 0xdc,
	0x24, 0xdd, 0x7d, 0xe6, 0x69, 0xc6, 0x06, 0x96, 0xf5, 0x84, 0x6b, 0x9a, 0x15, 0x03, 0xf0, 0xf6,
	0xc4, 0x56, 0x2b, 0x59, 0xa5, 0xda, 0xb0, 0xff, 0xf6, 0xf3, 0x40, 0x78, 0xba, 0xe3, 0x05, 0x0f,
	0xf6, 0xd8, 0xcd, 0x5f, 0x71, 0x0c, 0xc3, 0x7b, 0x1e, 0x45, 0x6b, 0xbf, 0x87, 0x1e, 0xfc, 0x13,
	0x5c, 0x26, 0xeb, 0x95, 0xe4, 0x7e, 0x1f, 0x01, 0x46, 0xa1, 0x95, 0xcf, 0xd2, 0x77, 0x70, 0x02,
	0xe3, 0x47, 0xce, 0x93, 0x45, 0xb4, 0x7c, 0xe1, 0xfe, 0x00, 0x29, 0xb8, 0xf2, 0x75, 0x15, 0xc6,
	0xf2, 0xce, 0x27, 0xc1, 0x05, 0xd0, 0x4e, 0x3d, 0x9c, 0x82, 0xb3, 0x34, 0xf5, 0x25, 0x8c, 0x85,
	0xb3, 0x35, 0x88, 0x40, 0x92, 0xbc, 0xa8, 0xea, 0x86, 0x43, 0x41, 0x8c, 0xd5, 0xf3, 0x6b, 0x20,
	0xe1, 0x47, 0x5a, 0xe1, 0x55, 0x3b, 0x8f, 0x0e, 0xf5, 0x3e, 0x3e, 0xe8, 0x06, 0xbd, 0xb7, 0x51,
	0xfd, 0x10, 0x97, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x70, 0x77, 0x5a, 0x99, 0x01, 0x00,
	0x00,
}
