// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package event is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	AddNamespaceEvent
	DeleteNamespaceEvent
	AdminResponseEvent
	TestEvent
	ValidationEvent
	OpLogAck
	OpLogFetch
*/
package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/hyperchain/hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddNamespaceEvent struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *AddNamespaceEvent) Reset()                    { *m = AddNamespaceEvent{} }
func (m *AddNamespaceEvent) String() string            { return proto.CompactTextString(m) }
func (*AddNamespaceEvent) ProtoMessage()               {}
func (*AddNamespaceEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddNamespaceEvent) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DeleteNamespaceEvent struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *DeleteNamespaceEvent) Reset()                    { *m = DeleteNamespaceEvent{} }
func (m *DeleteNamespaceEvent) String() string            { return proto.CompactTextString(m) }
func (*DeleteNamespaceEvent) ProtoMessage()               {}
func (*DeleteNamespaceEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteNamespaceEvent) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type AdminResponseEvent struct {
	Ok  bool   `protobuf:"varint,1,opt,name=Ok" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *AdminResponseEvent) Reset()                    { *m = AdminResponseEvent{} }
func (m *AdminResponseEvent) String() string            { return proto.CompactTextString(m) }
func (*AdminResponseEvent) ProtoMessage()               {}
func (*AdminResponseEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AdminResponseEvent) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *AdminResponseEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TestEvent struct {
	Id  uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *TestEvent) Reset()                    { *m = TestEvent{} }
func (m *TestEvent) String() string            { return proto.CompactTextString(m) }
func (*TestEvent) ProtoMessage()               {}
func (*TestEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TestEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// receive new block event from node consensus event for consensus module
type ValidationEvent struct {
	Digest       string               `protobuf:"bytes,1,opt,name=Digest" json:"Digest,omitempty"`
	Transactions []*types.Transaction `protobuf:"bytes,2,rep,name=Transactions" json:"Transactions,omitempty"`
	SeqNo        uint64               `protobuf:"varint,3,opt,name=SeqNo" json:"SeqNo,omitempty"`
	View         uint64               `protobuf:"varint,4,opt,name=View" json:"View,omitempty"`
	IsPrimary    bool                 `protobuf:"varint,5,opt,name=IsPrimary" json:"IsPrimary,omitempty"`
	Timestamp    int64                `protobuf:"varint,6,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *ValidationEvent) Reset()                    { *m = ValidationEvent{} }
func (m *ValidationEvent) String() string            { return proto.CompactTextString(m) }
func (*ValidationEvent) ProtoMessage()               {}
func (*ValidationEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ValidationEvent) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *ValidationEvent) GetTransactions() []*types.Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *ValidationEvent) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *ValidationEvent) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ValidationEvent) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

func (m *ValidationEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type OpLogAck struct {
	ExecuteOk bool   `protobuf:"varint,1,opt,name=executeOk" json:"executeOk,omitempty"`
	SeqNo     uint64 `protobuf:"varint,2,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *OpLogAck) Reset()                    { *m = OpLogAck{} }
func (m *OpLogAck) String() string            { return proto.CompactTextString(m) }
func (*OpLogAck) ProtoMessage()               {}
func (*OpLogAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OpLogAck) GetExecuteOk() bool {
	if m != nil {
		return m.ExecuteOk
	}
	return false
}

func (m *OpLogAck) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

type OpLogFetch struct {
	LogID uint64 `protobuf:"varint,1,opt,name=logID" json:"logID,omitempty"`
}

func (m *OpLogFetch) Reset()                    { *m = OpLogFetch{} }
func (m *OpLogFetch) String() string            { return proto.CompactTextString(m) }
func (*OpLogFetch) ProtoMessage()               {}
func (*OpLogFetch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OpLogFetch) GetLogID() uint64 {
	if m != nil {
		return m.LogID
	}
	return 0
}

func init() {
	proto.RegisterType((*AddNamespaceEvent)(nil), "event.AddNamespaceEvent")
	proto.RegisterType((*DeleteNamespaceEvent)(nil), "event.DeleteNamespaceEvent")
	proto.RegisterType((*AdminResponseEvent)(nil), "event.AdminResponseEvent")
	proto.RegisterType((*TestEvent)(nil), "event.TestEvent")
	proto.RegisterType((*ValidationEvent)(nil), "event.ValidationEvent")
	proto.RegisterType((*OpLogAck)(nil), "event.OpLogAck")
	proto.RegisterType((*OpLogFetch)(nil), "event.OpLogFetch")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4b, 0x4b, 0x33, 0x31,
	0x18, 0x85, 0x99, 0x99, 0xb6, 0xb4, 0x6f, 0x3f, 0x3e, 0x35, 0x14, 0x19, 0xc4, 0x45, 0x99, 0x8d,
	0xdd, 0xd8, 0xe2, 0x85, 0x2e, 0x85, 0x42, 0x15, 0x0a, 0xda, 0xca, 0x58, 0xba, 0x8f, 0x99, 0x97,
	0x69, 0x68, 0x73, 0x71, 0x12, 0x2f, 0xfd, 0x85, 0xfe, 0x2d, 0x49, 0x66, 0xec, 0xe8, 0xd2, 0x5d,
	0xce, 0xc9, 0x73, 0xe0, 0xe4, 0x10, 0xe8, 0xe2, 0x1b, 0x4a, 0x3b, 0xd4, 0x85, 0xb2, 0x8a, 0x34,
	0xbd, 0x38, 0x39, 0x5b, 0xef, 0x34, 0x16, 0x6c, 0x4d, 0xb9, 0x1c, 0x31, 0x55, 0xe0, 0xc8, 0xee,
	0x34, 0x9a, 0x91, 0x2d, 0xa8, 0x34, 0x94, 0x59, 0xae, 0x64, 0xc9, 0x27, 0x17, 0x70, 0x34, 0xc9,
	0xb2, 0x39, 0x15, 0x68, 0x34, 0x65, 0x78, 0xeb, 0xd2, 0xe4, 0x14, 0x3a, 0xf2, 0xdb, 0x89, 0x83,
	0x7e, 0x30, 0xe8, 0xa4, 0xb5, 0x91, 0x5c, 0x43, 0x6f, 0x8a, 0x5b, 0xb4, 0xf8, 0xa7, 0xd4, 0x18,
	0xc8, 0x24, 0x13, 0x5c, 0xa6, 0x68, 0xb4, 0x92, 0xa6, 0xca, 0xfc, 0x87, 0x70, 0xb1, 0xf1, 0x70,
	0x3b, 0x0d, 0x17, 0x1b, 0x72, 0x08, 0xd1, 0x83, 0xc9, 0xe3, 0xd0, 0xa7, 0xdd, 0x31, 0x39, 0x87,
	0xce, 0x12, 0x8d, 0xdd, 0xe3, 0x3c, 0xf3, 0x78, 0x23, 0x0d, 0x79, 0xe6, 0x70, 0x51, 0xe3, 0xc2,
	0xe4, 0xc9, 0x67, 0x00, 0x07, 0x2b, 0xba, 0xe5, 0x19, 0x75, 0x8f, 0x2c, 0x53, 0xc7, 0xd0, 0x9a,
	0xf2, 0x1c, 0x8d, 0xad, 0x5a, 0x55, 0x8a, 0x8c, 0xe1, 0xdf, 0xb2, 0x1e, 0xc4, 0xc4, 0x61, 0x3f,
	0x1a, 0x74, 0x2f, 0xc9, 0xd0, 0x6f, 0x35, 0xfc, 0x71, 0x95, 0xfe, 0xe2, 0x48, 0x0f, 0x9a, 0x4f,
	0xf8, 0x32, 0x57, 0x71, 0xe4, 0x8b, 0x94, 0x82, 0x10, 0x68, 0xac, 0x38, 0xbe, 0xc7, 0x0d, 0x6f,
	0xfa, 0xb3, 0x9b, 0x64, 0x66, 0x1e, 0x0b, 0x2e, 0x68, 0xb1, 0x8b, 0x9b, 0xfe, 0x95, 0xb5, 0xe1,
	0x6e, 0x97, 0x5c, 0xa0, 0xb1, 0x54, 0xe8, 0xb8, 0xd5, 0x0f, 0x06, 0x51, 0x5a, 0x1b, 0xc9, 0x0d,
	0xb4, 0x17, 0xfa, 0x5e, 0xe5, 0x13, 0xb6, 0x71, 0x24, 0x7e, 0x20, 0x7b, 0xb5, 0xb8, 0x5f, 0xab,
	0x36, 0x5c, 0x1f, 0xe3, 0xfb, 0x84, 0x65, 0x1f, 0x2f, 0x92, 0x04, 0xc0, 0xe7, 0xef, 0xd0, 0xb2,
	0xb5, 0x63, 0xb6, 0x2a, 0x9f, 0x4d, 0xab, 0xf1, 0x4a, 0xf1, 0xdc, 0xf2, 0x9f, 0xe0, 0xea, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0x80, 0xb4, 0x6c, 0x43, 0x02, 0x00, 0x00,
}
