// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

/*
Package event is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	AddNamespaceEvent
	DeleteNamespaceEvent
	AdminResponseEvent
	TestEvent
	CommitBlockEvent
	RollbackEvent
	OpLogAck
	OpLogFetch
	CheckpointAck
*/
package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/hyperchain/hyperchain/core/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddNamespaceEvent struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *AddNamespaceEvent) Reset()                    { *m = AddNamespaceEvent{} }
func (m *AddNamespaceEvent) String() string            { return proto.CompactTextString(m) }
func (*AddNamespaceEvent) ProtoMessage()               {}
func (*AddNamespaceEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddNamespaceEvent) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DeleteNamespaceEvent struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *DeleteNamespaceEvent) Reset()                    { *m = DeleteNamespaceEvent{} }
func (m *DeleteNamespaceEvent) String() string            { return proto.CompactTextString(m) }
func (*DeleteNamespaceEvent) ProtoMessage()               {}
func (*DeleteNamespaceEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteNamespaceEvent) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type AdminResponseEvent struct {
	Ok  bool   `protobuf:"varint,1,opt,name=Ok" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *AdminResponseEvent) Reset()                    { *m = AdminResponseEvent{} }
func (m *AdminResponseEvent) String() string            { return proto.CompactTextString(m) }
func (*AdminResponseEvent) ProtoMessage()               {}
func (*AdminResponseEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AdminResponseEvent) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *AdminResponseEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TestEvent struct {
	Id  uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *TestEvent) Reset()                    { *m = TestEvent{} }
func (m *TestEvent) String() string            { return proto.CompactTextString(m) }
func (*TestEvent) ProtoMessage()               {}
func (*TestEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TestEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CommitBlockEvent struct {
	PreviousHash        string                            `protobuf:"bytes,1,opt,name=PreviousHash" json:"PreviousHash,omitempty"`
	Digest              string                            `protobuf:"bytes,2,opt,name=Digest" json:"Digest,omitempty"`
	Transactions        []*types.Transaction              `protobuf:"bytes,3,rep,name=Transactions" json:"Transactions,omitempty"`
	InvalidTransactions []*types.InvalidTransactionRecord `protobuf:"bytes,4,rep,name=InvalidTransactions" json:"InvalidTransactions,omitempty"`
	SeqNo               uint64                            `protobuf:"varint,5,opt,name=SeqNo" json:"SeqNo,omitempty"`
	View                uint64                            `protobuf:"varint,6,opt,name=View" json:"View,omitempty"`
	IsPrimary           bool                              `protobuf:"varint,7,opt,name=IsPrimary" json:"IsPrimary,omitempty"`
	Timestamp           int64                             `protobuf:"varint,8,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *CommitBlockEvent) Reset()                    { *m = CommitBlockEvent{} }
func (m *CommitBlockEvent) String() string            { return proto.CompactTextString(m) }
func (*CommitBlockEvent) ProtoMessage()               {}
func (*CommitBlockEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CommitBlockEvent) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

func (m *CommitBlockEvent) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *CommitBlockEvent) GetTransactions() []*types.Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *CommitBlockEvent) GetInvalidTransactions() []*types.InvalidTransactionRecord {
	if m != nil {
		return m.InvalidTransactions
	}
	return nil
}

func (m *CommitBlockEvent) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *CommitBlockEvent) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *CommitBlockEvent) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

func (m *CommitBlockEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RollbackEvent struct {
	SeqNo uint64 `protobuf:"varint,1,opt,name=SeqNo" json:"SeqNo,omitempty"`
	Lid   uint64 `protobuf:"varint,2,opt,name=Lid" json:"Lid,omitempty"`
}

func (m *RollbackEvent) Reset()                    { *m = RollbackEvent{} }
func (m *RollbackEvent) String() string            { return proto.CompactTextString(m) }
func (*RollbackEvent) ProtoMessage()               {}
func (*RollbackEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RollbackEvent) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *RollbackEvent) GetLid() uint64 {
	if m != nil {
		return m.Lid
	}
	return 0
}

type OpLogAck struct {
	ExecuteOk bool   `protobuf:"varint,1,opt,name=executeOk" json:"executeOk,omitempty"`
	SeqNo     uint64 `protobuf:"varint,2,opt,name=seqNo" json:"seqNo,omitempty"`
}

func (m *OpLogAck) Reset()                    { *m = OpLogAck{} }
func (m *OpLogAck) String() string            { return proto.CompactTextString(m) }
func (*OpLogAck) ProtoMessage()               {}
func (*OpLogAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OpLogAck) GetExecuteOk() bool {
	if m != nil {
		return m.ExecuteOk
	}
	return false
}

func (m *OpLogAck) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

type OpLogFetch struct {
	LogID uint64 `protobuf:"varint,1,opt,name=logID" json:"logID,omitempty"`
}

func (m *OpLogFetch) Reset()                    { *m = OpLogFetch{} }
func (m *OpLogFetch) String() string            { return proto.CompactTextString(m) }
func (*OpLogFetch) ProtoMessage()               {}
func (*OpLogFetch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OpLogFetch) GetLogID() uint64 {
	if m != nil {
		return m.LogID
	}
	return 0
}

type CheckpointAck struct {
	IsStableCkpt bool   `protobuf:"varint,1,opt,name=isStableCkpt" json:"isStableCkpt,omitempty"`
	Cid          uint64 `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
}

func (m *CheckpointAck) Reset()                    { *m = CheckpointAck{} }
func (m *CheckpointAck) String() string            { return proto.CompactTextString(m) }
func (*CheckpointAck) ProtoMessage()               {}
func (*CheckpointAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CheckpointAck) GetIsStableCkpt() bool {
	if m != nil {
		return m.IsStableCkpt
	}
	return false
}

func (m *CheckpointAck) GetCid() uint64 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func init() {
	proto.RegisterType((*AddNamespaceEvent)(nil), "event.AddNamespaceEvent")
	proto.RegisterType((*DeleteNamespaceEvent)(nil), "event.DeleteNamespaceEvent")
	proto.RegisterType((*AdminResponseEvent)(nil), "event.AdminResponseEvent")
	proto.RegisterType((*TestEvent)(nil), "event.TestEvent")
	proto.RegisterType((*CommitBlockEvent)(nil), "event.CommitBlockEvent")
	proto.RegisterType((*RollbackEvent)(nil), "event.RollbackEvent")
	proto.RegisterType((*OpLogAck)(nil), "event.OpLogAck")
	proto.RegisterType((*OpLogFetch)(nil), "event.OpLogFetch")
	proto.RegisterType((*CheckpointAck)(nil), "event.CheckpointAck")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4b, 0x8f, 0xd3, 0x30,
	0x10, 0x56, 0x9f, 0xb4, 0xb3, 0x5d, 0x54, 0xcc, 0x0a, 0x45, 0x08, 0x89, 0xca, 0xa7, 0x5e, 0x68,
	0xc5, 0x43, 0xcb, 0x09, 0xa4, 0xd2, 0x2e, 0xa2, 0xd2, 0xb2, 0x5d, 0xbc, 0x15, 0x77, 0xd7, 0x19,
	0x25, 0x56, 0xe2, 0x38, 0xc4, 0x6e, 0xa1, 0xbf, 0x8e, 0xbf, 0x86, 0xec, 0xa4, 0x4d, 0x2b, 0xb8,
	0x70, 0x9b, 0xf9, 0xf2, 0x3d, 0x46, 0x9f, 0x03, 0x17, 0xb8, 0xc3, 0xcc, 0x4e, 0xf2, 0x42, 0x5b,
	0x4d, 0x3a, 0x7e, 0x79, 0xfe, 0x21, 0x92, 0x36, 0xde, 0x6e, 0x26, 0x42, 0xab, 0x69, 0xbc, 0xcf,
	0xb1, 0x10, 0x31, 0x97, 0xd9, 0xe9, 0x28, 0x74, 0x81, 0x53, 0xbb, 0xcf, 0xd1, 0x4c, 0x6d, 0xc1,
	0x33, 0xc3, 0x85, 0x95, 0x3a, 0x2b, 0x5d, 0xe8, 0x6b, 0x78, 0x32, 0x0b, 0xc3, 0x3b, 0xae, 0xd0,
	0xe4, 0x5c, 0xe0, 0x8d, 0xf3, 0x24, 0x2f, 0xa0, 0x9f, 0x1d, 0x90, 0xa0, 0x31, 0x6a, 0x8c, 0xfb,
	0xac, 0x06, 0xe8, 0x3b, 0xb8, 0x5a, 0x60, 0x8a, 0x16, 0xff, 0x4b, 0x75, 0x0d, 0x64, 0x16, 0x2a,
	0x99, 0x31, 0x34, 0xb9, 0xce, 0x4c, 0xa5, 0x79, 0x0c, 0xcd, 0x55, 0xe2, 0xc9, 0x3d, 0xd6, 0x5c,
	0x25, 0x64, 0x08, 0xad, 0xaf, 0x26, 0x0a, 0x9a, 0x5e, 0xed, 0x46, 0xfa, 0x0a, 0xfa, 0x6b, 0x34,
	0xf6, 0x48, 0x97, 0xa1, 0xa7, 0xb7, 0x59, 0x53, 0x86, 0x8e, 0xae, 0x6a, 0xba, 0x32, 0x11, 0xfd,
	0xdd, 0x84, 0xe1, 0x5c, 0x2b, 0x25, 0xed, 0xa7, 0x54, 0x8b, 0xa4, 0x94, 0x51, 0x18, 0xdc, 0x17,
	0xb8, 0x93, 0x7a, 0x6b, 0xbe, 0x70, 0x13, 0x57, 0xc7, 0x9d, 0x61, 0xe4, 0x19, 0x74, 0x17, 0x32,
	0x42, 0x63, 0x2b, 0xb7, 0x6a, 0x23, 0xd7, 0x30, 0x58, 0xd7, 0xad, 0x99, 0xa0, 0x35, 0x6a, 0x8d,
	0x2f, 0xde, 0x90, 0x89, 0x2f, 0x74, 0x72, 0xf2, 0x89, 0x9d, 0xf1, 0xc8, 0x37, 0x78, 0xba, 0xcc,
	0x76, 0x3c, 0x95, 0xe1, 0x99, 0xbc, 0xed, 0xe5, 0x2f, 0x2b, 0xf9, 0xdf, 0x0c, 0x86, 0x42, 0x17,
	0x21, 0xfb, 0x97, 0x96, 0x5c, 0x41, 0xe7, 0x01, 0x7f, 0xdc, 0xe9, 0xa0, 0xe3, 0x0b, 0x28, 0x17,
	0x42, 0xa0, 0xfd, 0x5d, 0xe2, 0xcf, 0xa0, 0xeb, 0x41, 0x3f, 0xbb, 0xa7, 0x58, 0x9a, 0xfb, 0x42,
	0x2a, 0x5e, 0xec, 0x83, 0x47, 0xbe, 0xdd, 0x1a, 0x70, 0x5f, 0xd7, 0x52, 0xa1, 0xb1, 0x5c, 0xe5,
	0x41, 0x6f, 0xd4, 0x18, 0xb7, 0x58, 0x0d, 0xd0, 0xf7, 0x70, 0xc9, 0x74, 0x9a, 0x6e, 0xf8, 0xa1,
	0xbd, 0x63, 0x6c, 0xe3, 0x34, 0x76, 0x08, 0xad, 0x5b, 0x19, 0xfa, 0xb2, 0xda, 0xcc, 0x8d, 0xf4,
	0x23, 0xf4, 0x56, 0xf9, 0xad, 0x8e, 0x66, 0x22, 0x71, 0x11, 0xf8, 0x0b, 0xc5, 0xd6, 0xe2, 0xf1,
	0x79, 0x6b, 0xc0, 0x39, 0x1a, 0xef, 0x58, 0xaa, 0xcb, 0x85, 0x52, 0x00, 0xaf, 0xff, 0x8c, 0x56,
	0xc4, 0x8e, 0x93, 0xea, 0x68, 0xb9, 0x38, 0xa4, 0xfa, 0x85, 0xde, 0xc0, 0xe5, 0x3c, 0x46, 0x91,
	0xe4, 0x5a, 0x66, 0xd6, 0x05, 0x51, 0x18, 0x48, 0xf3, 0x60, 0xf9, 0x26, 0xc5, 0x79, 0x92, 0xdb,
	0x2a, 0xeb, 0x0c, 0x73, 0xa7, 0x8a, 0xfa, 0x54, 0x21, 0xc3, 0x4d, 0xd7, 0xff, 0xfc, 0x6f, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x80, 0x74, 0x25, 0x51, 0x03, 0x00, 0x00,
}
