# CA & CERT configs
#
# this config prepare  for ca & cert module
# *.toml config file is batter than *.yaml
# this config will never change by hyperchain
# please ensure the file not end with the `/` (slash)
#

[ecert]
ca = "config/cert/eca.ca"
cert = "config/cert/ecert.cert"
priv = "config/cert/ecert.priv"

[rcert]
# if you do not have rcert, leave this item blank
ca = "config/cert/rca.ca"
cert = "config/cert/rcert.cert"
priv = "config/cert/rcert.priv"

# the tls cert supply the transport layer security
[tlscert]
ca = "config/cert/tlscert/tlsca.ca"
cert = "config/cert/tlscert/tls_peer1.cert"
priv = "config/cert/tlscert/tls_peer1.priv"
serverhostoverride = "hyperchain.cn"

[check]
# check the ecert and rcert signature during the connect progress
checkercert = false

# check the tcert during the request process
checktcert  = false
