################################################################################
#Author:Frank
#This is configuration file for Hyperchain db config
################################################################################

dbConfig:
#dbType
########################
##Redis##SSDB##leveldb##
##0/1  ##0/1  ##0/1   ##
########################
# For example 110 means use Redis and SSDB
#
# 1234 means use leveldb with Bloom Filter
  dbType: 1234


#ssdb config
  ssdb:

  #the first port use for SSDB
    firstPort: 8011

  #the gap between the adjacent port
  #for example with gap 10 first port 8001 the second port is 8011 ,the thread port is 8021
    gap: 10

  #SSDB server number
    serverNumber: 2

  #pool size for connection
    poolSize: 10

  #timeout for connection in the pool  /second
    timeout: 60

  #Max retry times for a timeout operation
    maxConnectTimes: 15

  #element size for one-iteration
    iteratorSize: 100


#Redis config
  redis:

  #port for redis
    port: 8101

  #pool size for connection
    poolSize: 10

  #timeout for connection in the pool /second
    timeout: 60

  #Max retry times for a timeout operation
    maxConnectTimes: 15


  leveldbPath: "./build/leveldb"

  logStatus: true

  logPath: "./db.log"