###########################################################
#  _   _                        ____ _           _        #
# | | | |_   _ _ __   ___ _ __ / ___| |__   __ _(_)_ __   #
# | |_| | | | | '_ \ / _ \ '__| |   | '_ \ / _\` | | '_ \ #
# |  _  | |_| | |_) |  __/ |  | |___| | | | (_| | | | | | #
# |_| |_|\__, | .__/ \___|_|   \____|_| |_|\__,_|_|_| |_| #
#        |___/|_|                                         #
###########################################################

## Data storage path config
# Note: please DONOT add a slash `/` in the end of directory path.
# this relative path is relative to the hyperchain binary execute file path
# e.g: the file tree stauct like:
#


# node config

global:

##########################
# data storage config #
##########################
    account:
        keystoredir: "./build/keystore"
        keynodesdir: "./build/keynodes"

    database:
        dir: "./build/database/"

    version:
        blockversion: "1.0"
        transactionversion: "1.0"
###########################
# configs
# dbtype 110 means use redis cache and ssdb if you want use only leveldb put dbtypes as 001
# dblog calculate the time for processing the block and record the some debug information for db connection
############################
    configs:
        peers: "config/peerconfig.json"
        genesis: "config/genesis.json"
        membersrvc: "config/membersrvc.yaml"
        pbft: "config/pbft.yaml"
        license: "config/LICENSE"
        replicainfo:
            interval : 500s
            enable   : false
        ratelimit:
            enable   : true
            txRatePeak : 100
            txFillRate: 0.5ms
            contractRatePeak : 100
            contractFillRate: 0.5ms
        hmpublickey:
            "N": "14315727801779002117"
            Nsquare: "204940062494628260128356353732290481689"
            G: "90976693534933209671098397317966944738726332459523400324197777885595356310417"
        dbtype: 110
        dbLogConfig: ""

######################################################
# config log's level by module                       #
#                                                    #
# CRITICAL ERROR WARNING NOTICE INFO DEBUG           #
# high <------------- log level -------> low         #
#                                                    #
######################################################
    logs:
        # dump the log file or not
        dumpfile: true
        newLogFileInterval: 24h  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
                                # such as "300ms", "2h45m".

        logsdir: "./build/logs"
        # default loglevel for all modules which can be override by module level log setting
        loglevel: "NOTICE"

        module:
            #set log level by module
            p2p: "INFO"
            consensus: "NOTICE"
            core: "NOTICE"
            hyperdb: "NOTICE"