################################################################################
#Author:Frank
#This is configuration file for Hyperchain db config
################################################################################

dbConfig:

    ################################################################################
    # database name     #    database code
    #                   #
    # LEVEL_DB          #      0001
    # SUPER_LEVEL_DB    #      0010
    #                   #
    ################################################################################
    dbType: 0001

    #################################################################################
    #                                                                               #
    #    configurations for SuperLevelDB                                            #
    #                                                                               #
    #################################################################################
    sldb:
        dbpath: "./namespaces/ns2/data/sldb"
        index:
            dir: "./namespaces/ns2/data/sldb/index"
            bloombit: 100000000
            hashnum: 3
            dumpinterval: 24h
    ########################### end configurations of sldb ##########################


    #################################################################################
    #                                                                               #
    #    configurations for ssdb                                                    #
    #                                                                               #
    #################################################################################
    ssdb:

        #the first port use for SSDB
        firstPort: 8011

        #the gap between the adjacent port
        #for example with gap 10 first port 8001 the second port is 8011 ,the thread port is 8021
        gap: 10

        #SSDB server number
        serverNumber: 2

        #pool size for connection
        poolSize: 10

        #timeout for connection in the pool  /second
        timeout: 60

        #Max retry times for a timeout operation
        maxConnectTimes: 15

        #element size for one-iteration
        iteratorSize: 100

    ########################### end configurations of ssdb ##########################

    #################################################################################
    #                                                                               #
    #    configurations for Redis                                                   #
    #                                                                               #
    #################################################################################
    #Redis config
    redis:

        #port for redis
        port: 8101

        #pool size for connection
        poolSize: 10

        #timeout for connection in the pool /second
        timeout: 60

        #Max retry times for a timeout operation
        maxConnectTimes: 15

    ########################### end configurations of Redis #######################


    #db path of hyperchain. it's the parent dir of namespace dir
    leveldbPath: "./namespaces/ns2/data/leveldb"

    logStatus: true

    logPath: "./namespaces/ns2/data/db.log"