#used to generate namespace config files

namespace: global
maxpeernode: 4

node1:
    ip: 192.168.1.4
    node_id: 1
    is_origin: true
    is_vp: true
    grpc_port: 8001
    jsonrpc_port: 8081
    restful_port: 9001
    introducer_ip: 192.168.1.4
    introducer_port: 8001
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051

node2:
    ip: 192.168.1.5
    node_id: 2
    is_origin: true
    is_vp: true
    grpc_port: 8001
    jsonrpc_port: 8081
    restful_port: 9001
    introducer_ip: 192.168.1.4
    introducer_port: 8001
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051

node3:
    ip: 192.168.1.6
    node_id: 3
    is_origin: true
    is_vp: true
    grpc_port: 8001
    jsonrpc_port: 8081
    restful_port: 9001
    introducer_ip: 192.168.1.4
    introducer_port: 8001
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051

node4:
    ip: 192.168.1.7
    node_id: 4
    is_origin: true
    is_vp: true
    grpc_port: 8001
    jsonrpc_port: 8081
    restful_port: 9001
    introducer_ip: 192.168.1.4
    introducer_port: 8001
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051