#used to generate namespace config files

namespace: global
maxpeernode: 7

node1:
    ip: 127.0.0.1
    node_id: 1
    is_origin: true
    is_vp: true
    grpc_port: 8001
    jsonrpc_port: 8081
    restful_port: 9001
    websocket_port: 10001
    introducer_ip: 127.0.0.1
    introducer_port: 8001
    introducer_id: 1

node2:
    ip: 127.0.0.1
    node_id: 2
    is_origin: true
    is_vp: true
    grpc_port: 8002
    jsonrpc_port: 8082
    restful_port: 9002
    websocket_port: 10002
    introducer_ip: 127.0.0.1
    introducer_port: 8001
    introducer_id: 1

node3:
    ip: 127.0.0.1
    node_id: 3
    is_origin: true
    is_vp: true
    grpc_port: 8003
    jsonrpc_port: 8083
    restful_port: 9003
    websocket_port: 10003
    introducer_ip: 127.0.0.1
    introducer_port: 8001
    introducer_id: 1

node4:
    ip: 127.0.0.1
    node_id: 4
    is_origin: true
    is_vp: true
    grpc_port: 8004
    jsonrpc_port: 8084
    restful_port: 9004
    websocket_port: 10004
    introducer_ip: 127.0.0.1
    introducer_port: 8001
    introducer_id: 1

