#used to generate namespace config files

namespace: ns1
maxpeernode: 4

node2:
    ip: 172.16.0.12
    node_id: 1
    is_origin: true
    is_vp: true
    grpc_port: 8002
    jsonrpc_port: 8081
    restful_port: 9002
    introducer_ip: 172.16.0.12
    introducer_port: 8002
    introducer_id: 1

node3:
    ip: 172.16.0.13
    node_id: 2
    is_origin: true
    is_vp: true
    grpc_port: 8002
    jsonrpc_port: 8081
    restful_port: 9002
    introducer_ip: 172.16.0.12
    introducer_port: 8002
    introducer_id: 1

node4:
    ip: 172.16.0.14
    node_id: 3
    is_origin: true
    is_vp: true
    grpc_port: 8002
    jsonrpc_port: 8081
    restful_port: 9002
    introducer_ip: 172.16.0.12
    introducer_port: 8002
    introducer_id: 1

node1:
    ip: 172.16.0.11
    node_id: 4
    is_origin: true
    is_vp: true
    grpc_port: 8002
    jsonrpc_port: 8081
    restful_port: 9002
    introducer_ip: 172.16.0.12
    introducer_port: 8002
    introducer_id: 1