#used to generate namespace config files

namespace: ns2
maxpeernode: 4

node3:
    ip: 192.168.1.6
    node_id: 1
    is_origin: true
    is_vp: true
    grpc_port: 8003
    jsonrpc_port: 8081
    restful_port: 9003
    introducer_ip: 192.168.1.6
    introducer_port: 8003
    introducer_id: 1

node4:
    ip: 192.168.1.7
    node_id: 2
    is_origin: true
    is_vp: true
    grpc_port: 8003
    jsonrpc_port: 8081
    restful_port: 9003
    introducer_ip: 192.168.1.6
    introducer_port: 8003
    introducer_id: 1

node1:
    ip: 192.168.1.4
    node_id: 3
    is_origin: true
    is_vp: true
    grpc_port: 8003
    jsonrpc_port: 8081
    restful_port: 9003
    introducer_ip: 192.168.1.6
    introducer_port: 8003
    introducer_id: 1

node2:
    ip: 192.168.1.5
    node_id: 4
    is_origin: true
    is_vp: true
    grpc_port: 8003
    jsonrpc_port: 8081
    restful_port: 9003
    introducer_ip: 192.168.1.6
    introducer_port: 8003
    introducer_id: 1
