#used to generate namespace config files

namespace: ns3
maxpeernode: 4

node4:
    ip: 172.16.0.14
    node_id: 1
    is_origin: true
    is_vp: true
    grpc_port: 8004
    jsonrpc_port: 8081
    restful_port: 9004
    introducer_ip: 172.16.0.14
    introducer_port: 8004
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051

node1:
    ip: 172.16.0.11
    node_id: 2
    is_origin: true
    is_vp: true
    grpc_port: 8004
    jsonrpc_port: 8081
    restful_port: 9004
    introducer_ip: 172.16.0.14
    introducer_port: 8004
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051

node2:
    ip: 172.16.0.12
    node_id: 3
    is_origin: true
    is_vp: true
    grpc_port: 8004
    jsonrpc_port: 8081
    restful_port: 9004
    introducer_ip: 172.16.0.14
    introducer_port: 8004
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051

node3:
    ip: 172.16.0.13
    node_id: 4
    is_origin: true
    is_vp: true
    grpc_port: 8004
    jsonrpc_port: 8081
    restful_port: 9004
    introducer_ip: 172.16.0.14
    introducer_port: 8004
    introducer_id: 1
    jvm_port: 50081
    ledger_port: 50051