[self]
"N"=4
id=1
hostname="node1"
org=true
vp=true
rec=false
caconf= "namespaces/global/config/namespace.toml" #TODO: duplicate config with namespace.toml
[[nodes]]
id=1
hostname="node1"
[[nodes]]
id=2
hostname="node2"
[[nodes]]
id=3
hostname="node3"
[[nodes]]
id=4
hostname="node4"
