self:
  "N": 4
  id: 3
  hostname: node3
  org: true
  vp: true
  rec: false
  caconf: "namespaces/global/config/caconfig.yaml"
nodes:
  -
    id: 1
    hostname: node1
  -
    id: 2
    hostname: node2
  -
    id: 3
    hostname: node3
  -
    id: 4
    hostname: node4