// Code generated by protoc-gen-go.
// source: block.proto
// DO NOT EDIT!

/*
Package version1_2 is a generated protocol buffer package.

It is generated from these files:
	block.proto
	chain.proto
	receipt.proto
	replica.proto
	transaction.proto
	transaction_value.proto

It has these top-level messages:
	Block
	Blocks
	Chain
	Receipt
	ReplicaInfo
	Transaction
	InvalidTransactionRecord
	InvalidTransactionRecords
	TransactionMeta
	TransactionValue
*/
package version1_2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Version      []byte         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ParentHash   []byte         `protobuf:"bytes,2,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	BlockHash    []byte         `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,4,rep,name=transactions" json:"transactions,omitempty"`
	Timestamp    int64          `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	MerkleRoot   []byte         `protobuf:"bytes,6,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	TxRoot       []byte         `protobuf:"bytes,7,opt,name=txRoot,proto3" json:"txRoot,omitempty"`
	ReceiptRoot  []byte         `protobuf:"bytes,8,opt,name=receiptRoot,proto3" json:"receiptRoot,omitempty"`
	Number       uint64         `protobuf:"varint,9,opt,name=number" json:"number,omitempty"`
	WriteTime    int64          `protobuf:"varint,10,opt,name=writeTime" json:"writeTime,omitempty"`
	CommitTime   int64          `protobuf:"varint,11,opt,name=commitTime" json:"commitTime,omitempty"`
	EvmTime      int64          `protobuf:"varint,12,opt,name=evmTime" json:"evmTime,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *Block) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *Block) GetTxRoot() []byte {
	if m != nil {
		return m.TxRoot
	}
	return nil
}

func (m *Block) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetWriteTime() int64 {
	if m != nil {
		return m.WriteTime
	}
	return 0
}

func (m *Block) GetCommitTime() int64 {
	if m != nil {
		return m.CommitTime
	}
	return 0
}

func (m *Block) GetEvmTime() int64 {
	if m != nil {
		return m.EvmTime
	}
	return 0
}

type Blocks struct {
	Batch []*Block `protobuf:"bytes,1,rep,name=batch" json:"batch,omitempty"`
}

func (m *Blocks) Reset()                    { *m = Blocks{} }
func (m *Blocks) String() string            { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()               {}
func (*Blocks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Blocks) GetBatch() []*Block {
	if m != nil {
		return m.Batch
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "version1_2.Block")
	proto.RegisterType((*Blocks)(nil), "version1_2.Blocks")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0xd2, 0xa6, 0xf4, 0x92, 0xa5, 0x1e, 0xc0, 0x42, 0x08, 0x45, 0x5d, 0xc8, 0x14,
	0xa9, 0x65, 0x64, 0x63, 0x62, 0xb6, 0xba, 0x23, 0x27, 0x3a, 0xa9, 0x56, 0xeb, 0x38, 0xb2, 0x8f,
	0xc2, 0x0f, 0xe0, 0x87, 0x23, 0x5f, 0x52, 0x12, 0xc6, 0xf7, 0xbe, 0x67, 0xdf, 0xd3, 0x1d, 0xe4,
	0xcd, 0xd9, 0xb5, 0xa7, 0xba, 0xf7, 0x8e, 0x9c, 0x80, 0x0b, 0xfa, 0x60, 0x5c, 0xb7, 0xfb, 0xd8,
	0x3f, 0x6c, 0xc8, 0xeb, 0x2e, 0xe8, 0x96, 0x8c, 0xeb, 0x06, 0xbc, 0xfd, 0x49, 0x61, 0xf9, 0x16,
	0xe3, 0x42, 0xc2, 0x6a, 0x8c, 0xca, 0xa4, 0x4c, 0xaa, 0x42, 0x5d, 0xa5, 0x78, 0x02, 0xe8, 0xb5,
	0xc7, 0x8e, 0xde, 0x75, 0x38, 0xca, 0x1b, 0x86, 0x33, 0x47, 0x3c, 0xc2, 0x9a, 0x27, 0x32, 0x4e,
	0x19, 0x4f, 0x86, 0x78, 0x85, 0x62, 0x36, 0x36, 0xc8, 0x45, 0x99, 0x56, 0xf9, 0xfe, 0xbe, 0x9e,
	0x7a, 0xd5, 0x87, 0x89, 0xab, 0x7f, 0xe1, 0xf8, 0x35, 0x19, 0x8b, 0x81, 0xb4, 0xed, 0xe5, 0xb2,
	0x4c, 0xaa, 0x54, 0x4d, 0x46, 0x2c, 0x66, 0xd1, 0x9f, 0xce, 0xa8, 0x9c, 0x23, 0x99, 0x0d, 0xc5,
	0x26, 0x47, 0xdc, 0x41, 0x46, 0xdf, 0xcc, 0x56, 0xcc, 0x46, 0x25, 0x4a, 0xc8, 0x3d, 0xb6, 0x68,
	0x7a, 0x62, 0x78, 0xcb, 0x70, 0x6e, 0xc5, 0x97, 0xdd, 0xa7, 0x6d, 0xd0, 0xcb, 0x75, 0x99, 0x54,
	0x0b, 0x35, 0xaa, 0xd8, 0xe7, 0xcb, 0x1b, 0xc2, 0x83, 0xb1, 0x28, 0x61, 0xe8, 0xf3, 0x67, 0xc4,
	0x3e, 0xad, 0xb3, 0xd6, 0x10, 0xe3, 0x9c, 0xf1, 0xcc, 0x89, 0x2b, 0xc6, 0x8b, 0x65, 0x58, 0x30,
	0xbc, 0xca, 0xed, 0x0e, 0x32, 0xbe, 0x42, 0x10, 0xcf, 0xb0, 0x6c, 0x34, 0xb5, 0x47, 0x99, 0xf0,
	0x9e, 0x36, 0xf3, 0x3d, 0x71, 0x44, 0x0d, 0xbc, 0xc9, 0xf8, 0x80, 0x2f, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0xc8, 0x8a, 0x40, 0xee, 0x01, 0x00, 0x00,
}
