// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oplog.proto

/*
Package oplog is a generated protocol buffer package.

It is generated from these files:
	oplog.proto

It has these top-level messages:
	LogEntry
*/
package oplog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEntry_Type int32

const (
	LogEntry_TransactionList LogEntry_Type = 0
	LogEntry_RollBack        LogEntry_Type = 1
	LogEntry_StateUpdate     LogEntry_Type = 3
)

var LogEntry_Type_name = map[int32]string{
	0: "TransactionList",
	1: "RollBack",
	3: "StateUpdate",
}
var LogEntry_Type_value = map[string]int32{
	"TransactionList": 0,
	"RollBack":        1,
	"StateUpdate":     3,
}

func (x LogEntry_Type) String() string {
	return proto.EnumName(LogEntry_Type_name, int32(x))
}
func (LogEntry_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type LogEntry struct {
	Lid     uint64        `protobuf:"varint,1,opt,name=lid" json:"lid,omitempty"`
	Type    LogEntry_Type `protobuf:"varint,2,opt,name=type,enum=LogEntry_Type" json:"type,omitempty"`
	Payload []byte        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogEntry) GetLid() uint64 {
	if m != nil {
		return m.Lid
	}
	return 0
}

func (m *LogEntry) GetType() LogEntry_Type {
	if m != nil {
		return m.Type
	}
	return LogEntry_TransactionList
}

func (m *LogEntry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "LogEntry")
	proto.RegisterEnum("LogEntry_Type", LogEntry_Type_name, LogEntry_Type_value)
}

func init() { proto.RegisterFile("oplog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0xce, 0x31, 0xab, 0x83, 0x30,
	0x14, 0x05, 0xe0, 0x97, 0xa7, 0xbc, 0x27, 0x57, 0xd1, 0x90, 0x2e, 0x19, 0xc5, 0xc9, 0xc9, 0xa1,
	0xdd, 0x3a, 0x16, 0xba, 0x39, 0xa5, 0xf6, 0x07, 0xdc, 0x6a, 0x10, 0x69, 0xf0, 0x06, 0xbd, 0x4b,
	0xfe, 0x48, 0x7f, 0x6f, 0x51, 0x70, 0x3b, 0x87, 0xf3, 0x0d, 0x07, 0x52, 0xf2, 0x8e, 0xc6, 0xc6,
	0x2f, 0xc4, 0x54, 0x7d, 0x04, 0x24, 0x2d, 0x8d, 0xf7, 0x99, 0x97, 0xa0, 0x24, 0x44, 0x6e, 0x1a,
	0xb4, 0x28, 0x45, 0x1d, 0x9b, 0x2d, 0xaa, 0x0a, 0x62, 0x0e, 0xde, 0xea, 0xdf, 0x52, 0xd4, 0xf9,
	0x39, 0x6f, 0x0e, 0xda, 0x74, 0xc1, 0x5b, 0xb3, 0x6f, 0x4a, 0xc3, 0xbf, 0xc7, 0xe0, 0x08, 0x07,
	0x1d, 0x95, 0xa2, 0xce, 0xcc, 0x51, 0xab, 0x2b, 0xc4, 0x9b, 0x53, 0x27, 0x28, 0xba, 0x05, 0xe7,
	0x15, 0x7b, 0x9e, 0x68, 0x6e, 0xa7, 0x95, 0xe5, 0x8f, 0xca, 0x20, 0x31, 0xe4, 0xdc, 0x0d, 0xfb,
	0xb7, 0x14, 0xaa, 0x80, 0xf4, 0xc1, 0xc8, 0xf6, 0xe9, 0x07, 0x64, 0x2b, 0xa3, 0xd7, 0xdf, 0xfe,
	0xef, 0xf2, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x07, 0x67, 0x06, 0x81, 0xae, 0x00, 0x00, 0x00,
}
